### ISSUE TITLE
[Bug] Custom Instance ID not working.

### ISSUE THREAD

**Issue by GenesisAria** [vrcx-team/VRCX#1006]
~~is currently <world_id>**:**<instance_id>~~

~~this doesn't seem to work, or not anymore~~

~~should be~~

~~<world_id>**&instanceId=**<instance_id>~~

**Comment by Natsumi-sama** [comment]
What's the context? I cannot reproduce.

**Comment by GenesisAria** [comment]
oh wait might be confused what the deal is... alright i didn't inspect the url portion thoroughly enough in vrcx vs the location field...
issue might be different.

if i manually create an instance with a custom id by just replacing the text from the id # to whatever text i want on the website, it works fine, but if i do it via vrcx it just ignores it and generates a fresh instance id #

**Comment by Natsumi-sama** [comment]
I'm really trying but I still can't reproduce, I have a feeling it isn't something simple, if you press `Ctrl + Shift + I` in console tab you can see the URI VRCX executes maybe this will help you narrow it down, I noticed VRCX doesn't set a ref, I'll add that but I don't think it's the cause.

**Comment by GenesisAria** [comment]
I tried in both nightly and the main branch and the issue happens in both.

Also i am referring to self-invite, not launch (i never use launch because i have complicated launch commands i use from custom launchers)

**Comment by GenesisAria** [comment]
You cannot set a custom instance id in the normal tab, i did mention it

> this is in the legacy tab ofc because the normal tab doesn't give the option to put in custom id's

**Comment by GenesisAria** [comment]
As far as creating an instance in normal tab then switching to legacy, i could not have thought of this... this wasn't a single case thing, it was doing it for like a couple weeks, and i didn't know the cause.

**Comment by Natsumi-sama** [comment]
I've made it so clicking the tabs will regenerate the instance to be as expected, A side affect of this is if you create an instance then go to legacy tab and back the created instance will be lost.

**Comment by Natsumi-sama** [comment]
I can't even begin to understand what the game is trying to do there, seems like a client issue.

**Comment by Natsumi-sama** [comment]
I'm guessing they have a dictionary key using instanceId without worldId and they're expecting it to be unique enough to not worry about collisions, except they didn't consider the possibility of manually specifying instanceId, pretty sure it will be phased out soon anyway, I'm betting custom instance IDs will be gone before this bug gets fixed.

**Comment by Natsumi-sama** [comment]
It's known that they aren't supported anymore and are slowly being removed, hence "legacy", I assume group names are the intended replacement.
