### ISSUE TITLE
[Feature Request] Extend Auto Status Change functionality

### ISSUE THREAD

**Issue by IDex** [vrcx-team/VRCX#1014]
The auto status change could be powerful tool for keeping our friend groups separated by automatically preventing people from joining when in an instance with a friend. This would require the status change condition to be whether or not a friend is in the current instance. The current functionality prevents us staying green when in a populated public world for example, in which case most people wouldn't object to others joining.

Instead of just (Alone/Company) we could have other combinations of conditions such as (No friend/With friend). This could be implemented using variety of UI components depending on how much customization is wanted (there seems to be some desire to expand this setting, see #905 and  #934). In the simplest case we could add a button or a set of dropdowns for selecting the triggering condition for status change.

**Comment by Natsumi-sama** [comment]
Give latest nightly build a try and let me know if it works as expected for you.

**Comment by IDex** [comment]
The nightly version seems to cover this use case nicely, and more. Thank you.

**Comment by IDex** [comment]
After some testing it seems the friend detection is failing if the friend(s) in the instance are on orange.

**Comment by Natsumi-sama** [comment]
Not sure what's going on there, could try debug it by opening console with `Ctrl + Shift + I` and pasting this line `$app.lastLocation.friendList` into the console and see if friends in your instance are missing from the list.

**Comment by IDex** [comment]
With a single friend in the instance the size returned is 1.
So the problem isn't the status, but the number of friends due to (https://github.com/vrcx-team/VRCX/blob/f0cd64c3aa7f4cd97370b9479ba41258984846c9/html/src/app.js#L6256) ?
`withCompany = this.lastLocation.friendList.size > 1;`

**Comment by Kiokuu** [comment]
assuming self isn't added in friendList, that should be >= 1

**Comment by IDex** [comment]
Self wasn't in the list I got using the debugger as instructed above

**Comment by Natsumi-sama** [comment]
Thanks for the testing guys, silly mistake on my part.
