### ISSUE TITLE
[Bug] Screenshot Helper metadata functions don't work on Linux

### ISSUE THREAD

**Issue by DigitalStarSys** [vrcx-team/VRCX#1037]
**Describe the bug**
When using VRCX as installed via the Linux install script, none of the metadata features work. Enabling the feature does not add metadata to images, and enabling "Modify Filename" does not modify the filename whatsoever. My initial theory was that VRCX couldn't properly see the files, but clicking "Last Screenshot" *does* open the most recent image. (The "Screenshots" common folder errors out with a 'folder doesn't exist' error, but the "Photos" common folder does.)

**To Reproduce**
1. Enable the screenshot helper, and "Modify filename".
2. Open VRChat via Steam.
3. Take a photo using the camera, or a screenshot.
4. Check the image in the metadata viewer, and in the file explorer.
5. The name does not include world ID, and there's no metadata in the photo.

**Expected behavior**
There should be metadata (world ID, players, etc.) embedded in the files, and the filenames should be modified.

**Screenshots**
![image](https://github.com/user-attachments/assets/e39fadf9-4ca1-409f-884f-928fd1a409a7)
*Example of Modify Filename not functioning.*

![image](https://github.com/user-attachments/assets/cfa02bcb-f75c-4986-aeca-c6cc966920df)
*What happens if you click the Photos button in Common Folders.*

![image](https://github.com/user-attachments/assets/8fa87552-ef09-4f56-addf-3e4cb9a598ce)
*What happens if you click the Screenshots button in Common Folders.*

**What version you are running**
VRCX 2024.12.03

**Comment by Natsumi-sama** [comment]
It is actively being worked on, you can try out a test build here https://github.com/rs189/VRCX/releases

**Comment by DigitalStarSys** [comment]
Gotcha, thanks :) Will use that for now.
