### ISSUE TITLE
[Feature Request] Exclude VideoErrors from text to speech

### ISSUE THREAD

**Issue by SilvyPaws** [vrcx-team/VRCX#1039]
**Explain in detail what your suggested feature would be used for.**
My friend uses the speech to text to read out join/leaves for them which is very useful, however, if a world has a video player that spams VideoErrors because the video is not available or stream is having issues, it'll go on forever and they have to mute it.

**Describe how it would look if it requires a UI.**
I don't think this will need a UI change, however, if you want to add an option to exclude errors from text to speech, a toggle under the Text To Speech for ignoring Errors and/or VideoErrors would be really appreciated.

**Explain why people would want to use it.**
Having to listen to it spamming _VideoError: [generic] Unable to download webpage: [WinError 10061] No connection could be made because the target machine actively refused it (caused by TransportError('[WinError 10061] No connection could be made because the target machine actively refused it'))_ over and over and over again is exhausting, having an option to disable it saying those errors would be really nice.

**Comment by Natsumi-sama** [comment]
TTS messages are linked to `Notification Filters`, if you disable `Miscellaneous Events` it will no long play video errors over TTS.

**Comment by SilvyPaws** [comment]
> TTS messages are linked to `Notification Filters`, if you disable `Miscellaneous Events` it will no long play video errors over TTS.

Oh! We didn't know that! Thanks for the fast reply! <3 <3
