### ISSUE TITLE
[Bug] Auto login doesn't work anymore (?)

### ISSUE THREAD

**Issue by NateWolf777** [vrcx-team/VRCX#1040]
It is just me being dumb or autologin/save credential doesn't work anymore (?)

Everytime I exit the app, I need to put my username and password again

I'm using the latest version

**Comment by Natsumi-sama** [comment]
Give latest nightly build a try.

**Comment by Myrkie** [comment]
some users said they fixed this issue with a reinstall, either update to nightly or reinstall your current build, either way a reinstall will occur and most likely fix the issue.

**Comment by NateWolf777** [comment]
Thank you for the recommendation, I'm using nightly version for now

**Comment by JHawkley** [comment]
I also am experiencing this bug after a full Windows reinstall, using VRCX 2024.12.03.  VRCX is freshly installed, but does not auto-login or store my user information.  I have to do the e-mail verification every time I boot, at the moment.  I'll probably just tough it out until you kick out the fix to stable.
