### ISSUE TITLE
[Bug] Friend Requests do not show up in Friend Log

### ISSUE THREAD

**Issue by Erallie** [vrcx-team/VRCX#1046]
## Describe the bug
In the Friend Log, I have my filters set to "Friend" and "Friend Request". And it is *only* showing whenever I make a friend, and not when I either send or receive a friend request.

## To Reproduce
1. Change the Friend Log filter to "Friend" only.
2. Change the Friend Log filter to include both "Friend" and "Friend Request".
3. Receive a friend request in VRChat.
4. It does not appear in the log.

## Expected behavior
I would expect a log to appear in the Friend Log when I receive a friend request, as long as I have the "Friend Request" filter enabled.

## Screenshots
This is how my friend log looks like:
![image](https://github.com/user-attachments/assets/26c940c8-e6c8-415a-bb9b-fd082ebdf317)

I have received **a lot** of friend requests throughout the time displayed in the screenshots, while still having the "Friend Request" filter enabled.

## What version you are running
VRCX 2024.12.03

**Comment by Myrkie** [comment]
seems to work fine for me on latest nightly build 2024-12-21

**Comment by Turretoforth** [comment]
I think there's a misconception here, the "Friend request" log is when you send a request, not when you receive one.
The received friend requests are in the notifications until you accept or refuse them

**Comment by Myrkie** [comment]
are you sending friend requests via VRCX or via VRChat/Website? VRCX can only display friend requests that were created within VRCX.

**Comment by Erallie** [comment]
> I think there's a misconception here, the "Friend request" log is when you send a request, not when you receive one. The received friend requests are in the notifications until you accept or refuse them

Ahh yes. That is definitely where the problem lies then. I don't know how many times I actually *sent* a friend request within the period of time in the screenshot. Now that I checked, the friend requests I receive *do* show up in the notifications. Thank you!
