### ISSUE TITLE
Virus detected?

### ISSUE THREAD

**Issue by BloodWorkVR** [vrcx-team/VRCX#363]
When trying to open it, it says its infected with IDP.GENERIC

**Comment by BloodWorkVR** [comment]
CefSharp.BrowserSubprocess.exe is causing it

**Comment by BloodWorkVR** [comment]
I added it to exception and works, just wanted to say that since i didnt see any recent reports and this just popped up today

**Comment by Natsumi-sama** [comment]
Just Avast being Avast I recommend uninstalling it, Windows Defender is good enough these days.

**Comment by Myrkie** [comment]
agreed, windows defender has come a long way you can get along just fine running stock windows defender, Malwarebytes if your confident you need a secondary anti virus / malware though Malwarebytes can absolutely destroy system performance while its performing scans and Realtime protection.

**Comment by BloodWorkVR** [comment]
i sadly cannot use Windows Defender for some reason. Im using Avast One atm. Windows 11 broke it somehow in a Update and its been months like that. It keeps telling me to install an App to open Windowsdefender-links and i tried multiple fixes from the Internet but nothing helped^^

**Comment by PennyBunny** [comment]
Windows 11 moment
