### ISSUE TITLE
[Bug] Feed is not automatically updated in time

### ISSUE THREAD

**Issue by ScrapW** [vrcx-team/VRCX#402]
For a while, my VRCX was able to refresh the feed in time, and even when my friends changed Avatars in Avatar world, VRCX was able to record all of their Avatars (at least I think all of them were recorded).
But in the recent time, my VRCX can't refresh the feed automatically in time (especially GPS and Avatar categories). It only refreshes when I manually click the "Refresh friends" button. At this time the time from the last Feed may be up to 20mins.

**Comment by Natsumi-sama** [comment]
Seems like your web socket is failing to connect, clicking "Refresh friends" will attempt to reconnect but it looks like that didn't fix it. Open up the VRCX devtools window by pressing `Ctrl + Shift + I` then select the console tab and you should be able to see the error of it failing to connect there. Also if you are using a VPN you need to exclude both `VRCX.exe` and  `CefSharp.BrowserSubprocess.exe`.
