### ISSUE TITLE
[Question] Linux build support

### ISSUE THREAD

**Issue by Kieaer** [vrcx-team/VRCX#441]
Linux build guide is dead because dotnet472 link no longer works in wine.
I tried to build my own on Linux, but since .NET 4.7.2 is only supported on Windows OS, I can't build it.
Builds on Linux are from .NET 5.0.0 and higher.

How to build VRCX in Linux?

**Comment by Natsumi-sama** [comment]
Cef sharp will only natively work with windows even with .NET 5.0 https://github.com/cefsharp/CefSharp/wiki/General-Usage#software-requirements
You'll need to either update winetricks or find a mirror for .NET 4.7.2 and I'm sure there are hundreds available.
