### ISSUE TITLE
[Feature Request] able to resend code to email

### ISSUE THREAD

**Issue by NekoSuneVR** [vrcx-team/VRCX#445]
i requesting for able to resend email code. since when i recieved code it said was invalid and wasn"t able resend new code. but browser able login fine.

**Comment by Natsumi-sama** [comment]
I've also experienced this issue with the game client attempting to login and being sent an email verification code when having 2FA enabled, VRCX and the game expects you to enter in a 2FA code not the email verification code. I may add an option to enter in a email code instead when 2FA is enabled.
