### ISSUE TITLE
[Feature Request] Have option for instead of asking "Start another instance?", show the current instance.

### ISSUE THREAD

**Issue by nullstalgia** [vrcx-team/VRCX#449]
Sometimes I try to open VRCX by typing it into the Start Menu, and that asks if I want to open a new instance of the app. Instead, it should match the behavior of apps like Discord, where it just un-minimizes and focuses the already-running instance.

**Comment by Myrkie** [comment]
https://github.com/pypy-vrc/VRCX/issues/428

**Comment by nullstalgia** [comment]
Editing the Target of my VRCX shortcut to:

`"C:\Program Files\VRCX\VRCX.exe" --ignore-instance-check --config="C:\Users\<Name>\AppData\Roaming\VRCX\VRCX.sqlite3"`

Still brings up the prompt?

**Comment by Myrkie** [comment]
launch arguments really need to be refined https://github.com/pypy-vrc/VRCX/blob/master/StartupArgs.cs#L40

**Comment by nullstalgia** [comment]
Looks like my Target needs to be:

`"C:\Program Files\VRCX\VRCX.exe" /uri=vrcx:///`

Since that makes it set the LaunchCommand variable with something, skipping the prompt.

**Comment by Myrkie** [comment]
give it a try.

**Comment by nullstalgia** [comment]
You misunderstood, I already tried and it works, that's why I shared it. 😅 

But I do think a checkbox in Advanced or General for this would be preferred, and likely not too hard to set up (depending on when configs are loaded, I haven't checked).
