### ISSUE TITLE
Clearing Game Log

### ISSUE THREAD

**Issue by XenoxUSser** [vrcx-team/VRCX#450]
is there a way to clear the Game Log (join and leaves of world and ect) cause i reached my max table size now it doesent do anything anymore and clearing the vrcx cache does nothing

**Comment by Natsumi-sama** [comment]
Make sure debug logging is enabled https://github.com/pypy-vrc/VRCX/issues/443#issuecomment-1336856875

**Comment by XenoxUSser** [comment]
> Make sure debug logging is enabled [#443 (comment)](https://github.com/pypy-vrc/VRCX/issues/443#issuecomment-1336856875)

its enabled 
![image](https://user-images.githubusercontent.com/33065711/207492893-a98c24bb-dd60-4b8c-b416-bf9fae42dda0.png)
![image](https://user-images.githubusercontent.com/33065711/207492997-ab32d881-50a8-43a5-943d-a35bcc27851d.png)

**Comment by Natsumi-sama** [comment]
The log size in database is unlimited, this is just the size of the table.
Debug logging in VRChat not VRCX, click the link and follow the instructions

**Comment by XenoxUSser** [comment]
> The log size in database is unlimited, this is just the size of the table. Debug logging in VRChat not VRCX, click the link and follow the instructions

and enabling that will make new things show in the game log even with max set table size reached?

**Comment by XenoxUSser** [comment]
> Yes.

ok thank you, you can close this then now ^w^

**Comment by XenoxUSser** [comment]
> Yes.

nvm reopening this do i need to restart anything cause i had vrchat already running someone just joined and left while i also changed a playing video and nothing has changed in the game log

**Comment by XenoxUSser** [comment]
> You need to rejoin the instance yes

ok so tried and nothing happened not even the video got registered in game log

**Comment by XenoxUSser** [comment]
> Try restart your game and make sure you have nothing in the search box and no filters set.

nvm only logged my homeworld and then gave up

**Comment by XenoxUSser** [comment]
> Try restart your game and make sure you have nothing in the search box and no filters set.

I FIGURED IT OUT I WAS SOMEHOW PLAYING ON AN TEMPORARY SUSPENDED ACCOUNT BRUH
