### ISSUE TITLE
Getting Logs From Another Account.

### ISSUE THREAD

**Issue by AvocadoFemboy** [vrcx-team/VRCX#454]
![image](https://user-images.githubusercontent.com/103474655/208335377-f1172c72-ef0f-47d0-b29c-dc764105c743.png)
This was my other account I was trying to get the logs from it. I'm wondering where I could find these logs sense they are still on my old account.

**Comment by Natsumi-sama** [comment]
This info is from game logs, VRCX stores game logs in the VRCX database it can be found here `%AppData%\VRCX\VRCX.sqlite3`

**Comment by AvocadoFemboy** [comment]
Thanks! Very helpful. Also, if anybody else needs to view the logs you can use this website. https://inloop.github.io/sqlite-viewer/

**Comment by Myrkie** [comment]
> Thanks! Very helpful. Also, if anybody else needs to view the logs you can use this website. https://inloop.github.io/sqlite-viewer/

Excessive database size may cause this website to lock up and crash, recommended method is to use DB Browser https://sqlitebrowser.org/

**Comment by AvocadoFemboy** [comment]
> 

Okay, I just used it and it got pretty much everything I had. I'll keep it in mind.
