### ISSUE TITLE
Unable to launch on Linux (followed all instructions)

### ISSUE THREAD

**Issue by sylviiu** [vrcx-team/VRCX#455]
When I attempt to launch VRCX on my linux machine, it seems to open, but crashes immediately.

![image](https://user-images.githubusercontent.com/95180094/209204218-f98095bd-b962-4a04-bcc8-54f0dcdaf6e2.png)

I also ran this in the terminal, and logs read `Unhandled Exception: SharpDX.SharpDXException: HRESULT: [0x887A0002], Module: [SharpDX.DXGI], ApiCode: [DXGI_ERROR_NOT_FOUND/NotFound]` -- is there anything I can do to fix this?

**Comment by Natsumi-sama** [comment]
It's a known issue and is being worked on but will take awhile to fix, for now all you can do is downgrade VRCX.
