### ISSUE TITLE
VRCX is detected a virus.

### ISSUE THREAD

**Issue by AvocadoVR** [vrcx-team/VRCX#460]
My window anti-virus keeps on deleting VRCX due to saying there is a virus within the program.

**Comment by Natsumi-sama** [comment]
Either whitelist VRCX in your anti-virus program or uninstall your anti-virus and use Windows defender instead.

**Comment by jwise3** [comment]
Windows defender also detects it as well.

**Comment by AvocadoVR** [comment]
> Windows defender also detects it as well.

Try whitelisting it.

**Comment by Myrkie** [comment]
ive suggested to Natsumi to, submit the VRCX installers to Microsoft WDSI file submission for a whitelist by Microsoft, hopefully this will solve the problem with false positives with at least Windows defender, so far other virus providers like Malwarebytes hasn't found this false positive

**Comment by Natsumi-sama** [comment]
I've release a hotfix, is this also detected as a virus?

**Comment by AvocadoVR** [comment]
It hasn't had any issues for me! Im a few weeks late but this hotfix worked.
