### ISSUE TITLE
Windows sees VRCX as malware

### ISSUE THREAD

**Issue by jwise3** [vrcx-team/VRCX#463]
Since the latest update Windows has started to recognize VRCX as a trojan. As a result the program keeps getting removed when I install the latest version. I would prefer to not have to have to add exception in my protection for this.

![image](https://user-images.githubusercontent.com/59040046/210151192-9d993099-95fc-4ad8-b5b7-8834713cffef.png)

**Comment by AvocadoVR** [comment]
https://github.com/vrcx-team/VRCX/issues/460

Already has been reported. Try whitelisting it.
