### ISSUE TITLE
[Feature] Highlight friends in game log

### ISSUE THREAD

**Issue by 64766C** [vrcx-team/VRCX#469]
I often find myself scrolling through the game log checking if friends joined while I was napping but it gets really busy in worlds like rest & sleep. It would be nice to either have an option or just by default to highlight friends in the game log. An icon similar to what Player List has would be fine or recoloring the name or the whole line would also work.

Note that I would not like to do this with a filter ("show only friends") because that would hide important information like when I myself switched instances, or a friend leaving could actually just be you leaving the instance because the same OnPlayerLeft is fired.

**Comment by Natsumi-sama** [comment]
Maybe something like this, but it wont dynamically update though due to performance reasons.
![Screenshot](https://user-images.githubusercontent.com/11171153/213910034-aded8e35-d5dc-4b98-a957-02c2c1e5cc32.png)
