### ISSUE TITLE
2fa suddenly?

### ISSUE THREAD

**Issue by astayeager** [vrcx-team/VRCX#474]
i had not  enabled 2fa  on  vrcx  but since yesterday it was asking me to enter my code to login but i never had a code not sure what to do because theres no  options plz help

**Comment by Natsumi-sama** [comment]
Make sure your VRCX is up to date and check your email for a 2FA code.

**Comment by Myrkie** [comment]
can confirm just had this happen just before the new nightly update dropped, though i do have 2FA enabled.

**Comment by astayeager** [comment]
> Make sure your VRCX is up to date and check your email for a 2FA code.

i never received a code

**Comment by NiteXXX** [comment]
This just happened to me. Any way to fix it ?

**Comment by Myrkie** [comment]
> This just happened to me. Any way to fix it ?

update your vrcx to the latest version
