### ISSUE TITLE
[Feature Request] Group Owner Link

### ISSUE THREAD

**Issue by zkxs** [vrcx-team/VRCX#478]
In the Group Info dialog please consider adding a link to the group owner. 

I find myself commonly having to go into the JSON to grab the `ownerId` then tossing that into the Direct Access button to figure out who runs such-and-such group.

**Comment by Natsumi-sama** [comment]
It's already there, are you on an old version can you send a screenshot?

**Comment by zkxs** [comment]
Oh, I see it now. That didn't look like a clickable link to me, sorry.

For future travelers:
![image](https://user-images.githubusercontent.com/1807509/215363870-a2360f66-7cdb-4c45-938b-70d48b8d3fe7.png)
