### ISSUE TITLE
[Feature Request] Change VRCX appdata folder location

### ISSUE THREAD

**Issue by Nyanpasu1** [vrcx-team/VRCX#481]
VRCX by default put all its data on filepath : 

C:\Users|[user]\AppData\Roaming\VRCX

This will be problem when you changing to new PC, and you need to recopy the folder to new PC which means it is not portable at all.

i prefer the data location to its own folder or app directory as example :

D:\VRCX

Is it possible as feature?

**Comment by Myrkie** [comment]
VRCX already supports relocation of the VRCX sqlite database https://github.com/vrcx-team/VRCX#vrcx-launch-parameters

**Comment by Natsumi-sama** [comment]
Can't be done because the file is in use while the app is running. `config` launch option works good enough for this.
