### ISSUE TITLE
2FA suddenly active and doesn't let me log in

### ISSUE THREAD

**Issue by ShojiButts** [vrcx-team/VRCX#484]
I saw a few issues posted here about this too, but last week my VRCX all of a sudden logged me out and is now asking for my 2FA code, and when I get my email from VRC and put in the code, it gives me an error that says "No secret to match against code!"

Any help or idea what's going on?

**Comment by Natsumi-sama** [comment]
Try latest nightly build https://github.com/Natsumi-sama/VRCX/releases/latest and make sure you can login to the VRChat website normally.
