### ISSUE TITLE
Can't Login, Error 401

### ISSUE THREAD

**Issue by GODZILLA6337** [vrcx-team/VRCX#486]
Newest version and last 2022 version won't let me login. Keeps giving me a 401 error and saying my "Username is required, Password is required" even though I've put them in. Tried my Current username and my old username, Email, New password old password. Nothing is working.
![ajnbvimage](https://user-images.githubusercontent.com/66243273/219848928-71acd652-18f8-4f72-bccc-ce6621b922d9.png)

**Comment by Myrkie** [comment]
are you able to login via [vrchat.com](https://vrchat.com/home/login)?

**Comment by GODZILLA6337** [comment]
I am able to login to the site yes. So sorry for the super delayed reponse. I was attending a convention.
I'm able to login normally on the site just not the vrcx program.

**Comment by Myrkie** [comment]
it could be caused by your name if it has odd symbols, I remember that happening in the past not sure if its been fixed.

**Comment by GODZILLA6337** [comment]
It doesn't. I wish that were the case lol
My name is all standard letters. Not even any numbers

**Comment by Myrkie** [comment]
Then im unsure.

**Comment by GODZILLA6337** [comment]
Ah okie.

**Comment by GroovyTeacup** [comment]
Does your password have any special characters in it(this feels so sketchy to ask, lol)? I'm not sure if VRCX escapes those properly, but mine does and I don't have issues so I'm not sure.

**Comment by Myrkie** [comment]
> Does your password have any special characters in it(this feels so sketchy to ask, lol)? I'm not sure if VRCX escapes those properly, but mine does and I don't have issues so I'm not sure.

i remember someone having issues with this too its why i brought it up with the username aswell

**Comment by GroovyTeacup** [comment]
Just took a look and the login func does handle special chars properly. Did this only start happening to you after you changed your password? You could try to rename your VRCX.sqlite3 to something else and restart to see if something that's been cached is messing up your login somehow.

The default location is in %AppData%\VRCX

**Comment by GODZILLA6337** [comment]
Okie dokie. I'll do the fresh install. A fresh reboot would help as well correct?

**Comment by GroovyTeacup** [comment]
You should be fine to just move the appdata folder while the program is closed and then re-opening VRCX. This'll reset everything back to defaults and help narrow down the issue.

**Comment by GODZILLA6337** [comment]
Okie dokie. I'll letcha know what happens

**Comment by GODZILLA6337** [comment]
What do I do about tis file?

**Comment by Myrkie** [comment]
uhh you dont have to reinstall vrcx, only move the folder listed above that will clear vrcxs settings and cache and then try to login again to see if your database has been corrupted.

**Comment by GODZILLA6337** [comment]
![image](https://user-images.githubusercontent.com/66243273/219934687-2a5e2b7e-f810-47ff-a066-85964547e5cc.png)
Ah alright. I did move and rename the folder listed. 
Same results

**Comment by Myrkie** [comment]
uh huh, can you open up the developer console and check the console for any errors? can open it by pressing ctrl shift I, or right click the vrcx icon in the tray and select devtools.

**Comment by GODZILLA6337** [comment]
![image](https://user-images.githubusercontent.com/66243273/219934971-01175ede-2003-4195-9eff-15ee5e5b0534.png)

**Comment by Myrkie** [comment]
uh huh, that looks like the SQL library logic is completly failing so its unable to continue

**Comment by GODZILLA6337** [comment]
ah
What do I do?

**Comment by Myrkie** [comment]
well what it looks like is vrcx is failing to either insert data into the database or failing to create the database, can you verify that the vrcx folder located int `%appdata%\..\VRCX` is gone

**Comment by GODZILLA6337** [comment]
lemme check
I thought I moved it. Might not

**Comment by Myrkie** [comment]
make sure vrcx is completly closed from the tray icon before doing it or else it will not work

**Comment by GODZILLA6337** [comment]
Okie

**Comment by GODZILLA6337** [comment]
Okie I made a new fresh installation on my secondary drive. It said I had 0kb left on my main which is false sine I checked earlier and I had 7gb so ye. I'll see if this installation runs properly

**Comment by Myrkie** [comment]
then im not sure seems like an unusual issue with SQL Lite

**Comment by GODZILLA6337** [comment]
Ah
What can I do on my end?
I'm not educated in code or anything ^^"
I only know just enough to nab pics and fonts from sites through inspect element ^^"

**Comment by Myrkie** [comment]
you could attempt to run older versions of vrcx, or atleast the nightly builds, vrcx can assist with auto installing them from the top left download icon.

**Comment by GroovyTeacup** [comment]
The SQLite error might be unrelated and perhaps it was a buggy call trying to insert something before the new, fresh database was fully initialized. 

Did this only start happening after you changed your password?
If so, the only thing I can think of is VRCX not being able to handle a specific character in your password. Try changing your password to something simple with standard character and see if you're able to log in. Then change it back to your normal pass and try again.

If it does seem to be a problem with your pass, there's probably a certain special character in it causing issues with the encoding.

**Comment by GODZILLA6337** [comment]
I tried running the last version from 2022 and had the same issue.
I changed my password sometime late last year but I hadn't used vrcx since June so I'm not sure.
My password is all standard, Capitals, no special symbols, and numbers

**Comment by GODZILLA6337** [comment]
The Latest change I've made is my username. But It's also just one word all caps, no specials or numbers.
I can't change it for another 77 days tho

**Comment by GroovyTeacup** [comment]
I'm quite unsure why you're having this issue, unfortunately. Somebody else might be able to help.

**Comment by slord399** [comment]
Somthing to see if it makes change,
1. Try nightly build
2. use e-mail address to login
3. check your security software not blocking app

**Comment by GODZILLA6337** [comment]
Okie, which versions are the nightly builds?

**Comment by Myrkie** [comment]
at the top left of vrcx click the download icon and then select nightly 
![image](https://user-images.githubusercontent.com/20288698/219939537-8a878bb1-9515-4ecb-ae96-77d7109f69e0.png)
then click download

**Comment by GODZILLA6337** [comment]
Ahh okie dokie, Ill see if they work

**Comment by GODZILLA6337** [comment]
![image](https://user-images.githubusercontent.com/66243273/219940471-1e1a6cab-1782-4c07-9547-47071d609d54.png)
They keep failing on installation

**Comment by Myrkie** [comment]
failure reason my be related to lack of space on storage volume, clear some space windows tends to run like garbage with less than 15gb remaining

**Comment by GODZILLA6337** [comment]
I installed it to my secondary HDD drive which has over 100gb left on it

**Comment by slord399** [comment]
try fresh install using exe. maybe something broken. https://github.com/vrcx-team/VRCX/releases

**Comment by GODZILLA6337** [comment]
I already did a couple times ^^"

**Comment by slord399** [comment]
Uninstall once, restart machine, install again. how would this sounds?
and are you able to login on vrchat.com using same credidential??

**Comment by GODZILLA6337** [comment]
I shall attempt this

**Comment by GODZILLA6337** [comment]
![image](https://user-images.githubusercontent.com/66243273/219948851-d9dae4de-21ec-4694-9dfa-6d1b123cdeae.png)
No change
I've no clue what to do at this point. It used to work fine in june but not now. I couldn't even login on my older version from june cuz it gave me the same error.

**Comment by GODZILLA6337** [comment]
Same results. Sorry for the delay. I thought I already updated the thread.
Not sure why it doesn't work but oh well

**Comment by Emmet1119** [comment]
I'm having this problem too

**Comment by Natsumi-sama** [comment]
Did you try all of the above troubleshooting steps? can you list the things you've tried and send the full error in the console you're getting.
