### ISSUE TITLE
VRCX Performance Issue

### ISSUE THREAD

**Issue by AvocadoVR** [vrcx-team/VRCX#487]
I have discord and spotify usaully open. Including SteamVR, Oculus, VRChat. I never had lag. When I opened vrcx it dropped my frames from ~60 to around ~11

**Comment by Natsumi-sama** [comment]
Does it happen on older versions or when VRCX is minimized? also try disabling the VRCX SteamVR overlay then restarting VRCX.

**Comment by AvocadoVR** [comment]
I have the steamvr overlay on. But it sometimes it takes more usage than needed it seems.

**Comment by Natsumi-sama** [comment]
The SteamVR overlay is pretty bad in general, once XS overlay update is out of beta it'll get a rework.

**Comment by AvocadoVR** [comment]
Alright!
