### ISSUE TITLE
Two-Factor Authenticator needed.

### ISSUE THREAD

**Issue by BigBoiBill** [vrcx-team/VRCX#489]
![Screenshot 2023-02-18 041723](https://user-images.githubusercontent.com/66810925/219852381-01f6705e-f670-4884-8f1a-1d02105963bb.png)
I get this message and cannot enter my account because I was never prompted before to set up two-factor auth for vrcx. The only other option is to enter a recover code, of which I did not know vrcx had those and don't have any saved. Is there any way I can login?

**Comment by Myrkie** [comment]
please ensure that your on the latest version of VRCX old versions have bugs that will cause this error

**Comment by BigBoiBill** [comment]
> 

thanks, I got it working now

**Comment by Myrkie** [comment]
please close this issue if your issue has been fixed, button at the bottom.
