### ISSUE TITLE
Add to Winget

### ISSUE THREAD

**Issue by ShayBox** [vrcx-team/VRCX#491]
Microsoft has had a built-in package manager for awhile now (winget), most programs are already available with it, I believe you just have to create and pull request a manifest file to the GitHub repository.  
https://github.com/microsoft/winget-pkgs

**Comment by gizmo-ds** [comment]
[Scoop](https://scoop.sh) is also a command-line installation tool for Windows, and I hope it can also receive support.

**Comment by babo4d** [comment]
Hello, I have added `vrcx` to my scoop bucket [scoop-xrtools](https://github.com/babo4d/scoop-xrtools) so you can install it with
```
scoop bucket add xrtools "https://github.com/babo4d/scoop-xrtools"
scoop install vrcx
```

I will see if I can get it into winget and the scoop `Extras` repository.

**Comment by babo4d** [comment]
VRCX is now on winget as `VRCX.VRCX` (https://github.com/microsoft/winget-pkgs/pull/125008).
