### ISSUE TITLE
Vrcx unity project downloader

### ISSUE THREAD

**Issue by Invaliduser81** [vrcx-team/VRCX#496]
The system for it makes 0 sense to me and its insanely confusing how id get 806 files in a tar package, is it not possible to just be able to get the quest and pc version as a unity package?

**Comment by Myrkie** [comment]
can you provide some context about what your talking about, VRCX is a large program now. are you referring to the "Download Unity Package" button in VRCX when your avatar is selected?

**Comment by Invaliduser81** [comment]
sorry didnt see you comment and only got the noti that you closed the issue

**Comment by Invaliduser81** [comment]
and yes i am, after the 3 dots

**Comment by Natsumi-sama** [comment]
the tar package _is_ the unity package, rename it with the file extension `.unitypackage` then drag it into your Unity project window.

**Comment by Invaliduser81** [comment]
oh that would make sense i guess, sorry for the ignorance.
