### ISSUE TITLE
Allow multiple sqlite dbs.

### ISSUE THREAD

**Issue by AvocadoVR** [vrcx-team/VRCX#499]
I used vrcx for awhile but have switch from 2 computers to my current one today. I'd like to have them all be stored onto my current vrcx. Could you add an option to do that.

**Comment by Natsumi-sama** [comment]
Nope it isn't possible with how VRCX was developed, if you don't use both computers at the same time you could sync the database file with a service like OneDrive or Google Drive. I'd backup before trying this as it could cause data lose or corruption of the database.

**Comment by AvocadoVR** [comment]
How would you sync it with google drive?? I have 3 dbs but dont have all my data synced.

**Comment by Myrkie** [comment]
if you have google drive installed it mounts your google accounts cloud storage as a virtual hard drive that can be mapped to, you just have to change the launch argument where vrcx stores the sqlite database `--config="pathtogoogledrive\VRCX.sqlite3"
