### ISSUE TITLE
XSNotifications not sent out on Linux

### ISSUE THREAD

**Issue by galister** [vrcx-team/VRCX#500]
XSNotifications are not being sent on Linux, because game process/steamvr cannot be detected.

https://github.com/vrcx-team/VRCX/blob/be2f2fd98690ddda74ef8f8e9748dc81ec15875c/html/src/app.js#L5681-L5684

When using the AppApi call from the console, the test notifications go out just fine.

Suggestion: Add a 'When to display' setting, like for Desktop Notifications, or simply send the notification unconditionally when running under Wine.

**Comment by Natsumi-sama** [comment]
Ah yea I'll remove that check all together then, also what VRCX version are you running on Linux? If it's latest what steps did you take to get it working?

**Comment by galister** [comment]
I'm still on [`2022.11.04`](https://github.com/vrcx-team/VRCX/tree/v2022.11.04)

**Comment by Natsumi-sama** [comment]
Do you have a windows build environment setup? could you try build the Linux branch, this fix isn't going to be very useful if it can't be used.

**Comment by galister** [comment]
Got a build going with github actions, it starts and runs seemingly fine.
Indicated version is `VRCX 2022.12.30`

**Comment by Natsumi-sama** [comment]
Oh fantastic I'll update the fork now I had reports of that build not working, did you take any special steps with your wine prefix?

**Comment by galister** [comment]
the linux branch as it was a few hours ago built and ran in the same wine prefix just fine. now building the updated branch

**Comment by galister** [comment]
runs as well, same wine prefix, no changes. indicated version `2023.02.18`.

built using https://github.com/galister/VRCX/blob/Linux/.github/workflows/github_actions.yml

**Comment by Natsumi-sama** [comment]
Alright nice I'll update the docs and workflow later.
