### ISSUE TITLE
Incompatibility with VRHandsFrame

### ISSUE THREAD

**Issue by Loupyboy** [vrcx-team/VRCX#502]
VRHandsFrame crashes when the wrist overlay is active.
VRCX overlay doesn't start when VRHF is active.

**Comment by Myrkie** [comment]
working fine here for me interesting.

**Comment by Loupyboy** [comment]
Might be something else, then? I'm also using Desktop+ but it seems to be working fine with either individually. SRanipal is also running most of the time but I haven't noticed any problem yet.

Platform: SteamVR (Vive Pro Eye)
Games tested: VRChat, SteamVR Home
Steps:
→Start SteamVR with VRCX (VRCX is working correctly), then start VRHandsFrame (crashes automatically)
→Start SteamVR without VRCX, then start VRHandsFrame (works correctly), then start VRCX with VRChat (overlay doesn't seem to work)

I'll try starting it with VRC again instead of SteamVR, just to be sure.

**Comment by Loupyboy** [comment]
Mmmmm. It seems to be working fine without Desktop+, which is weird.
