### ISSUE TITLE
[Feature request] Add player info when use camera

### ISSUE THREAD

**Issue by Kieaer** [vrcx-team/VRCX#507]
This's the same as it was originally in knah mod.
Put the information of all players in that instance into a png file using a meta data.

**Comment by GroovyTeacup** [comment]
Note the current release build only features metadata and not the viewer panel. But yea, this is already implemented. It's off by default, and you can enable it in the Advanced settings tab.
![image](https://user-images.githubusercontent.com/61763649/225776946-5b459133-39dd-4bd6-b7c2-4592ab3db77f.png)
