### ISSUE TITLE
[Feature Request] Better Thumbnail Preview

### ISSUE THREAD

**Issue by LIII-Works** [vrcx-team/VRCX#510]
Currently, the thumbnail preview (specifically, favorite friends/worlds/avatars) is small, alongside text.

> Please refer to image 01, the current view

### Whats the suggestion?

I would like to suggest making an alternative view mode as an option that's more focused on thumbnails, with text below it, much like VRChat menu for better world management. And additionally, make it scaleable 

>Please refer to image 02, my suggested view

### Why is this neccessary?

As VRCX has become (if not one of) the main tool for managing local world favorites. Many world travelers will manage (including store, 
 which is swapping world from online to local. And retrieval, swap world from local to online so that a portal can be placed) their favorite world locally using VRCX due to the fact that 400 world favor limit is too small for them.

However, the current VRCX thumbnail preview is too small to identify which world(even harder in VR view using SteamVR or OVR Toolkit), people tend to remember the thumbnail instead of the name of the world, especially _**when they have thousands of worlds**_.

![}(86SIE1D13)FU%FME9K274](https://user-images.githubusercontent.com/56265123/226263844-66a7084c-33aa-43be-8ce7-535f8cb116fb.png)

![image](https://user-images.githubusercontent.com/56265123/226263895-96f91c86-731c-4c3a-b558-1f2bfdfa3577.png)

**Comment by Natsumi-sama** [comment]
You can achieve what your after using custom CSS https://github.com/vrcx-team/VRCX#themes

Here is an example:

**Just larger images**
![Screenshot 2023-03-20 194926](https://user-images.githubusercontent.com/11171153/226267040-f2566684-e748-445a-af06-f5ffbbe07444.png)

.x-friend-item > .avatar {
  width: 80px;
  height: 80px;
}


**Larger image above text**
![Screenshot 2023-03-20 194833](https://user-images.githubusercontent.com/11171153/226267064-37111535-c351-47b8-8269-e0d9b430bd66.png)

.x-friend-item > .avatar {
  width: 290px;
  height: 290px;
}

.x-friend-item {
  display: block;
}


**And if you don't want rounded images you can add**

.x-friend-item > .avatar > img {
    border-radius: 0%;
}
