### ISSUE TITLE
Command Parameter Doesn't work

### ISSUE THREAD

**Issue by Nyanpasu1** [vrcx-team/VRCX#514]
i tried using command parameters, close vrcx, move entire VRCX.sqlite3 to new path and reopen, but it doesnt detect my database and revert to fresh login and i checked it still using default path.

![image](https://user-images.githubusercontent.com/10215304/227810211-9b4a29f1-e7a7-4a4e-9a8b-f25c3fa45d18.png)
![image](https://user-images.githubusercontent.com/10215304/227810213-588fbef7-b903-4f03-a280-326a63eaf7db.png)

**Comment by Natsumi-sama** [comment]
The Launch Options dialog is for VRChat not for VRCX, you need to launch VRCX.exe with the config parameter one method of doing this is creating or editing a shortcut for VRCX.

**Comment by Myrkie** [comment]
the launch parameters pertain the the launch parameters of the application, your looking at launch parameters of the Vrchat, if you want to apply launch options to vrcx, right click on vrcx.exe and create a shortcut, this in the shortcuts "target" add the launch options you want at the end of the target after the exe

![image](https://user-images.githubusercontent.com/20288698/227810618-5117eb00-45a0-4af6-a947-d1bc8c7948f3.png)

**Comment by Myrkie** [comment]
clarification should be done, renaming the button to "VRChat launch options" aswell as the window might be better for clarity in the future.

**Comment by Myrkie** [comment]
cache for cef cant not be easily relocated so that will probably stay within appdata until vrcx gets rewritten with a different framework

**Comment by Myrkie** [comment]
you can make a feature request yes, but that doesn't mean it will be completed.
