### ISSUE TITLE
[Feature Request] Allow Database Relocate using GUI or Launcher

### ISSUE THREAD

**Issue by Nyanpasu1** [vrcx-team/VRCX#515]
**Description of the Feature**
Right now, if you want to relocate the database VRCX.sqlite3, you need to manually do that by creating vrcx shortcuts and then right click > properties > add command line , and this process are absolutely not user friendly at all.

**Why is this necessary**
User Friendly and High Customization is one of most important features on the apps, and it will be great if i can freely relocate database within a simple launcher or there is automatic process to make it easier.

**Feature Details**
There is two option that you can choose, actually i prefer option 1 if it is possible.
- Option 1 : Change appdata default filepath to its own vrcx folder like how portableapps works instead of storing database in local appdata folder
- Option 2 : Choose custom database path inside the apps itself or might be using "launcher" to enable it will be great.

**Comment by Natsumi-sama** [comment]
The setup deletes the entire VRCX folder on upgrade so allowing users to store their databases in that folder isn't a great idea.
I'll rename the launch dialog title to prevent confusion.
The database location cannot be configured because the database stores all of the app configuration.

**Comment by Natsumi-sama** [comment]
Creating a whole launcher for a feature that's very rarely used isn't very practical.
