### ISSUE TITLE
[Feature Request] Add Recently used display names to a friend

### ISSUE THREAD

**Issue by EinDev** [vrcx-team/VRCX#518]
Sometimes you have friends which keep updating their display name. While you can see the changes in the friend log, it would be helpful if you could see previuously used names inside VRCX.

Something like Steam's "This user also played as (...)"

![grafik](https://user-images.githubusercontent.com/12981672/229572278-c1e121bd-1bd2-460b-bb55-d42c478c6d99.png)

**Comment by TayouVR** [comment]
that seems to be a thing already
![image](https://user-images.githubusercontent.com/31988415/229576351-6581db3b-5961-460c-8c1b-71fd638001f3.png)

**Comment by BLANKE1** [comment]
Yeah this already exists, VRCX just needs to log the friend that changed their name though. VRCX can't get that data from the network
