### ISSUE TITLE
Cant Change Image

### ISSUE THREAD

**Issue by Nothingoru** [vrcx-team/VRCX#520]
I cant change my Image on avatar 
![wow](https://user-images.githubusercontent.com/81114053/230762437-bc26f250-395a-4c51-9608-4fbc49916530.png)
How do i fix this?

**Comment by Natsumi-sama** [comment]
Press `Ctrl + Shift + I` select console tab then run `$app.debugWebRequests = true;` then try upload again and screenshot the console after.

**Comment by Nothingoru** [comment]
Didnt work same error

**Comment by Myrkie** [comment]
> Didnt work same error



> Press `Ctrl + Shift + I` select console tab then run `$app.debugWebRequests = true;` then try upload again and **screenshot the console after.**

**Comment by Nothingoru** [comment]
still not working
