### ISSUE TITLE
[Feature Request] OSC integration with the inclusion of useful system parameters

### ISSUE THREAD

**Issue by dallytaur** [vrcx-team/VRCX#523]
It would be nice to have always see OSC integration pulling friends joined friends leave and notifications in general.  As well as being able to omit them as text chat messages.

Also, it would be nice if we could get a lot of OSC hooks that makes avatars able to have access to parameters such as the time, system load, memory usage, FPS, or or even parameters that are not linked standard full body tracking(example putting vive  tracker on your dog so they can represented with a model in vrc.  Little parameter that could be available is a birthday parameter.

Another use would be a system similar to saved parameters, but is stored VRCX and may be accessible via the OSC in the world all have global parameters accessible by multiple avatars.

How adorable would be if you are able to play in animation based on someone accepting a friend request.  More having a properly integrated clock on your avatar.  Or if your frame rate drops below a certain value your avatar reacts accordingly.  or on your birthday.  You have a party hat on your head

While I feature like this may be a bit on the side when it comes to the VRCX  for a system like this to become standardised and existing program would aid in confirming such standard.

Sorry for the terrible English  I'm not the best English so I hope I meet something that people understands

**Comment by Natsumi-sama** [comment]
This request is far too out of scope for VRCX.
