### ISSUE TITLE
[Feature Request] Search box for Group member lists

### ISSUE THREAD

**Issue by Gentlecat2210** [vrcx-team/VRCX#527]
As an owner of a large group, I would like to be able to search through the members of the group to see who might (not) be there.
![image](https://user-images.githubusercontent.com/62384836/234387910-82919fd4-d8c6-46a9-933b-3171a0af770e.png)

**Comment by Natsumi-sama** [comment]
I'll wait till VRC adds server side search so I don't have to implement this twice, also VRC limits loading in about 5100~ members max meaning this wouldn't work for larger groups. For now there is an option to save the JSON to a file that you can then search through.
