### ISSUE TITLE
[Feature request] Plugin support

### ISSUE THREAD

**Issue by Kieaer** [vrcx-team/VRCX#528]
![image](https://user-images.githubusercontent.com/44261958/234895759-477c2dc7-0f2b-4282-b5eb-1d6e6fdbc7e0.png)
https://github.com/vrcx-team/VRCX/issues/228#issuecomment-864916101

Can this be implemented?
I'm thinking of making a plugin. ex) Automatic accept join request for a specific friend, integration with discord, etc.

**Comment by Natsumi-sama** [comment]
Your best options are:
Using `custom.js` in `%AppData%\VRCX\` to run your own JS code at startup.
Making a pull request to the repo.

**Comment by Kieaer** [comment]
Flie name must be ``custom.js``?

**Comment by Myrkie** [comment]
> Flie name must be `custom.js`?

yes

**Comment by GroovyTeacup** [comment]
> How to run code when a player joins the current world instance using VRCX storage?

You could hook `$app.methods.addGameLogEntry` or poll something like the current instance player list and checking for changes See `$app.methods.getCurrentInstanceUserList` and how it stores user entries in `currentInstanceUserList.data`

There's probably like 100 different ways to do this with how fucked up the codebase is, but `addGameLogEntry` will be your entry point for a join event being logged for the most part.

**Comment by Kieaer** [comment]
@GroovyTeacup Is there an example code? App.js is too complex to analyze.
