### ISSUE TITLE
[Maybe a Bug] SteamVR Dashboard won't close

### ISSUE THREAD

**Issue by AvocadoVR** [vrcx-team/VRCX#530]
**Describe the bug**
I may be wrong about this but sense I had performance issues caused in the past I would like to bring it up. I've been having issues with my steamvr and after a certain period of time my dashboard just won't close. I have remove ovr advance settings before but not VRCX. I have to restart steamvr. This may not be a vrcx bug but I'd rather ask to see if this is possible either way I appreciated it. 

**What version you are running**
VRCX Nightly 2023-04-30T18.36-836c5c9

**Comment by Natsumi-sama** [comment]
The VRCX SteamVR overlay isn't very performant, if you'd like to test if it's causing you issues disable SteamVR overlay in VRCX settings then restart VRCX to fully disable it.

**Comment by AvocadoVR** [comment]
![image](https://user-images.githubusercontent.com/103474655/235573824-d6ea2adb-59e9-4a52-9c82-19687819fc5c.png)
Well this is the only reason why I could assume.

**Comment by Natsumi-sama** [comment]
Only way to know is test and find out.

**Comment by Myrkie** [comment]
the SteamVR overlay itself is based and built ontop of a chrome based browser, which is not very performant at all, other factors can also cause performance issues such as Fragmented Vram which is very common when loading and unloading large avatars with sizes that don't fit within the gap between blocks.

**Comment by AvocadoVR** [comment]
Its most likely not VRCX. I'm back to the drawing board welp.
