### ISSUE TITLE
[Bug] VRCX Fails to latch into SteamVR

### ISSUE THREAD

**Issue by AvocadoVR** [vrcx-team/VRCX#538]
**Describe the bug**
It was working for a bit. Then I reopened vrcx and it latched in then it disappeared again. Now it just dosen't work.

**Screenshots**
![image](https://user-images.githubusercontent.com/103474655/236709416-a0fa8dda-2834-4c46-8f24-f0efef4f9ce4.png)
![image](https://user-images.githubusercontent.com/103474655/236709436-04b612c3-bb61-49e7-861d-c57ad8623bbb.png)

**What version you are running**
Latest Version as of 5/7/2023

**Comment by AvocadoVR** [comment]
Sorry, for the constant bug reports.. Just tryna figure out why this is now happening after working perfectly for the past few hours.

**Comment by Myrkie** [comment]
does the overlay show up in steamvr on your wrist?

**Comment by AvocadoVR** [comment]
Nope.

**Comment by Myrkie** [comment]
> Nope.

do you happen to use multiple gpus or have an integrated GPU?

**Comment by AvocadoVR** [comment]
> > Nope.
> 
> do you happen to use multiple gpus or have an integrated GPU?

Nope, I only use one GPU. I have a Geforce 3060 TI

**Comment by Myrkie** [comment]
if you dont have an IGPU enabled with your dedicated gpu it may just be caused by SteamVR being garbage with assignment.

you can check if its being connected properly by navigating to [SteamVRConsole](http://localhost:27062/console/index.html) in your browser and seeing if you get the connect response message

```
Processing message VRMsg_Connect from VRCX (13740) took 0.0177 seconds
vrclient_VRCX
Received success response from vrserver connect
vrclient_VRCX
```

**Comment by AvocadoVR** [comment]
![image](https://user-images.githubusercontent.com/103474655/236710206-8e194167-78d5-4371-90da-6cb579c7aeb7.png)

**Comment by Myrkie** [comment]
interesting thats starting to look more like a steamvr issue, maybe try restarting steamvr and make sure they are not running as administrator.

**Comment by AvocadoVR** [comment]
![image](https://user-images.githubusercontent.com/103474655/236710597-073886e6-643a-4832-bd40-d16c75e6e3d9.png)

It dosen't automatically run as an admin.

**Comment by Myrkie** [comment]
i mean for both vrcx aswell

**Comment by AvocadoVR** [comment]
![image](https://user-images.githubusercontent.com/103474655/236710720-f753254f-41b9-4ad9-9abb-b3e03d9e2d31.png)

When I restarted it it did work. Although, this is weird.

**Comment by Myrkie** [comment]
it could be because how you have VRCX overlay set to start with steamvr, I don't know exact how VRCX detects the startup of steamvr or if its still running so it may be starting, crashing and then it doesn't detect it has crashed so it stays disconnected until steamvr starts up again I personally set VRCX overlay to start with VRChat only.

**Comment by AvocadoVR** [comment]
![image](https://user-images.githubusercontent.com/103474655/236710817-c66c68e8-145e-4ebe-8458-7f4f298d3a37.png)

Alright, so if I close out of like twice then it just dosen't work in the logs is what happend. Let me try it with VRChat only.

**Comment by Myrkie** [comment]
the steamvr VRCX overlay is rather busted a lot of the time, when XSOverlay finishes its upgrade that it currently runs in beta to using VuPlex WebBrowser VRCX will be abandoning the current overlay method and instead piggyback off of the xsoverlay one

**Comment by AvocadoVR** [comment]
> it could be because how you have VRCX overlay set to start with steamvr, I don't know exact how VRCX detects the startup of steamvr or if its still running so it may be starting, crashing and then it doesn't detect it has crashed so it stays disconnected until steamvr starts up again I personally set VRCX overlay to start with VRChat only.

I think I had it on steamvr in the past and it was working. Well either way it works with vrchat mode.
