### ISSUE TITLE
Feed does not seem to be getting new data all the time

### ISSUE THREAD

**Issue by DonovanPhoenix** [vrcx-team/VRCX#548]
I would assume that the feed would be getting data from the website. but it does not seem to get data from friends that I can see if I just missed them, the website says they were on an hour ago but the app logged them a day ago.

Version 2023.05.01

**Comment by slord399** [comment]
How many friends do you have?
and any log on Dev Tools?

**Comment by Natsumi-sama** [comment]
Might be fixed now.
