### ISSUE TITLE
[Feature Request] LogWatcher.cs: "[Behaviour] OnDisconnected:" and "Restart VRChat on Timeout"

### ISSUE THREAD

**Issue by GapVR** [vrcx-team/VRCX#557]
**Explain in detail what your suggested feature would be used for.**

Provide logging of [Behaviour] Disconnect events. In particular, "OnDisconnected: ClientTimeout" to allow VRCX to kill the VRChat process (and relaunch it, joining the last instance).

**Describe how it would look if it requires a UI.**

An additional option for "Restart VRChat on Timeout/Disconnect Prompt" below "Relaunch VRChat after crashing".

**Explain why people would want to use it.**

VRC now disconnects the user and awaits input on a timeout event instead of automatically rejoining the last instance.

**Comment by Natsumi-sama** [comment]
VRChat have claimed this is fixed.
