### ISSUE TITLE
[Bug] GitHub repository click URL incorrect

### ISSUE THREAD

**Issue by Chi-Yu** [vrcx-team/VRCX#564]
**Describe the bug**
The label is correct (`https://github.com/vrcx-team/VRCX`) but it actually points to `https://github.com/pvrcx-team/VRCX` when clicking it.

**To Reproduce**
1. Go to 'Settings'
2. Go to 'General' tab
3. Click on 'Repository URL'
4. See 'Page not found' error on GitHub

**Expected behavior**
Correct GitHub page opens in web browser

**Screenshots**
![grafik](https://github.com/vrcx-team/VRCX/assets/4586875/d00cb679-32ab-4f4c-b071-d614a534fa46)

**What version you are running**
2023.05.01

**Comment by Myrkie** [comment]
this has been fixed in latest Nightly builds aswell as a yet to be released build https://github.com/vrcx-team/VRCX/blob/f2c7275000aa6251a34188aa669cee09c3c9dba0/html/src/mixins/tabs/settings.pug#L52
