### ISSUE TITLE
[Feature Request] Ability to see all photos that contain a specific player

### ISSUE THREAD

**Issue by LunarstarPony** [vrcx-team/VRCX#565]
**Explain in detail what your suggested feature would be used for.**
So since VRCX can already include Metadata that contains all players that currently in the world, I wonder if it's possible to have a feature that allows user to search for a specific player and see all the photos that they might be around.
**Describe how it would look if it requires a UI.**
Pretty much just a search function but for photos tbh
**Explain why people would want to use it.**
Mostly just for if you want to revisit all the memories that might possibly contain the specific user

**Comment by TrixiDW** [comment]
Well, A wonderful idea, It's feasible to accomplish.

**Comment by LunarstarPony** [comment]
Yap I hope they can add it at some point!

**Comment by Natsumi-sama** [comment]
It would have to read every single photo this operation would be extremely slow.

**Comment by LunarstarPony** [comment]
I can see it being slow but at least it's still better than nothing xD

**Comment by GroovyTeacup** [comment]
> 

We'd actually only have to read the PNG header to get the necessary info; So it wouldn't be *that* slow. Idk how it would scale with tens/hundreds of photos without testing though.

I'd like to add something like this eventually but I have other priorities rn

**Comment by LunarstarPony** [comment]
Understandable, No worries.
