### ISSUE TITLE
[Feature Request] Sort by Name in player list

### ISSUE THREAD

**Issue by Wasmachineman-NL** [vrcx-team/VRCX#566]
I would like to block people who blocked me so that I can avoid lobbies with in them, but VRCX is missing a sort players by name option so I can't crossreference the ingame player list with the VRCX player list.

Really pisses me off.

**Comment by Myrkie** [comment]
as far as im aware vrchat doesn't publicly show that data to the user who gets blocked, that's only within Photon which is out of the scope for VRCX so doing that would be impossible

**Comment by Wasmachineman-NL** [comment]
That's not what I asked, what I am asking for is sort players by name so I can crossreference it with the ingame player list which hides people who have you blocked.

**Comment by Myrkie** [comment]
> That's not what I asked, what I am asking for is sort players by name so I can crossreference it with the ingame player list which hides people who have you blocked.



> as far as im aware vrchat doesn't publicly show that data to the user who gets blocked, that's only within Photon which is out of the scope for VRCX so doing that would be impossible, however sorting by display name can be added in the future.

__however sorting by display name can be added in the future.__
