### ISSUE TITLE
[Bug] VRCX Flagged by Microsoft Defender as Malware

### ISSUE THREAD

**Issue by MissingNO123** [vrcx-team/VRCX#568]
The latest Nightly build of VRCX is being flagged by Microsoft Defender as malware. I assume this has to do with recent changes to implement world persistence over a local IP, as the message given in MS Defender refer to "executing commands from an attacker" 

1. Install the latest Nightly build of VRCX (2023-06-07
2. Installation gets blocked by Windows 

**What version you are running**
2023-06-07T06.28-72ac87b

![image](https://github.com/vrcx-team/VRCX/assets/16027333/e2762898-25b3-4076-86f4-4c746b4ba3dc)

**Comment by Nekromateion** [comment]
I could not replicate this issue.
What operating system are you on? (Windows 10 or 11)
And which "Security intelligence version" is your Windows Defender on? (see image below)
![image](https://github.com/vrcx-team/VRCX/assets/43814053/fa05c3a0-50b5-4d66-9774-3c5e9113e3b9)

**Comment by MissingNO123** [comment]
I'm using Windows 10 22H2, and MS Defender is on Security Intelligence v1.391.723.0

![image](https://github.com/vrcx-team/VRCX/assets/16027333/c27a85ae-8f2d-40f3-92f8-2af2b7b1ba20)

**Comment by Toubsh** [comment]
My Microsoft Defender Antivirus detected it just now as well when I tried to update to the latest version, same message as stated in first post.

**Comment by jesterod** [comment]
Mine just popped up the same

**Comment by ElixGit** [comment]
So, I should trust that? I mean, I of course used VRCX before, it's awesome, but I'm aware of any trojans my anti-virus finds. xD
And like, the main issue is that the previous updates of VRCX didn't show as a Trojan.

**Comment by Myrkie** [comment]
Virus total scans for this version of the releases can be found over at.
[VRCX_20230615_Setup.exe Virus Total](https://www.virustotal.com/gui/file/fabbc2b238391bba6f00c3d25d6df0bab957d8201786924f158af7d38291e2c6/detection)
[VRCX_20230615.zip Virus Total](https://www.virustotal.com/gui/file/0e668e2dd6c2e8a40f7cec0adbd25ae2dc128af4302d436592765f5983219e9a)

As you can see the files themselves do not come up as a virus even through Microsoft, this is purely caused by the installer files being auto run from VRCX and being newly uploaded so they have not properly gone through the users to be anonymously uploaded via [automatic sample submission](https://learn.microsoft.com/en-us/microsoft-365/security/defender-endpoint/cloud-protection-microsoft-antivirus-sample-submission)

**Comment by Toubsh** [comment]
> > I trust that this version is safe, but it's bad practice to tell people to just "trust me bro" on every new release. If anyone ever gets unauthorized access to this repo and pushes malware, most users will just see it as another false positive and happily let it run.
> > I don't know if there's anything else you can do about this, but I do know that nearly all of the FOSS I use is unsigned, like VRCX, but they don't get these issues every update. For the security of your users, I reckon it'd be best to find some way around this.
> 
> the reason for VRCX triggering windows is because of the way VRCX updater works, automatically downloading an unsigned installer and running it on behalf of the user is a usual no no in the security world, we already submit all of our release files to security vendors, at this point its out of our control as we have to wait for security vendors to approve the files as safe and update their anti malware packages if our end users don't trust this they can always download the installer themselves and manually update or verify the packages are safe via another scan of the installer itself.
> 
> we are very much at the mercy of the anti virus vendors as submission of files can take up to 3 days to be verified by a human as safe and even longer to get added to an updated anti malware definitions package. this could be easily fixed by using a certificate to sign the code but as said above they are expensive and are not given out to FOSS developers.

Can I ask why it behaves like that all of a sudden? I have been using VRCX for quite some time (>1 year) now and never had this happen with the auto-updater, so something must have obviously changed, right?

**Comment by Myrkie** [comment]
> > > I trust that this version is safe, but it's bad practice to tell people to just "trust me bro" on every new release. If anyone ever gets unauthorized access to this repo and pushes malware, most users will just see it as another false positive and happily let it run.
> > > I don't know if there's anything else you can do about this, but I do know that nearly all of the FOSS I use is unsigned, like VRCX, but they don't get these issues every update. For the security of your users, I reckon it'd be best to find some way around this.
> > 
> > 
> > the reason for VRCX triggering windows is because of the way VRCX updater works, automatically downloading an unsigned installer and running it on behalf of the user is a usual no no in the security world, we already submit all of our release files to security vendors, at this point its out of our control as we have to wait for security vendors to approve the files as safe and update their anti malware packages if our end users don't trust this they can always download the installer themselves and manually update or verify the packages are safe via another scan of the installer itself.
> > we are very much at the mercy of the anti virus vendors as submission of files can take up to 3 days to be verified by a human as safe and even longer to get added to an updated anti malware definitions package. this could be easily fixed by using a certificate to sign the code but as said above they are expensive and are not given out to FOSS developers.
> 
> Can I ask why it behaves like that all of a sudden? I have been using VRCX for quite some time (>1 year) now and never had this happen with the auto-updater, so something must have obviously changed, right?

this isn't the first time its happened this is actually the third, and it  has to do a lot with the way malware detection's have changed, AI based anti malware detection's now exist in a lot of tools which suck and are usually wrong. it also depends on how new the release is files are verified through peers when you run software on a windows machine a anonymous sample (if enabled) is sent to Microsoft for detection and its determined then if its malware and this takes awhile. on-top of that microsoft has a limited amount of files you can submit for malware analysis manually vrcx is well over 1300 files and breaches that limitation.

**Comment by Toxic-Cookie** [comment]
Very strange issue indeed. First time I've run into this happening myself. Will be reverting to a previous version until this is resolved.

Security Intelligence Version:
![2023-06-15 04 23 37](https://github.com/vrcx-team/VRCX/assets/66691163/d5802f7c-a559-481e-bd5f-33c57c71abb4)

Quarantined Threat:
![2023-06-15 04 24 19](https://github.com/vrcx-team/VRCX/assets/66691163/1a6343e9-6f1f-4ec0-8765-57f30a9d0def)

The same threat attempting to be quarantined again I guess? And it failing since it's already been quarantined I presume? PROGRA~1 seems to be an abbreviation for backwards compatibility to the same directory.
![2023-06-15 04 24 34](https://github.com/vrcx-team/VRCX/assets/66691163/e581d5fa-931c-4fb5-a1ee-680516bb7df5)

**Comment by Myrkie** [comment]
> ![image](https://user-images.githubusercontent.com/109052138/246072517-69a043b4-d4f9-4ba7-be37-3bbf4a7a769d.png)
> 
> W11 Pro Sec version: 1.391.1506.0
> 
> It sees the VRCX as a Trojan:Script/Watatac.B!ml for the first time.



> Very strange issue indeed. First time I've run into this happening myself. Will be reverting to a previous version until this is resolved. Using Windows 10 Pro.
> 
> Security Intelligence Version: ![2023-06-15 04 23 37](https://user-images.githubusercontent.com/66691163/246094435-d5802f7c-a559-481e-bd5f-33c57c71abb4.png)
> 
> Quarantined Threat: ![2023-06-15 04 24 19](https://user-images.githubusercontent.com/66691163/246094440-1a6343e9-6f1f-4ec0-8765-57f30a9d0def.png)
> 
> The same threat attempting to be quarantined again I guess? And it failing since it's already been quarantined I presume? PROGRA~1 seems to be an abbreviation for backwards compatibility to the same directory. ![2023-06-15 04 24 34](https://user-images.githubusercontent.com/66691163/246094442-e581d5fa-931c-4fb5-a1ee-680516bb7df5.png)
> 
> EDIT: So I completely quarantined and removed the old version as well as manually uninstalled and erased VRCX from Program Files. I then downloaded the second most up to date zip, and exacted it to a folder named VRCX and pasted it into Program Files. I then launched it and disabled auto updating and ALT+F4'd since it had started already and upon relaunching it, it cancelled the update and works normally. Easy enough workaround for people skeptical about giving it an exception in Windows Defender. ![2023-06-15 04 49 22](https://user-images.githubusercontent.com/66691163/246099744-d5f9f322-74e9-45e5-ae33-ad9ba916c2d7.png)

as responded in the previous message by me, this is caused by VRCXs auto updater automatically downloading and running the unsigned installer that was created with NSIS, you can manually update VRCX by either using the zip file or running the installer manually, windows is just a bit unhappy that the VRCX process is auto starting a process as seen by the PID and thread id listed in the malware detection,
![image](https://github.com/vrcx-team/VRCX/assets/20288698/28bbe081-5948-4ddd-98bf-63447d7a464d)
PID is the process ID, all of vrcx files are safe as seen by my previous message and we are working with Microsoft to get this resolved, but Microsoft is not being cooperative. Until we receive cooperation from Microsoft recommended action is to disable the auto-updater to stop these false positives from being triggered, we know for a fact these are false positives but we don't recommend adding VRCX to your detection exclusion list as this is generally bad security practice.

**Comment by Toxic-Cookie** [comment]
> > ![image](https://user-images.githubusercontent.com/109052138/246072517-69a043b4-d4f9-4ba7-be37-3bbf4a7a769d.png)
> > W11 Pro Sec version: 1.391.1506.0
> > It sees the VRCX as a Trojan:Script/Watatac.B!ml for the first time.
> 
> > Very strange issue indeed. First time I've run into this happening myself. Will be reverting to a previous version until this is resolved. Using Windows 10 Pro.
> > Security Intelligence Version: ![2023-06-15 04 23 37](https://user-images.githubusercontent.com/66691163/246094435-d5802f7c-a559-481e-bd5f-33c57c71abb4.png)
> > Quarantined Threat: ![2023-06-15 04 24 19](https://user-images.githubusercontent.com/66691163/246094440-1a6343e9-6f1f-4ec0-8765-57f30a9d0def.png)
> > The same threat attempting to be quarantined again I guess? And it failing since it's already been quarantined I presume? PROGRA~1 seems to be an abbreviation for backwards compatibility to the same directory. ![2023-06-15 04 24 34](https://user-images.githubusercontent.com/66691163/246094442-e581d5fa-931c-4fb5-a1ee-680516bb7df5.png)
> > EDIT: So I completely quarantined and removed the old version as well as manually uninstalled and erased VRCX from Program Files. I then downloaded the second most up to date zip, and exacted it to a folder named VRCX and pasted it into Program Files. I then launched it and disabled auto updating and ALT+F4'd since it had started already and upon relaunching it, it cancelled the update and works normally. Easy enough workaround for people skeptical about giving it an exception in Windows Defender. ![2023-06-15 04 49 22](https://user-images.githubusercontent.com/66691163/246099744-d5f9f322-74e9-45e5-ae33-ad9ba916c2d7.png)
> 
> as responded in the previous message by me, this is caused by VRCXs auto updater automatically downloading and running the unsigned installer that was created with NSIS, you can manually update VRCX by either using the zip file or running the installer manually, windows is just a bit unhappy that the VRCX process is auto starting a process as seen by the PID and thread id listed in the malware detection, ![image](https://user-images.githubusercontent.com/20288698/246101066-28bbe081-5948-4ddd-98bf-63447d7a464d.png) PID is the process ID, all of vrcx files are safe as seen by my previous message and we are working with Microsoft to get this resolved, but Microsoft is not being cooperative. Until we receive cooperation from Microsoft recommended action is to disable the auto-updater to stop these false positives from being triggered, we know for a fact these are false positives but we don't recommend adding VRCX to your detection exclusion list as this is generally bad security practice.

Thank you! Good to know! And thank you for all your hard work on this amazing utility.
