### ISSUE TITLE
[Feature Request] Make a tab of group instances in the group popup

### ISSUE THREAD

**Issue by EsserGaming** [vrcx-team/VRCX#569]
Add/move a tab to see group instances through the group popup so people can see it through there.

![image](https://github.com/vrcx-team/VRCX/assets/36900138/891488aa-b1f3-4e04-bb39-6d050f562a68)
> Something like that.

Also when you click on the group instance on the sidebar there's no way to directly open the group instance.
(I am currently on the latest dev build with a custom theme)

**Comment by Natsumi-sama** [comment]
It's an issue with that theme try remove it, I'll upload a fixed version of this theme later.

**Comment by Myrkie** [comment]
isnt that the Material theme?

**Comment by EsserGaming** [comment]
> It's an issue with that theme try remove it, I'll upload a fixed version of this theme later.

Alright, thank you!
