### ISSUE TITLE
[Feature Request] Blacklist certain lobbies

### ISSUE THREAD

**Issue by Wasmachineman-NL** [vrcx-team/VRCX#571]
Long story short, I would like to block a certain lobby from showing up in VRCX since I am blocked from there due to a petty argument with it's owner.

Also a bug I will report shortly.

**Comment by Nekromateion** [comment]
Can you elaborate a bit on how blacklisting lobbies would work? Would it be blacklisting it by the InstanceID or by WorldID.
And by blocking it from showing up do you mean entirely prevent it from being displayed in your feed?

**Comment by Wasmachineman-NL** [comment]
> Can you elaborate a bit on how blacklisting lobbies would work? Would it be blacklisting it by the InstanceID or by WorldID. And by blocking it from showing up do you mean entirely prevent it from being displayed in your feed?

Blocking it from showing up in the instances list is what i'm thinking of:
https://i.imgur.com/RlLWfOs.png

**Comment by Myrkie** [comment]
> > Can you elaborate a bit on how blacklisting lobbies would work? Would it be blacklisting it by the InstanceID or by WorldID. And by blocking it from showing up do you mean entirely prevent it from being displayed in your feed?
> 
> Blocking it from showing up in the instances list is what i'm thinking of: https://i.imgur.com/RlLWfOs.png
> 
> Additionally, if it would be possible, stopping VRCX from joining said lobby randomly.

vrcx is limited this information is not exposed by the api only way to find out is to join and that would only stop joining for that one instance through self invite

**Comment by Wasmachineman-NL** [comment]
> > > Can you elaborate a bit on how blacklisting lobbies would work? Would it be blacklisting it by the InstanceID or by WorldID. And by blocking it from showing up do you mean entirely prevent it from being displayed in your feed?
> > 
> > 
> > Blocking it from showing up in the instances list is what i'm thinking of: https://i.imgur.com/RlLWfOs.png
> > Additionally, if it would be possible, stopping VRCX from joining said lobby randomly.
> 
> vrcx is limited this information is not exposed by the api only way to find out is to join and that would only stop joining for that one instance through self invite

I can live with that.

**Comment by Nekromateion** [comment]
> Additionally, if it would be possible, stopping VRCX from joining said lobby randomly.

VRCX cannot force you into instances.

**Comment by tgrafk12** [comment]
uh... and... you cant go to a different instance?
sounds like someone got upset over an argument.
i dont think there would be a reason to *blacklist* a certain public instance cause someone got mad at someone. that would be WAY too much power for every user on the platform. 
that would introduce internet trolls and bot accounts that could completely blacklist every instance in existence

**Comment by Nekromateion** [comment]
> uh... and... you cant go to a different instance? sounds like someone got upset over an argument. i dont think there would be a reason to _blacklist_ a certain public instance cause someone got mad at someone. that would be WAY too much power for every user on the platform. that would introduce internet trolls and bot accounts that could completely blacklist every instance in existence

I'm pretty sure they are talking about a local blacklist. All of the VRCX features are local.

**Comment by tgrafk12** [comment]
maybe do it locally!
but not like, a blacklist for every user that has VRCX. Thats way too much power.
*and just realizing now thats what they ment. 
i mean, whats the point in blacklisting an instance on VRCX when it still shows on VRC?
beciedes maybe like, poping up a notification saying this instance is blacklisted, are you sure you would like to travel?

**Comment by Myrkie** [comment]
> maybe do it locally! but not like, a blacklist for every user that has VRCX. Thats way too much power. *and just realizing now thats what they ment. i mean, whats the point in blacklisting an instance on VRCX when it still shows on VRC? beciedes maybe like, poping up a notification saying this instance is blacklisted, are you sure you would like to travel?

even if it was added it would be pointless since the vrchat api doesn't actually return instances you're banned from only the client says that through photon vrcx doesnt have access to the game networking.

**Comment by tgrafk12** [comment]
well, i dont think they mean banned from instances... 
if you leave an instance in general it will still show in your log that you were there.
on vrcx, if your *kicked*/*banned* from an instance, VRCX still shows it.
so a user could manually blacklist instance and have a notification saying *Instance Blacklisted* or something along the lines of that

**Comment by Natsumi-sama** [comment]
This is very much a VRC issue and not a VRCX issue.

**Comment by tgrafk12** [comment]
^agreed

**Comment by Myrkie** [comment]
> well, i dont think they mean banned from instances... if you leave an instance in general it will still show in your log that you were there. on vrcx, if your _kicked_/_banned_ from an instance, VRCX still shows it. so a user could manually blacklist instance and have a notification saying _Instance Blacklisted_ or something along the lines of that

timeout timers for instances your kicked from may become a feature later on when vrchat adds more logging to the game output log, which vrchat said they will do in the latest devlog, but the rest of this thread is issues caused by vrchat, thus not a vrcx issue

**Comment by Wasmachineman-NL** [comment]
> This is very much a VRC issue and not a VRCX issue.

How is asking me wanting to (locally, mind you) block certain lobbies in VRCX a VRChat issue?

**Comment by Natsumi-sama** [comment]
VRChat shouldn't be sending you instances you can't join.

**Comment by Wasmachineman-NL** [comment]
> VRChat shouldn't be sending you instances you can't join.

Already beat you to it: https://feedback.vrchat.com/bug-reports/p/blocked-lobby-causes-softlock

**Comment by Natsumi-sama** [comment]
This instance blacklist feature does not seem like something that would make a lot of sense.
I don't see any *real* benefit to the end user from this feature.
