### ISSUE TITLE
[Bug] Self-Invites not working anymore

### ISSUE THREAD

**Issue by InfoBlock** [vrcx-team/VRCX#573]
**Describe the bug**
I'm trying to send myself self invites using my modified VRCX but when I click on any lobby and try to self-invite myself I'm not getting any notifications on VRChat, I have tried restarting VRChat but still the same issue

**To Reproduce**
1. Open VRChat and join any loby
2. Head to VRCX
3. Look for a new Lobby
4. Invite yourself into the new Lobby using VRCX

**Expected behavior**
I should get an invite in-game which I don't get

**Screenshots**
https://streamable.com/q1647l

**What version you are running**
2023.05.01

**Comment by slord399** [comment]
As you said own modified VRCX,
could you try with latest release and nightly release?

also there is VRChat update happen recently so update client as well.

**Comment by Myrkie** [comment]
can confirm that self invites are working as expected in VRCX with latest release of vrchat and vrcx nightly.

**Comment by Myrkie** [comment]
> can confirm that self invites are working as expected in VRCX with latest release of vrchat and vrcx nightly.

its a little slow but that probably has to do with cloud-flares recent outage / current maintenance 

[VRChat_qNvoX9qeZS.webm](https://github.com/vrcx-team/VRCX/assets/20288698/1304a1f3-c112-40a8-8675-a7de9ee2a864)

**Comment by InfoBlock** [comment]
> > can confirm that self invites are working as expected in VRCX with latest release of vrchat and vrcx nightly.
> 
> its a little slow but that probably has to do with cloud-flares recent outage / current maintenance
> 
>  VRChat_qNvoX9qeZS.webm

I'm not getting any invites at all eften after hours

**Comment by InfoBlock** [comment]
> > > > can confirm that self invites are working as expected in VRCX with latest release of vrchat and vrcx nightly.
> > > 
> > > 
> > > its a little slow but that probably has to do with cloud-flares recent outage / current maintenance
> > > VRChat_qNvoX9qeZS.webm
> > 
> > 
> > I'm not getting any invites at all eften after hours
> 
> try using latest nightly build and see if you have any changes as its working on my end.

What nightly build? I have even tried with the original VRCX now, same issue

**Comment by Natsumi-sama** [comment]
Try using the VRC website, but to me it sounds like classic game web socket disconnecting.

**Comment by Myrkie** [comment]
nightly build is the beta build for vrcx testing features, you can access it from settings > VRCX Updater > Change Build > Nightly 2023-06-08

![image](https://github.com/vrcx-team/VRCX/assets/20288698/158776bb-d46b-4c42-9b46-65e0816582a2)

**Comment by InfoBlock** [comment]
> Try using the VRC website, but to me it sounds like classic game web socket disconnecting.

Same issue on VRC Website, I have restarted VRChat twice and I'm not even getting invites from the VRC Website

**Comment by Natsumi-sama** [comment]
Try disable IPv6

**Comment by Myrkie** [comment]
> > Try using the VRC website, but to me it sounds like classic game web socket disconnecting.
> 
> Same issue on VRC Website, I have restarted VRChat twice and I'm not even getting invites from the VRC Website

then this is a VRChat issue not VRCX try disabling IPV6 in your router settings, that's known to cause issues with vrchat's websocket

**Comment by InfoBlock** [comment]
Do I restart my PC or smth after disablind IPv6? I disabled it in my Network Settings on my PC now, everything worked fine before I updated VRChat to their latest update

**Comment by Natsumi-sama** [comment]
no a restart isn't required

**Comment by Myrkie** [comment]
> Do I restart my PC or smth after disablind IPv6? I disabled it in my Network Settings on my PC now, everything worked fine before I updated VRChat to their latest update

if it doesn't work then that's a VRChat service issue, you're best off contacting vrchat for support.

**Comment by slord399** [comment]
If you cannot disable IPv6 for reason, you can run "netsh interface ipv6 set prefixpolicy ::ffff:0:0/96 100 4" on elevated command prompt. (make use IPv4 than IPv6)

**Comment by slord399** [comment]
Also try restart router anyway, it can glitched often.

**Comment by InfoBlock** [comment]
Would restarting VRChat work out aswell? I'm not the only one connected to the router, my parents would be pissed if I restarted it now

**Comment by InfoBlock** [comment]
I don't have access to my router settings since we have a new router

**Comment by Myrkie** [comment]
if its an issue related to the router then no

**Comment by InfoBlock** [comment]
> if its an issue related to the router then no

Seems to be an VRChat issue, as I said it worked just fine before I updated VRChat to their latest release (2023.2.3)

**Comment by slord399** [comment]
Are you trying to invite me to legacy instance?
(if it is, maybe that's could be issue often. just possibility.)

**Comment by Myrkie** [comment]
> > if its an issue related to the router then no
> 
> Seems to be an VRChat issue, as I said it worked just fine before I updated VRChat to their latest release (2023.2.3)

in that case its not our problem and you're asking for help in the wrong place, best to contact VRChat over email or via the discord server.

**Comment by InfoBlock** [comment]
Sorry for wasting your time, looks like it's indeed an VRChat issue, gotta get in contact with them as y'all said, thank you for the help anyways!
