### ISSUE TITLE
[Feature Request] Filter out avatars you already know cant be used

### ISSUE THREAD

**Issue by Ishikiopy** [vrcx-team/VRCX#574]
Add a toggle option into the settings at the advanced / Remove Avatar Database, with the title "Filter Privated / Deleted Avatars".

Now you gonna make a function that will test every single avatar that the program found if it can or cant be used since your program is capable of that already.

Currently by clicking on a avatar search option VRCX then will announce the avatar to be deleted or private if the avatar cannot be used / displayed this makes this whole interaction entirely useless and a waste of time, you could automate this behavior just to pre filter the results to only show viable results.

**Comment by ScruffyRules** [comment]
This will cause API spam and likely get you temp banned from VRC :>

**Comment by Ishikiopy** [comment]
REEEEEEEEEEEEEEEEEEEEEEEEEEEE

**Comment by Myrkie** [comment]
> Add a toggle option into the settings at the advanced / Remove Avatar Database, with the title "Filter Privated / Deleted Avatars".
> 
> Now you gonna make a function that will test every single avatar that the program found if it can or cant be used since your program is capable of that already.
> 
> Currently by clicking on a avatar search option VRCX then will announce the avatar to be deleted or private if the avatar cannot be used / displayed this makes this whole interaction entirely useless and a waste of time, you could automate this behavior just to pre filter the results to only show viable results.

if your using the offical avatar database VRCX supports avtr.just-h.party it automatically filters these out but it does take time to conform to vrchat's api rate limiting
