### ISSUE TITLE
[Bug]  Groups

### ISSUE THREAD

**Issue by AvocadoVR** [vrcx-team/VRCX#576]
**Describe the bug**
It only shows a few groups in the tab. It randomly changes.

**Expected behavior**
I expect it show all the groups.

**Screenshots**
![image](https://github.com/vrcx-team/VRCX/assets/135179467/3b60b4aa-621a-44a7-96e5-4823373c86e7)
![image](https://github.com/vrcx-team/VRCX/assets/135179467/bf9ca2be-2653-4bd5-9b48-6a0bcf98ca30)

**What version you are running**
Version: Latest

**Comment by GroovyTeacup** [comment]
Those are group instances.

**Comment by AvocadoVR** [comment]
It was never clarified. It just says groups.

**Comment by Myrkie** [comment]
> It was never clarified. It just says groups.

that tab appears in the player list where you see online players, thus its a list of all online friends in group instances.
