### ISSUE TITLE
[Feature Request] Button to enable `Avatar Scaling` on all own words.

### ISSUE THREAD

**Issue by DauwJonas** [vrcx-team/VRCX#583]
Instead of manually going on the website enabling it for each world separately, a 1 click solution.

## **Explain in detail what your suggested feature would be used for.**
A button that changes the new world setting `Avatar Scaling` from the default `off` to `on`.

## **Describe how it would look if it requires a UI.**
In `User panel (you)/worlds` next to the sorts, add a settings button that opens a new window for mass/batch editing. In that menu I would place the button.

_While you are at it maybe at a batch toggle for making worlds private & so._

## **Explain why people would want to use it.**
So they don't have to do it for every world 1 by 1.

**Comment by Myrkie** [comment]
seems a bit out of scope for vrcx, an a very niche feature. maybe at best adding an individual option to change world scaling settings as its just adding a tag to your world `feature_avatar_scaling`

**Comment by DauwJonas** [comment]
But what about people with lots of worlds? Let's say they have a 100, changing it individually for every world is a lot of effort.
I just suspect that VRC is gonna add more & more features that are off by default, so the VRCX batch features is preparing for the future.
+ Being able to private all world & avatars with a few clicks seems not very niche to me. These are options that YT, Twitter, & alike have.

**Comment by Myrkie** [comment]
tag additions already exist and soon adding of the avatar scaling specifically will be added, so I don't see batch features being added anytime soon, that's more of a feature vrchat should be adding themselves to the sdk and world tools.

**Comment by DauwJonas** [comment]
Indeed, there are many features VRC should add.
