### ISSUE TITLE
[Feature Request] Local Friend and Avatar Favorites

### ISSUE THREAD

**Issue by C0D3-M4513R** [vrcx-team/VRCX#584]
**Explain in detail what your suggested feature would be used for.**
So I'm fairly new to VRC, and have noticed the limitation of only 3 Friend Favorites.
I'd like a Feature in VRCX, where you could add local Friend Favorite Lists and Avatar Favorite Lists.

**Describe how it would look if it requires a UI.**

The UI would look similar to the existing local World Lists.

**Explain why people would want to use it.**

If you want to actually group your friends by meaningful Groups, you need more than 3 Groups.
Even if it is only locally.

**Comment by Natsumi-sama** [comment]
Local friend favorites would take a massive amount of work to add and is why it hasn't been added already.
Local avatar favorites used to be a thing but had to be removed after VRC+.

**Comment by Natsumi-sama** [comment]
You'd be 100% correct, I can only dream it'll get put out of it's misery one day although after all I am half to blame for this monstrosity of a monolith, I can't imagine it'll be maintained after I'm done I would rewrite it but it's too far gone at this point.

**Comment by Natsumi-sama** [comment]
Already many issues for this so I'll close this one

**Comment by Natsumi-sama** [comment]
Easier said than done this program is a lot bigger than you'd think.
