### ISSUE TITLE
[Bug] Latest Nightly build flagging windows defender with Wacatac.B1ml

### ISSUE THREAD

**Issue by McguyverZero** [vrcx-team/VRCX#586]
**Describe the bug**
Yesterday's nightly build is running fine. I turned on my pc with the auto update on and it flagged some viruses and removed them. Sometime after I noticed that VRCX wasn't running and the .exe was removed. So I reinstalled a stable, as soon as I switched to the latest nightly build (2023-06-24T14.32-ef6b21b) it would flag up again in Windows Defender with the "Wacatac.B1ml" trojan. I reinstalled again and switched to yesterday's nightly build (2023-06-23T09.27-e5a448d) and it's fine.

![ApplicationFrameHost_gICtkboF5s](https://github.com/vrcx-team/VRCX/assets/137654867/16820c10-456b-41d8-b6c9-990db3bb4210)

![ApplicationFrameHost_KbAVW4veTi](https://github.com/vrcx-team/VRCX/assets/137654867/fcf36ff9-738e-4bd6-a5ad-759643d0bd7b)

**Comment by Myrkie** [comment]
see https://github.com/vrcx-team/VRCX/issues/568 this is a false positive blame microsoft

**Comment by Myrkie** [comment]
can you tell me which version of the nightly was having issues from the settings > version so I can go about contacting Microsoft again for a whitelist 

![image](https://github.com/vrcx-team/VRCX/assets/20288698/0160e332-bfd6-4180-b061-416fe8ddce08)

**Comment by McguyverZero** [comment]
> see #568 this is a false positive blame Microsoft

Ahh okay I searched "VRCX Wacatac" on google and it only came back with something from 2 years ago so was unsure.


> can you tell me which version of the nightly was having issues from the settings > version so I can go about contacting Microsoft again for a whitelist
> 
> ![image](https://user-images.githubusercontent.com/20288698/248514136-0160e332-bfd6-4180-b061-416fe8ddce08.png)

![VRCX_mCHXGvGMw7](https://github.com/vrcx-team/VRCX/assets/137654867/efdc22cd-ea7f-4725-92f9-ff4fb047a1a3)

The build listed in blue at the top is the one that is being removed upon installation I checked the listed post and they mentioned the Security Intelligence Version so posting my current just incase

![ApplicationFrameHost_3zCtO3HpF0](https://github.com/vrcx-team/VRCX/assets/137654867/9840437e-a995-4e20-840c-607a0103dc85)

**Comment by Myrkie** [comment]
thanks for the information, ill be going through with Microsoft **again** to get a whitelist for this issue with latest nightly.

**Comment by Myrkie** [comment]
Hello everyone, for any future detections please provide a `MPSupportFiles.cab` file this can be generated by running the following commands in an elevated command prompt or windows terminal

`cd "%programfiles%\windows defender"`
`mpcmdrun.exe -GetFiles`

after the file has been created windows will provide a directory for the log file, for example 
`Files successfully created in C:\ProgramData\Microsoft\Windows Defender\Support\MpSupportFiles.cab`
Please provide this file if you receive any more detection's as this will be required to continue our investigation with Microsoft.
