### ISSUE TITLE
VRChat API Change Notification - Header Changes

### ISSUE THREAD

**Issue by dtupper** [vrcx-team/VRCX#587]
Hello!

VRChat's API will be making a change soon. We'll be adding the `SameSite=Lax` attribute to our auth cookies. This is part of an effort to improve our CSRF protection. 

Browsers for the most part already treat all cookies this way, but a handful don't. We don't expect this to affect many VRChat-related applications, but we wanted to let you know anyhow.

Additionally, we're going to start filtering requests based on the `Origin` and `Referer` headers. Leave those headers empty to avoid being impacted by this change.

Thank you!

---

This text was also posted [here](https://github.com/vrchatapi/specification/issues/248).

**Comment by Myrkie** [comment]
thanks, has been noted this change will probably be added into nightly and pushed to release when required.
