### ISSUE TITLE
[Bug] 

### ISSUE THREAD

**Issue by Cyc-Systems** [vrcx-team/VRCX#589]
**Describe the bug**
the latest updates .exe is seen as a Virus by my WIndows Defender >.<

**To Reproduce**
just trying to install/unpack the new patch

**Screenshots**
![image](https://github.com/vrcx-team/VRCX/assets/130109574/c3a0faad-9acd-4d62-8b25-1ec6e21354e0)

**Comment by Natsumi-sama** [comment]
https://github.com/vrcx-team/VRCX/issues/586
