### ISSUE TITLE
[Feature Request] Log Vote kicks

### ISSUE THREAD

**Issue by AshtonSparx** [vrcx-team/VRCX#594]
**Explain in detail what your suggested feature would be used for.**

I would like vote kicks to be logged somewhere, most likely Game Log with it's own filter. If you're a group moderator, it also tells you who initiated the vote kick. This could be useful for group moderation if the prompt vanished while you were AFK.

**Describe how it would look if it requires a UI.**

It would just appear the same as everything else in Game Log. Time, Type VoteKick, icon can be a boot icon, no User, Detail would be who the kick was initiated on and if the information is accessible, who started the kick

**Explain why people would want to use it.**

Would be really useful for logging moderation stuffs for group instances and others. Could even show (if accessible) if you denied or voted against the person.

**Comment by Natsumi-sama** [comment]
This can be added once VRChat add proper logging for vote kick information to the output log file, currently they only provide information when you accept or decline the vote kick notification which isn't useful.
