### ISSUE TITLE
[Feature Request] Would like to be able to log merge events

### ISSUE THREAD

**Issue by ncswwxb74** [vrcx-team/VRCX#600]
# My native language is Chinese, and this is the result of translation：
## Would like to be able to log merge events
If a friend is logged into vrchat with a steam account ( visitor account ) , and later merges the visitor account with the vrchat account, there will be an unfriend event and a friend event in my friend log, both at the same time. After a friend's account is merged, the friend's "Frend No.x" will change to the No.x of the newest friend.
If merge events can be recognized and logged, the friend log will become more intuitive.

# This is the original Chinese version 这是中文原文：
## 希望能够实现merge事件的记录
如果有一名好友使用steam账户登录vrchat（visitor账户），后来他将visitor账户与vrchat账户进行了合并，在我的好友日志中就会留下一条unfriend事件和一条friend事件，并且这两条事件都在同一时刻。在好友的账号合并以后，该好友的的“Frend No.x”信息将会变为最新添加好友的No.x 。
如果能够识别merge事件并记录，好友日志将会变得更加直观。

**Comment by Natsumi-sama** [comment]
Because the users username and userId changes when a account is merged VRCX can't 100% accurately know when an account has been merged.
