### ISSUE TITLE
[Feature Request] See friends location in group instance

### ISSUE THREAD

**Issue by blackorbit1** [vrcx-team/VRCX#609]
**Explain in detail what your suggested feature would be used for.**
Currently, when a friend is in a group instance that we can access, it is marked as in private instance with no further information.
In vrchat for instance, those friends locations are displayed like any public or friend+ instance if I recall.

**Describe how it would look if it requires a UI.**
Same as public or friend+.

**Explain why people would want to use it.**
Same as public or friend+.

**Comment by blackorbit1** [comment]
I think so, I downloaded / installed it for the first time yesterday.


It looks like I can see friends location on some modals when I'm already in the group instance :
![image](https://github.com/vrcx-team/VRCX/assets/38140797/45931913-08c5-4156-a5ba-bb6115a9fc2a)

But not when I'm disconnected : 
![Capture d’écran 2023-07-27 0407322](https://github.com/vrcx-team/VRCX/assets/38140797/6bbec409-a411-4852-bcbf-9193a2d259ca)

**Comment by Natsumi-sama** [comment]
User is in "Ask Me" status this will hide their location unless they are in the instance with you.
