### ISSUE TITLE
vrcx stuck on white screen[Bug] 

### ISSUE THREAD

**Issue by Mintboi88** [vrcx-team/VRCX#611]
**Describe the bug**
vrcx stuck on white screen.

**To Reproduce**
1. open vrcx

**Expected behavior**
the app to run.

**What version you are running**
Version VRCX 2023.06.30

![image](https://github.com/vrcx-team/VRCX/assets/69445294/22e4e85f-4086-4210-b24b-783d21009dda)

**Comment by Mintboi88** [comment]
I have tried reinstalling the app multiple times and also the nightly fork

**Comment by BLANKE1** [comment]
Did you already try the steps within the [Wiki](https://github.com/vrcx-team/VRCX/wiki#vrcx-opens-to-a-white-screen)

**Comment by Mintboi88** [comment]
deleting vrcx.sqlite3 Fixed it thanks
