### ISSUE TITLE
Self invite button does not work half the time

### ISSUE THREAD

**Issue by lexvi** [vrcx-team/VRCX#615]
I have replaced Vrchat menu usage with VRCX completelly to Self invite myself to instances i want to join

Used to be super easy, now however the quick action self invite button does not appear to work all the time, causing to go trough more menuing or in worst cases have to use Vrchats own wolrd or friends list to join on friends.

When the button does not work it does not give the self invite text hovering over it.

Request this to be fixed soon

**Comment by Myrkie** [comment]
self invite was broken by a recent change, update to VRCX nightly and try again.

**Comment by lexvi** [comment]
That seemed to help ty.
