### ISSUE TITLE
[Bug] Sort by status and private to bottom do not play nicely together

### ISSUE THREAD

**Issue by TapGhoul** [vrcx-team/VRCX#617]
**Describe the bug**
When enabling both "Sort Private to bottom" and "Sort by status", the status sort only applies to private users - status is not sorted for people in visible instances

**To Reproduce**
1. Go to Settings -> Appearance -> Side Panel
2. Enable "Sort Private to Bottom" and "Sort by status" only
4. See that when toggling "Sort by status", only those in private instances actually get sorted

**Expected behavior**
First sorted private to bottom, and then within each a sub-sort of by status (blue, green, orange, red - though here only blue/green applies)

Note, those who are private are correctly sorted, it's only publics that are not sorted.

**Screenshots**
I'd rather not share my friends list, but this is easily seen with a decently large friends list.

**What version you are running**
2023.07.30

**Comment by Natsumi-sama** [comment]
That was the intended behavior when I made it I don't remember why anymore but there was a good reason for it.

**Comment by Silvea12** [comment]
I'm curious what that was, because it doesn't make a lot of sense to me at first blush.

**Comment by Natsumi-sama** [comment]
Ah it was for "Sort GPS to top" to work with "Sort by status"

**Comment by Silvea12** [comment]
I've never seen sort GPS to top work, weirdly, even on its own. But I may just misunderstand what it does.

**Comment by Natsumi-sama** [comment]
You need to sorting set to "online for" for it to work, it sorts most recent instance changes to top/largest instance timer to bottom.
