### ISSUE TITLE
[Feature Request] Sort by instance ID for visible instances

### ISSUE THREAD

**Issue by Silvea12** [vrcx-team/VRCX#618]
**Explain in detail what your suggested feature would be used for.**
A sort feature that groups friends who are in the same instance together. Potential sort order could be instance ID, then friend name.
Combining with things like sort by status, could sort by instance ID, then status, then friend name.

**Describe how it would look if it requires a UI.**
Simply a reordering of friends

**Explain why people would want to use it.**
Makes it easier to see when a bunch of friends are in the same instance directly from the sidebar (and is simpler to implement than grouping, as it's just a sort)

**Comment by Natsumi-sama** [comment]
Dupe issue
