### ISSUE TITLE
[Bug] Discord names no longer detected

### ISSUE THREAD

**Issue by Chi-Yu** [vrcx-team/VRCX#620]
**Describe the bug**

Discord names no longer contain the `#` symbol.

Therefore, the regular expression used to find them no longer matches.

**To Reproduce**

* Click "Load missing entries" in the friends list
* Open "Discord Names" dialog on "Profile" page
* Note that discord names following the new format are not listed

**Expected behavior**

* Names matching the new format (`[a-zA-Z0-9\._]+`, [source](https://support.discord.com/hc/en-us/articles/12620128861463-New-Usernames-Display-Names#docs-internal-guid-28d8eed3-7fff-7f1c-a2e6-21318f925157)) are recognized as discord names
* Optionally: Names matching the old format are no longer recognized (as they will become invalid soon)

**What version you are running**
2023.07.30

**Comment by ZettaiVR** [comment]
![image](https://github.com/vrcx-team/VRCX/assets/40919119/636f7d3a-b7eb-4515-aa6d-91add3d1d011)

**Comment by Chi-Yu** [comment]
I was describing the character set allowed in discord names, (obviously) not the full match pattern.

That's up to the developer to figure out.

**Comment by regalialong** [comment]
> That's up to the developer to figure out.

How do you expect the developers to detect Discord usernames? Since discriminators aren't common anymore, there's little patterns to reliably match to.

**Comment by ZettaiVR** [comment]
Ever since the change of discord username rules it's literally impossible to distinguish them from normal text. That's what the screenshot shows you: *every single word* in your original post could be a discord username.

**Comment by Chi-Yu** [comment]
The current implementation already matches against the prefix "discord:" (case insensitive I suppose) and it would simply be a matter of following that up with (optional) white space and the pattern I included in my report, then stop at the next white space.

You could also require that to be on a single line on it's own, if that's too difficult.

There are multiple options to do this, but dismissing a bug report right away because you can't immediately come up with a perfect solution doesn't seem to be a good way to go about it.

I'm a user, not a maintainer. It's not really my duty to come up with a perfect solution. Is it?

**Comment by Myrkie** [comment]
at most a match could be made for detecting the present of discord: username, in the bio but other than that its not really possible with discrims being removed

**Comment by WashierPlayz** [comment]
Actually, the new Discord format doesn't have any capitals, no unicode characters, and no spaces, so if you manage to have a bunch of mashed up words without capitalization , f.e "xxtentacionxx" or "thegaylord" all those could be Discord names, just needs a dictionary implementation to estimate discord names

**Comment by Myrkie** [comment]
> Actually, the new Discord format doesn't have any capitals, no unicode characters, and no spaces, so if you manage to have a bunch of mashed up words without capitalization , f.e "xxtentacionxx" or "thegaylord" all those could be Discord names, just needs a dictionary implementation to estimate discord names

even then that cannot be detected automatically, capitalization or not it will still be regex matched to random words as seen by [Zettai](https://github.com/ZettaiVR) example above, if you have an idea on how to do it you can PR it.

**Comment by Natsumi-sama** [comment]
Current solution should be good enough https://github.com/vrcx-team/VRCX/blob/master/html/src/app.js#L21754C24-L21754C24
