### ISSUE TITLE
[Bug] Player list not updating number of users in instance

### ISSUE THREAD

**Issue by JanieUwU** [vrcx-team/VRCX#624]
**Describe the bug**
Player list does not update the number of users in the instance. The user list itself does update with the correct users in the world. Just the number counter at the top does not. I use that to quickly check the number of users in the world for moderation purposes.

**To Reproduce**
Go to player list tab, look at the number of users in the instance at the top after the instance name and world name.
Notice that it does not change when users join or leave. The number does not update.

**Expected behavior**
The total users in instance updates as players leave or join the instance.

**Screenshots**
https://media.discordapp.net/attachments/1136852223368900690/1139494239177293905/image.png?width=949&height=445

**What version you are running**
Version 2023.07.30

**Comment by LucHeart** [comment]
@Natsumi-sama this is resolved with future release i think?

**Comment by Natsumi-sama** [comment]
on nightly build yes
