### ISSUE TITLE
[Bug] Theme Issue

### ISSUE THREAD

**Issue by AvocadoVR** [vrcx-team/VRCX#625]
**Describe the bug**
I use the [Material 3](https://github.com/kamiya10/VRCX-theme/tree/main/m3) theme. It seems the area that highlights the icon in this theme dosen't get adjusted in the theme instead it is in the default spot.

![image](https://github.com/vrcx-team/VRCX/assets/135179467/2e1a2c0d-0160-4929-850e-3c27e16c7518)

**What version you are running**
Latest Version

**Comment by Myrkie** [comment]
change to nightly build

**Comment by Natsumi-sama** [comment]
The theme is now baked into VRCX if you have it installed as a `custom.css` remove that file.
