### ISSUE TITLE
[Feature Request] SQLite Database Location in vrcx.json

### ISSUE THREAD

**Issue by dark-swordsman** [vrcx-team/VRCX#633]
**Explain in detail what your suggested feature would be used for.**
This feature would be used to put the SQLite database on another drive or folder.

**Describe how it would look if it requires a UI.**
Either by the "SQLite Table Size" menu area under advanced or some other, a folder path and button to select a folder to change the location of the SQLite database.

**Explain why people would want to use it.**
This is useful for people who want to store their data (world favorites, avatar favorites, etc.) separately from their host operating system.

While I could have checked and backed it up, I have twice now reformatted my OS and forgotten to migrate my existing VRCX database to the new install, thus losing all my data when formatting.

It would be nice to have it set on another drive so I can just reinstall, relink the DB, and then continue using VRCX like normal.

**Comment by Natsumi-sama** [comment]
You can change the database location with a launch parameter, it can't be changed in settings because settings are stored in the database.
https://github.com/vrcx-team/VRCX/wiki/Launch-parameters#vrcx-launch-parameters

**Comment by dark-swordsman** [comment]
Does this work on auto-start with Windows?

**Comment by Myrkie** [comment]
if you create a shortcut in the windows startup folder `shell:startup` with the argument added it should

**Comment by Myrkie** [comment]
you would have to disable `start as windows startup` and use said shortcut above 

![image](https://github.com/vrcx-team/VRCX/assets/20288698/8aa06f35-ece1-48c9-9d2c-83cc722e90f2)

**Comment by dark-swordsman** [comment]
Though I assume this removes its ability to start minimized in the tray?

**Comment by Myrkie** [comment]
> Though I assume this removes its ability to start minimized in the tray?

think so yes

**Comment by dark-swordsman** [comment]
When I do that, I get this error.
![image](https://github.com/vrcx-team/VRCX/assets/7909209/787e221c-3b36-48ed-8409-af30443e0022)

**Comment by Myrkie** [comment]
did you copy over the database to the new location?

**Comment by Myrkie** [comment]
the old database is located at `%appdata%\..\Roaming\VRCX`

**Comment by dark-swordsman** [comment]
Sorry, it was that I didn't specify `VRCX.sqlite3` at the end of the directory. Now that it's written specifically, it works.

**Comment by dark-swordsman** [comment]
I was curious if we can re-open this issue, or I guess ask if I should make a new one.

It would be nice if the SQLite DB can be defined in-app. The startup folder method is proving to be unreliable, particularly if VRCX restarts or if I need to restart the program. It would be much more reliable if I could define it in-app.

**Comment by Myrkie** [comment]
the flag is done like this on purpose, because the settings for the application are stored in the database, vrcx cant access the database to find its own location so the flag is required

**Comment by dark-swordsman** [comment]
Thank you for re-opening it. I was going to say: Why can't we just define it in a config file stored alongside the application?

I apparently had restarted VRCX today and it opened with the old database, so I just saved a ton of data into the wrong DB. 

I am also unable to install a new version apparently, because the current shortcut with the DB flag points to an old version.

Needless to say, this is desperately needed.

**Comment by dark-swordsman** [comment]
Just wanted to add, incase anyone else comes to this problem related to the DB:

I was avoiding updating VRCX because doing the in-app update would cause it to re-open without the database. Then when I re-opened manually, it would open to the previous version.

Manually downloading the installer and running again, it will see the old version and overwrite, and it ends up working correctly.
