### ISSUE TITLE
[Bug] Boot option --affinity=<ARG> settings can not be load correct.

### ISSUE THREAD

**Issue by embracech** [vrcx-team/VRCX#634]
Failed to set affinity args with VRCX boot option, but Its effective with steam starting option boot args and shortcut options

**Comment by Myrkie** [comment]
VRCX doesn't have a argument for setting processor affinity, by default a program has to add this support or it has to be changed by a administrator level application such as the task manager or windows powershell's `Get-Process` object Cefsharp doesn't seem to have a default one either

**Comment by Myrkie** [comment]
I am unable to reproduce this issue.

**Comment by Natsumi-sama** [comment]
If "VRChat Path Override" is set VRCX will launch VRChat via the exe, but if it isn't set it will launch it through Steam instead. Try setting/removing a "VRChat Path Override" to see if that helps.

**Comment by embracech** [comment]
but actually thats not point in case I didnt set "VRChat Path Override" at early time through I can't set CPU thread association either. is that any option such as I'm launching VRCX at admin can solve this?Nope, I still cannot launch VRChat with "--affinity" option correctly
![image](https://github.com/vrcx-team/VRCX/assets/19525722/c731cfcc-026d-4cc3-a9e4-fff7853612fc)
![image](https://github.com/vrcx-team/VRCX/assets/19525722/f566371f-462b-47b1-8a96-3e8fb8a72aa7)
