### ISSUE TITLE
[Feature Request] Instance Player List fetch info without manual clicking option

### ISSUE THREAD

**Issue by mossarelli** [vrcx-team/VRCX#636]
**Explain in detail what your suggested feature would be used for.**
Instead of manually clicking each player in the player list, VRCX fetches the avatar, platform, status, rank, languages, bio links automatically.

**Describe how it would look if it requires a UI.**
It would require a check mark type UI box in the instance tab called "Auto fetch player info", or in the settings tab as an option to be toggled. In the Instance player list there could be a new column called "Viewed" or "Checked" where all the manual fetches can be sorted in the list from top to bottom (just like Timer, Display Name and Rank), so that a user can see if they've checked a profile bio manually.

**Explain why people would want to use it.**
Why should a user have to manually click on every person that joins an instance, when VRCX is already capable of doing so automatically? I'm in game and in VR, I don't want to use my mouse and keyboard while wearing a headset unless really necessary. I sort the column "Timer" with newest at the top and oldest at the bottom, I have to click on each new person that joins the instance every 5 to 10 seconds which takes me away from the VR and I have to either use an overlay or take off my headset to see the second monitor with VRCX running.

A friend of mine is hosting a talent show every weekend, their group needs to be very aware of visitors and new users joining their instance as they sometimes run crashers or just want to be nuisances, it would be a great addition to VRCX if they could see the user rank as soon as they join the instance, as the in game player list in VRC also do not show their rank unless you manually tap on their name.

**Comment by Myrkie** [comment]
VRCX reads the output log of your game, the output log only shows the Username of a USR_ID linking to the user, when you click on a user in gamelog vrcx just does that search for you, requesting the USR_ID of every user could result in excessive api requests and bans.

**Comment by mossarelli** [comment]
> VRCX reads the output log of your game, the output log only shows the Username and doesn't provide the USR_ID linking to the user, when you click on a user in gamelog VRCX just does that search for you, requesting the USR_ID of every user could result in excessive api requests and bans.

What if there's a 5-10 second random delay between profile fetches to emulate a natural user's input?

I can click all the profiles in the list manually in less than 3 second per profile, so that just needs to be automated.

**Comment by Myrkie** [comment]
could be automated yes but if its a good idea is the question.

**Comment by Natsumi-sama** [comment]
Use this VRChat launch param it will give VRCX *most* userId's https://gist.github.com/Natsumi-sama/d280a58f08ace3da0e8fc7a9a381d44e

**Comment by Myrkie** [comment]
> Use this VRChat launch param it will give VRCX _most_ userId's https://gist.github.com/Natsumi-sama/d280a58f08ace3da0e8fc7a9a381d44e

this should get merged into the launch parameters wiki page might be helpful

**Comment by mossarelli** [comment]
> Use this VRChat launch param it will give VRCX _most_ userId's https://gist.github.com/Natsumi-sama/d280a58f08ace3da0e8fc7a9a381d44e

Thanks, will try it.

**Comment by mossarelli** [comment]
Using the solution 

> Use this VRChat launch param it will give VRCX _most_ userId's https://gist.github.com/Natsumi-sama/d280a58f08ace3da0e8fc7a9a381d44e

Using that parameter made VRCX autofetch all the players in the list, I can consider this ticket closed, but maybe put in the app somewhere in the help section how to use the parameter for future users.

As it looks right now it will autofetch all players in the list except for say 5%.

**Comment by Natsumi-sama** [comment]
Yup it's a weird caveat with how it gets userIds, it only works if the user is representing a group or if you open the user with the big menu in-game.
