### ISSUE TITLE
[Feature Request] Opt-Out of world/avatar tracking

### ISSUE THREAD

**Issue by KenahlOwO** [vrcx-team/VRCX#637]
**Explain in detail what your suggested feature would be used for.**
It would be used for people who do not want to be monitored, based on stuff like what avatar they're in, or what world they're in.
**Describe how it would look if it requires a UI.**
It wouldn't really need an UI, probably just some kind of switch/toggle in settings or somewhere easily accessible, in order to set yourself to "private" on VRCX, so no one is able to see information such as when you switch worlds, or avatars.
**Explain why people would want to use it.**
pretty much to avoid friends who use VRCX as a way to watch what they do on VRChat without them knowing/their consent (Privacy)

It would be helpful to have some kind of option to "opt-out" of VRCX's features such as world/avatar information being shared to those who have VRCX.

**Comment by Natsumi-sama** [comment]
VRCX has zero control over the VRChat API so this isn't possible in the way your expecting. But what you *can* do is set you status in-game to ask-me or busy this will hide what world you're in and with VRC+ you can set a profile photo this will hide what avatar you're in.

**Comment by KenahlOwO** [comment]
I'd honestly just want some way to possibly "opt-out" of VRCX stuff, not doing anything to the VRChat API stuff, but just like somehow "opting out" so your VRChat API information isn't shown on VRCX to anyone. Also, even if you end up setting a profile photo, someone would still be able to see if you changed avatars or stuff like that using the VRCX feed.

**Comment by BLANKE1** [comment]
VRCX only has friends in the feed section, if you're friends with someone who's stalking you. You should put your worries elsewhere and remove them as a friend.

**Comment by information-redacted** [comment]
As Natsumi pointed out, VRCX is nothing more than a more fancier version of the website with a local database. All data that VRCX receives (sans avatar search, which is provided by third-party providers you define) comes directly from VRChat's API, and is the exact same information exposed by the website, just with some correlation applied (e.g.: avatar names found from images uploaded).
 
Say that there *was* a way to opt-out of your data being stored in the local database of a VRCX install, that does not prevent anyone from using the libraries provided by @vrchatapi to effectively do the same, let alone anyone simply modifying their VRCX install (or outright forking the project) to remove those restrictions.

Your options are:
 - Hide your traveling status via the Orange/Red statuses in-game.
 - Hide your avatar switches by setting a profile picture with VRC+. VRCX captures avatar changes by noticing a difference in your profile picture, as avatar names are traced back by the image name.
 
 Asking for an opt-out feature in a client-side application whose data is provided by the official game servers is simply pointless, as it can be easily circumvented.
