### ISSUE TITLE
[Feature Request] auto-invite

### ISSUE THREAD

**Issue by MexyACJ** [vrcx-team/VRCX#640]
auto-invite would be used to automatically invite those who are whitelisted on vrcx by you whenever they request to join you(if possible to join that is; non-instance master of a invite+<1>)

the ability to whitelist someone would be under the drop menu where you can already request invite, request invite with message(, invite, invite with message, favorite, ect) and a whole list of all the ppl you've whitelisted under profile underneath where you can change your request/invite/send responses.

it would be a very niche group of ppl that would want to use it, ppl that fell asleep in game, super close friends/couple that are basically always together so they don't have to manually accept each requests.

<1>: if you know how invite+ works, as instance master of the world you can invite your friends to the world while your friends can't... unless that person they are trying/want to invite is also on your friends list.

I honestly don't know if this is possible to do but might as well ask if it can be done.

**Comment by Myrkie** [comment]
It's possible to do, but it being a very niche feature as you yourself said
probably wouldn't be worth the development time to implement and maintain.
The VRCX code base is already in a dire need of a rewrite as is.

**Comment by Natsumi-sama** [comment]
This is more of a feature VRChat should add rather than VRCX, as an alternative I recommend sending people unlocked instance links so they can join that instance at any time or create another VRC account to use for creating friend only instances.

**Comment by Lilypids** [comment]
I still think it should be a vrcx feature more over because I know vrc wont add it just for simplicity sake. The use case I want is if im sleeping or running an event in game locked to certain people id like for them to be auto invited when they request while others can be invited under my digression.

**Comment by MexyACJ** [comment]
Not gonna like I kinda found a way to do this with vrc groups by using the members roles

**Comment by MexyACJ** [comment]
Op I didn't mean to close. I don't know if ppl can still leave comments if it's closed so I'm reopening it sorry

**Comment by Natsumi-sama** [comment]
Dupe issue
