### ISSUE TITLE
[Bug] [niche] Overlay not showing.

### ISSUE THREAD

**Issue by noideaman** [vrcx-team/VRCX#642]
**Describe the bug**
Wrist Overlay not displaying. Need to know how to re-register the overlay to steamvr

**To Reproduce**
1: use custom backup profiles in Microsoft's USMT
2: reinstall windows
3: recreate widows profile with the restore function of USMT
4: log in to the account USMT restored
5: launch vrcx. credentials are remembered from the USMT restore
6: launch steam . same as above with credentials
7: launch steamvr, playspace profile was also migrated over
8: launch vrchat, credentials where remembered as well from USMT
9:no vrcx overlay, no icon in steamvr dashboard

**Expected behavior**
Wrist overlay should show

**What version you are running**
Version 2023.07.30

**Comment by Myrkie** [comment]
try running with GPUFIX launch parameter for VRCX https://github.com/vrcx-team/VRCX/wiki/Launch-parameters

**Comment by noideaman** [comment]
thanks for the tip, sadly still no overlay, and no button in the steamvr dashboard.

**Comment by Myrkie** [comment]
most likely an issue with the library itself, maybe steamvr console would provide some information http://localhost:27062/console/index.html

**Comment by noideaman** [comment]
[steamvr.txt](https://github.com/vrcx-team/VRCX/files/12505087/steamvr.txt)

**Comment by Myrkie** [comment]
steamvr is implying that its loading and connecting properly, so not sure what could be causing it 

```
New Connect message from C:\Program Files\VRCX\VRCX.exe (VRApplication_Background) (Args: --gpufix) 5196 
Creating Builtin AppInfo for C:\Program Files\VRCX\VRCX.exe (VRApplication_Background). , , 5196
AppInfoManager.ProcessConnected BEGIN 5196 C:\Program Files\VRCX\VRCX.exe 3 system.generated.vrcx.exe
SetApplicationPid appkey=system.generated.vrcx.exe pid=5196, external transition
SetApplicationPid: Setting app system.generated.vrcx.exe PID to 5196
AppInfoManager.ProcessConnected END
[Input] Enabling legacy input for system.generated.vrcx.exe
[Input] system.generated.vrcx.exe (indexhmd) attempting to load default config from file:///C:/Program%20Files%20%28x86%29/Steam/steamapps/common/SteamVR/resources/config/legacy_bindings_generic_hmd.json

```

maybe try removing gpufix and continuing

**Comment by noideaman** [comment]
Results, still nothing.
![image](https://github.com/vrcx-team/VRCX/assets/39884745/137c5ff0-8af8-4cb8-8f43-2e1f523bc6fb)

**Comment by Myrkie** [comment]
yeah not sure then, steam see its but doesn't initialize it

**Comment by noideaman** [comment]
I will give a reinstall test soon. updated my XML for backups to be a bit more restrictive.
insted of the entire config dir i am grabing just .vdf and .vrchap (steam config files for the client and what looks to be the chaperone file for steamvr
