### ISSUE TITLE
[Bug] Player is joining does not work

### ISSUE THREAD

**Issue by Myrothas** [vrcx-team/VRCX#644]
A friend of mine is having the issue, that everything works, except "player is joining".
It works fine for me and everyone else i know - but not for her - only when a player joined.
It does not show whenever a player clicks join - only when player has joined.
She runs AMD CPU 3060 GPU on Laptop.

Much love!
![Screenshot_4](https://github.com/vrcx-team/VRCX/assets/87095612/a5cea0f6-7b21-4e4a-9cbb-5a1efc93650c)

**Comment by Myrkie** [comment]
OnPlayerJoining uses the data that VRChat sends over the websocket. Which means that it does not work if the person is on Do not disturb or Ask me. This is a VRChat issue not a VRCX issue. The websocket is known to misbehave due to IP V6 so try disabling that.

**Comment by Myrothas** [comment]
we tried it both on green and blue status. u think we should disable IPv6?

**Comment by Myrkie** [comment]
> we tried it both on green and blue status. u think we should disable IPv6?

yes, disabling IPV6 is within vrchat's own recommendations when you have issues with the websocket, such as receiving notifications in game or friend list updating issues.

**Comment by Myrothas** [comment]
thank you, i will try this and let you know if it solved it.

**Comment by Myrothas** [comment]
We deactivated it and test-ipv6.com said its inactive.
It still did not work for her. :(

**Comment by Myrkie** [comment]
> We deactivated it and test-ipv6.com said its inactive. It still did not work for her. :(

in that case then not sure what to say if VRCX is not receiving the data that's on vrchat

**Comment by Natsumi-sama** [comment]
OnPlayerJoining only works for friends, if they're using a different account with VRCX than in-game it could cause this to not work.

**Comment by Myrothas** [comment]
Same account and is a friend. I'm clueless. I guess it must still be the IPv6 thingy even tho its disabled. Ugh.

**Comment by Natsumi-sama** [comment]
Some more things to try:
 - Make sure latest version of VRCX is installed.
 - Make sure that they're looking at the correct filters window.
 - Are the current working OnPlayerJoined notifications coming from VRCX or somewhere else?
 - Can they see the GPS entry in the main feed when a friend joins their instance?
 - Can they see friends in their current instance inside the user dialog?

**Comment by Myrothas** [comment]
Latest VRCX is installed.
I gave her my exact settings.
The mentions are from VRCX because the entire VRChat HUD is disabled.
Yes she can see the GPS entry in the main feed.
I dont understand the very last one. :x

Much love.

**Comment by Myrkie** [comment]
> Latest VRCX is installed. I gave her my exact settings. The mentions are from VRCX because the entire VRChat HUD is disabled. Yes she can see the GPS entry in the main feed. I dont understand the very last one. :x
> 
> Much love.

the last one being select yourself in vrcx and see if the friend you want to see joining appears in the instance dialog in the area below when online

![image](https://github.com/vrcx-team/VRCX/assets/20288698/e43d00ab-3985-4580-a4fa-4cfe82be2a17)

**Comment by Myrothas** [comment]
Thank you, i will try tomorrow when shes ready for it and update you on that.

Much love.
