### ISSUE TITLE
[Bug] Apps launched with VRCX auto close despite the auto close options being off

### ISSUE THREAD

**Issue by fwenny** [vrcx-team/VRCX#648]
**Describe the bug**
When closing VRCX all apps close.
Additionally, apps do not open/reopen if launching VRCX AFTER VRC

**To Reproduce**
Open vrcx, with some startup apps set up
Launch vrc
Close vrcx

**Expected behavior**
Apps should not close

**Screenshots**
![image](https://github.com/vrcx-team/VRCX/assets/44194453/23bedbb1-dd7f-4d02-915f-b852416c9fa6)

**What version you are running**
VRCX 2023.07.30

**Comment by Natsumi-sama** [comment]
https://github.com/vrcx-team/VRCX/commit/d95d25742f701c7b482fc2461116fcf454de7f50

**Comment by fwenny** [comment]
Thanks Natsu!
Does the auto run apps not opening if vrcx is ran after vrchat also a bug? or is it working as intended?

**Comment by Natsumi-sama** [comment]
Both behaviors were originally intended but because they were perceived as bugs will likely change depending on the amount of work it will required.
