### ISSUE TITLE
[Feature Request] Logging own info as the app does for other users

### ISSUE THREAD

**Issue by MellowEdge** [vrcx-team/VRCX#650]
**Explain in detail what your suggested feature would be used for.**
I suggest an ability for VRCX to log your own info. Everything that other players have now but you don't. Examples: status and bio changes, online/offline timestamp, avatar switches.

**Describe how it would look if it requires a UI.**
Just use the same parts of the UI, but with your username and/or as "You"

**Explain why people would want to use it.**
Could be useful for remembering any stuff you did before

**Comment by Natsumi-sama** [comment]
Duplicate, due to how VRCX works internally it requires a lot of work https://github.com/vrcx-team/VRCX/issues/318
