### ISSUE TITLE
VRCX overlay not working + forcing VRC into desktop

### ISSUE THREAD

**Issue by wolfey2900** [vrcx-team/VRCX#651]
**Describe the bug**
I just installed VRCX and tried to launch VRC with it. at first my overlays will not work in VRC and i have no clue of why. I didn't change anything other than enable Wrist overlay. though when I restart VRCX and steamVR, launching VRC it will stop responding for a short moment then force itself into desktop mode. it will not launch in VR mode. and it causes VRC to think its permanently open in the background wham I close it so when I'm in VR I have the VRC tag with "coming Up" as if its launching but there's no task of VRC that is running. 

**To Reproduce**
IDK what I did wrong all I did was install and enable steamVR wrist overlay, 
Steamvr overlay on
feed overlay on 
set to VRChat 
set to Grip

**Expected behavior**
I expected to use the VRCX Ingame Overlay menu. 

**What version you are running**
Version 2023.07.30?

**Comment by Myrkie** [comment]
https://github.com/vrcx-team/VRCX/wiki#steamvr-overlay-not-working

**Comment by Myrkie** [comment]
> https://github.com/vrcx-team/VRCX/wiki#steamvr-overlay-not-working
did you follow the steps above?


Launching VRChat via VRCX has some settings to either launch in vr or non vr, make sure to uncheck the box 
![image](https://github.com/vrcx-team/VRCX/assets/20288698/f62dcbdd-4f94-477c-ae42-ed5be3792bfd)

**Comment by wolfey2900** [comment]
> > https://github.com/vrcx-team/VRCX/wiki#steamvr-overlay-not-working
> 
> did you follow the steps above?
> 
> Launching VRChat via VRCX has some settings to either launch in vr or non vr, make sure to uncheck the box ![image](https://user-images.githubusercontent.com/20288698/270202933-f62dcbdd-4f94-477c-ae42-ed5be3792bfd.png)

I do not see this setting anywhere in VRCX.
