### ISSUE TITLE
[Bug] 401 Unauthorized "Invalid Username/Email or Password" (Even though the credentials are correct)

### ISSUE THREAD

**Issue by GODZILLA6337** [vrcx-team/VRCX#655]
**Describe the bug**
Everytime I go to login it always gives me the 401 Unauthorized error even though my credentials are correct. I've quadruple checked them front to back. This has been going on for some time.

**To Reproduce**
1. Go to Login Screen
2. Enter Credentials
3. Hit Login
4. Error appears below on bottom left
_401 Unauthorized
 "\"Invalid Username/Email or Password\""
 "auth/user"
 
**Expected behavior**
Being able to log in and use the software after not being able to for a long time.

**What version you are running**
Version Latest 2023.09.18
Also tried the Nightly Build 2023-09-24T14.02-c37ac54

I made a report about this awhile back like a year ago and there wasn't much help and it got closed so it was never resolved.
I distinctly recall one of the last entries in the support thread being some idjit with no prior experience (not that I have any either) giving extremely useless advice somewhere along the lines of recommending I re-install or turn it off and back on as If I hadn't already tried those fixes. (Apologies for the mini rant)

![image](https://github.com/vrcx-team/VRCX/assets/66243273/2027a3fc-32c1-4f4c-999f-5be15fc90152)
![image](https://github.com/vrcx-team/VRCX/assets/66243273/a6e5f04b-4ccf-4e23-bd44-92bf93d04dac)
![image](https://github.com/vrcx-team/VRCX/assets/66243273/7e66fcfc-bc25-4043-8436-d820e32ef1ad)

**Comment by Natsumi-sama** [comment]
did you try change your password to one without weird symbols and use your email to login? your login details should be the same as when you login to the VRChat website

**Comment by GODZILLA6337** [comment]
I have not
I suppose I can test that
I've been using the correct login details but somehow it's not recognizing em

**Comment by GODZILLA6337** [comment]
Turns out it was the symbols.
Interesting, I suppose vrcx doesn't like symbols in the password field
 Apologies for the trouble.

**Comment by Natsumi-sama** [comment]
VRCX shouldn't handle the symbols any different that the website, I'd like to try reproduce if you could list the symbols you used

**Comment by GODZILLA6337** [comment]
Sure, all I used was @ and &
@ at the beginning which might have had something to do w it and & at towards the end as well as a set of 4 of numbers behind @ and before the &
