### ISSUE TITLE
[Feature Request] Group Member Join/Leave Notification

### ISSUE THREAD

**Issue by Twiluff** [vrcx-team/VRCX#661]
This feature can be used to get notified whenever someone leaves/joins a VRC group you own.

2 sections in the "notification filter" tab that says "Personal Group Member Left" and "Personal Group Member Joined" with 3 switches that can go from "Off" "Favorites" "Friends" "Everyone"

It can be useful for anyone who is curious to know who leaves and who joins their group and possibly question why the person left or joined.

**Comment by Myrkie** [comment]
VRChats API doesn't let a user fetch more than 5100 members, and you would have to pull all members of every group to track who has joined and who has left, which would make this feature not possible, this would also cause excessive spam to the API which VRChat is very clear about not doing.
