### ISSUE TITLE
[Feature Request] Copy link to world

### ISSUE THREAD

**Issue by Adam-Kay** [vrcx-team/VRCX#669]
## Explain in detail what your suggested feature would be used for
I think it would be great to have a button to quickly copy a world link when using the _Direct Access ID_ button in the top right. This would take what you're currently looking at (in this case most likely worlds) and give you a link to the VRChat website for them. 
For example, for the ID `wrld_31a96742-b161-4f76-96c5-5105b64ff0f7` it would spit out https://vrchat.com/home/world/wrld_31a96742-b161-4f76-96c5-5105b64ff0f7 .

## Describe how it would look if it requires a UI
It would probably be added to the ••• menu on the _Direct Access ID_ result panel, like so:
![image](https://github.com/vrcx-team/VRCX/assets/10010491/df78350a-80ba-4ae3-80aa-680fd693c5f1)

## Explain why people would want to use it
This would be great for quickly sharing world links with people, especially other people who may not be using VRCX.

**Comment by Myrkie** [comment]
go to the info tab > Copy URL
![image](https://github.com/vrcx-team/VRCX/assets/20288698/4cb60604-f0ae-4dae-9ceb-31f4db7ea049)

**Comment by Adam-Kay** [comment]
Goddamn it, I knew I was missing something. Thanks!
