### ISSUE TITLE
[Bug] VRCX crashing

### ISSUE THREAD

**Issue by MochaCocah** [vrcx-team/VRCX#671]
**Describe the bug**
Constant crashing on windows 11, latest update.

**To Reproduce**
1. Open VRCX
2. Open VRCHAT
3. VRCX crashes

**Expected behavior**
Open vrchat, vrcx should not crash and should be working with no issues.

**Comment by Natsumi-sama** [comment]
What sort of crash, white screen, freeze or closes?
Try disable "App Launcher" in advanced settings.
Try launch VRChat in desktop mode to make sure it's not SteamVR overlay related.
An antivirus might not like VRCX reading a file when the game starts try disable any antivirus you may have.
Check VRCX log `%AppData%\VRCX\logs`
