### ISSUE TITLE
[Bug] white screen, and dev tool got two error message

### ISSUE THREAD

**Issue by JackyM04** [vrcx-team/VRCX#672]
**Describe the bug**
white screen, and dev tool got two error msg 
    "Uncaught (in promise) TypeError: Cannot read properties of null (reading 'noty') at app.js:14678:38"
    "Uncaught ReferenceError: $app is not defined at about:blank:1:1"
I tried re start my computer
I tried to re-install it and tried current and one previou version and it still no work.
This issue after I update the new driver for my GPU but I tried to downgrade back to previous version.
I also tried strart as admin administrator
......

**To Reproduce**
Any time run it

**Screenshots**
<img width="1427" alt="屏幕截图 2023-10-20 010427" src="https://github.com/vrcx-team/VRCX/assets/69099430/f2f4d71c-3686-42c3-9cb6-f68d12188061">

**What version you are running**
Version [20230918, 20230730]

system: windows 11 22621.2428

**Comment by JackyM04** [comment]
I del the userdata file in C:\Users\****\AppData\Roaming\VRCX and it work now

**Comment by Natsumi-sama** [comment]
Only the `userdata` folder? or everything in `Roaming\VRCX`?

**Comment by Natsumi-sama** [comment]
Oh interesting, thanks for the info.

**Comment by JackyM04** [comment]
I'm sorry, I might have made an incorrect judgment maybe. I just tried cover my old VRCX.sqlite3 for restore my data and it cause crash, but the userdata folder I deleted, so I can not try it again. Maybe it not because of the userdata, is VRCX.sqlite3

**Comment by xiatiaopoi** [comment]
really helpful
