### ISSUE TITLE
unable to detokenize presence data

### ISSUE THREAD

**Issue by Raseraa05** [vrcx-team/VRCX#676]
**Describe the bug**
Whenever I try to login to VRCX it gives me an error 500 "unable to detokenize presence data" and immediately logs me out. Also says "Failed to load friends list. Logging out." I should also state that VRChat isn't loading my friends list either when I log in.

**To Reproduce**
Logging in to VRCX

**Expected behavior**
Logging in and everything working fine as usual

**Screenshots**
![image](https://github.com/vrcx-team/VRCX/assets/148895865/4904308d-a6f3-4830-9de9-b3b0386a7c11)

**What version you are running**
VRCX 2023.09.18

**Comment by Natsumi-sama** [comment]
You'll need to contact VRChat support for this issue, including this info will help them with fixing it.

**Comment by Natsumi-sama** [comment]
VRC staff have since fixed it https://discord.com/channels/189511567539306508/1166205113304629299/1166566305625804850
