### ISSUE TITLE
[Bug] Vrcx not doing anything

### ISSUE THREAD

**Issue by Nukeman52** [vrcx-team/VRCX#678]
I don't really have much to go off on this issue.
When I launch vrcx I can see it running in task manager and accumulate ~30Mb of ram uses 0.2% of cpu and it doesn't do anything else.
I have tried downgrading and it still didn't do anything.
Vrcx has worked for a whole year until now

**Comment by Natsumi-sama** [comment]
Is it hidden in your windows task tray at the bottom right or your task bar?

**Comment by Nukeman52** [comment]
neither

**Comment by Natsumi-sama** [comment]
Give these steps a try https://github.com/vrcx-team/VRCX/wiki#vrcx-opens-to-a-white-screen

**Comment by Nukeman52** [comment]
Also I didn't realize the logs are in appdata
all the logs there say this
2023-10-28 07:33:52.6114 [INFO ] VRCX                 - VRCX 2023.09.18 Starting... 
2023-10-28 07:33:52.7469 [INFO ] VRCX.WorldDBManager  - Listening for requests on http://127.0.0.1:22500/

**Comment by Nukeman52** [comment]
I went all the way to creating a new database and still no difference

**Comment by Natsumi-sama** [comment]
Maybe an anti-virus is blocking it, other than that all that can be done at this point is either reinstalling Windows or following the build guide [here](https://github.com/vrcx-team/VRCX/wiki/Building-from-source) and step though the code with a break point to find the line it freezes on.

**Comment by Nukeman52** [comment]
Idk what happened but i walked away for an hour and came back and it was loaded at the login page
I switched back to the original database and it works fine now
