### ISSUE TITLE
[Bug] Japanese Sign Language is not shown.

### ISSUE THREAD

**Issue by Cayahuanca** [vrcx-team/VRCX#680]
**Describe the bug**
1: In VRCX, on the screen to select the language to be displayed on my VRChat account profile, Japanese Sign Language (JSL) is not displayed and cannot be selected.
2: Even if I add JSL to my profile from the VRChat site, the JSL is not displayed when I view the user's profile on VRCX.
(Json includes the language_jsl tag)

**To Reproduce**
Problem 1:
1. Open VRCX
2. Open my profile page.
3. Press the three dots button "..." next to the icon.
4. Select Language button and show Language selection popup.
5. Can't show "Japanese Sign Language (jsl)"
![image](https://github.com/vrcx-team/VRCX/assets/42778938/2ab158a5-6471-487f-bf5d-390082d83b5b)

Problem 2:
1. Open VRCX
2. Open someone's profile page who is added JSL to user's language.
3. Open user json and check the tag "language_jsl" is added.
4. JSL icon isn'n shown to profile top.
![image](https://github.com/vrcx-team/VRCX/assets/42778938/300342ee-2c1c-490f-8eb7-94fbb684cb96)

**Expected behavior**
1: Users can add JSL as a language they can use.
2: User can see JSL icon.

**What version you are running**
Version VRCX Nightly 2023-10-31T06.37-8876f3e

**Comment by slord399** [comment]
There is it.
(yeah, not english but in Japanese
![image](https://github.com/vrcx-team/VRCX/assets/50810875/5ca29e1a-abd8-4d5b-8b5e-5eb3181f3fe0)
)

**Comment by Cayahuanca** [comment]
It is "Japanese"
Not "Japanese Sign Language"

Click here to learn more about Sign Language.
https://en.wikipedia.org/wiki/Sign_language
