### ISSUE TITLE
[Bug] not changing avatar when cloning or trying to change from avatar list 

### ISSUE THREAD

**Issue by kyroXfox** [vrcx-team/VRCX#681]
I just recently downloaded the current version of VRCX and was told by friends it can help me with gate keeping kids who wont share a public avatar. I was told you can force clone public avatars with VRCX and many other management things but I was disappointed when I got done downloading it only to find it changes my avatar pfp but not the avatar. every time I press change I get the question do I really want to and I click yes after that it says changed but in game nothing actually happens and if I favorite a avatar it doesn't actually add to my favorite's tell I close the game and reopen it. Also sometimes a avatar says public but when i press it instead of pulling up the avatar it pulls up the avatars maker thus leaving me unable to get the avatar again.

**Comment by Natsumi-sama** [comment]
- If an avatar isn't in any avatar database it will show the users profile instead.
- You can unfavorite/favorite any avatar in-game to force your favorites list to update.
- Changing avatar though the website or VRCX requires you rejoin the instance or restart the game for it to apply.

All of these limitations are outside the control of VRCX so "it is what it is".
