### ISSUE TITLE
[Feature Request] Avatar change in Game Log

### ISSUE THREAD

**Issue by darkfader** [vrcx-team/VRCX#682]
**Explain in detail what your suggested feature would be used for.**
Show avatar changes in Game Log for joined instance avatar changes.

**Describe how it would look if it requires a UI.**
Just show the avatar changes also in the Game Log section.

**Explain why people would want to use it.**
It could be used for moderation and debugging lag spikes.

**Comment by Natsumi-sama** [comment]
As far as I can see the VRChat gameLog file is missing a lot of required info in order to make this happen.

**Comment by Natsumi-sama** [comment]
`--log-debug-levels="Always;API;AssetBundleDownloadManager;ContentCreator;All;NetworkTransport;NetworkData;NetworkProcessing"` with this launch parameter you can see avatar changes on wrist feed, notifications and console with `$app.debugGameLog = true`
