### ISSUE TITLE
[Feature Request] Add an endpoint that gives the list of users in the world you are in

### ISSUE THREAD

**Issue by LakesideMiners** [vrcx-team/VRCX#684]
Add an endpoint to the local API that allows fetching a list of users in the world you are in.

No UI would be required for this, as the port is already in the docs.

Would be useful for people making third party apps to allow for fetching a list of users in the world without having to code in a logger for users into their apps.

**Comment by Natsumi-sama** [comment]
VRCX already has enough obscure unmaintainable feature creep, I consider this too far out of scope but I don't believe you need VRCX for this at all if you search on github for VRChat log parsers I'm sure you'll find one in any language you want, this would also minimize dependencies for your project.
