### ISSUE TITLE
[Bug] Copy User URL Missing

### ISSUE THREAD

**Issue by JanieUwU** [vrcx-team/VRCX#685]
**Describe the bug**
There is no copy user url button when viewing a user profile under the 3 dots menu on the top right.

**To Reproduce**
Try to get the user's url link via the profile menu. The option is missing.
**Expected behavior**
The option to copy the User URL from the menu to be there.
![image](https://github.com/vrcx-team/VRCX/assets/63387805/a466afdf-d130-4951-bd2d-e9394f396328)

**What version you are running**
Version 
VRCX 2023.11.06

**Comment by Myrkie** [comment]
scroll down it has moved to its own div

![image](https://github.com/vrcx-team/VRCX/assets/20288698/31baabbd-f1bb-4e2f-86f7-43579978535f)
