### ISSUE TITLE
[Bug] startup

### ISSUE THREAD

**Issue by kyroXfox** [vrcx-team/VRCX#686]
when i go to start it there is no startup file iv tried unstalling and reinstalling it but it says run after done then tells me cant find start up file ? i had it working all this time then it said something about update and the shortcut stopped working and i cant find a run or anything in its files

**Comment by Natsumi-sama** [comment]
Reinstall using the setup and make sure your anti virus isn't deleting files

**Comment by kyroXfox** [comment]
> Reinstall using the setup and make sure your anti virus isn't deleting files

![image](https://github.com/vrcx-team/VRCX/assets/100985179/f517d228-fe72-4525-8a03-633243e54040)

**Comment by Myrkie** [comment]
> > Reinstall using the setup and make sure your anti virus isn't deleting files
> 
> ![image](https://user-images.githubusercontent.com/100985179/282343488-f517d228-fe72-4525-8a03-633243e54040.png)

make sure vrcx is fully closed from task manager

**Comment by kyroXfox** [comment]
> > > Reinstall using the setup and make sure your anti virus isn't deleting files
> > 
> > 
> > ![image](https://user-images.githubusercontent.com/100985179/282343488-f517d228-fe72-4525-8a03-633243e54040.png)
> 
> make sure vrcx is fully closed from task manager

i did maid sure it was all closed and im still getting the same stuff. i cant install the run.exe?

**Comment by Myrkie** [comment]
its happening during a file write so that means that the file has been write locked by another program, try restarting your pc first and then closing vrcx if it auto starts.
