### ISSUE TITLE
[Feature Request] Auto accept invite requests

### ISSUE THREAD

**Issue by Tazaur** [vrcx-team/VRCX#691]
Very Easy to implement:

A Simple list box to put players (or possibly set a friends favorites group to this) where any players who are on that list are auto invite-accepted to your world, even if you are on orange or in an Inv+. (DND should still be DND)

This utilizes the simple accept/reject functions already built into VrcX, but automates it. Every invite request that is recieved gets checked against the list. if their name is on there, it auto-accepts. So long as the program is running in the background, our very special friends can always join us.

Ideal for when you have those friends (or that special someone) that you can't get enough of, but want to not be joined by just ANY of your friends...
It creates an always-present open invite for specific friends.

**Comment by Natsumi-sama** [comment]
Duplicate request https://github.com/vrcx-team/VRCX/issues/495
