### ISSUE TITLE
[Bug] user_id from none Friends only doesnt store in gamelog_join_leave

### ISSUE THREAD

**Issue by NekoSuneVR** [vrcx-team/VRCX#694]
**Describe the bug**
Not sure if is New changes or BUG but pose log they UserIDS in join_leave sector of SQLLITE file for easy defined users

but some reasons it wont log it part only Friends only and im unsure if is bug or not but my discord bot logs from gamelog_join_leave in SQLLITE for Detect if userid match and if is true alerts me if they in my private api list

but i have no other way pull Join_Leave sessions to grab userid since my Discord BOT uses VRCX at moment less any other way round it without VRCX.

i just hide my friends UserID for Security even everyones names too but see all blank parts in SQLLITE DB file in gamelogs_join_leave

**Screenshots**
![image](https://github.com/vrcx-team/VRCX/assets/18028479/2917b02c-91b0-4a57-a6b0-0e4443831a25)

**What version you are running**
Version VRCX Nightly 2023-11-21T13.25-716ee37

**Comment by NekoSuneVR** [comment]
extra node it stopped workign in gamelog_join_leave in line `2023-06-23T07:01:44.000Z` as date and nothing  updated by then

**Comment by Natsumi-sama** [comment]
I cannot decipher your message. But I'm going to assume what you're asking is why userId's are missing from your gameLog, you need this VRChat launch parameter `--log-debug-levels=API`

**Comment by NekoSuneVR** [comment]
that will it work?
