### ISSUE TITLE
[Bug]   web socket error

### ISSUE THREAD

**Issue by lianliu503** [vrcx-team/VRCX#697]
**Describe the bug**
Error will be reported when adding proxy rules using Clash for Windows 
Vrcat ban is my VPN, so I added a rule to clash to prevent it from proxy for vrcx

**To Reproduce**
![{B9019B64-8206-46bd-941F-81C0A8597F2C}](https://github.com/vrcx-team/VRCX/assets/146159715/57204d45-c959-4e97-8494-0c1cfd8482c2)
![{12706F81-92EE-476f-98C9-CAFE0BB2069C}](https://github.com/vrcx-team/VRCX/assets/146159715/140e9713-7d60-4de9-a7d5-1939795b1812)

**Expected behavior**
Just this error occurred, but there are currently no usage issues

Version 2023.11.06

**Comment by Myrkie** [comment]
you will also have to whitelist the websocket URL

`wss://pipeline.vrchat.cloud/`

**Comment by lianliu503** [comment]
> 您还必须将 Websocket URL 列入白名单
> 
> `wss://pipeline.vrchat.cloud/`

非常感谢
