### ISSUE TITLE
[Feature Request] Enhancing UI Responsiveness by Modifying Animation Interactions

### ISSUE THREAD

**Issue by LIII-Works** [vrcx-team/VRCX#701]
# Explain in detail what your suggested feature would be used for.

The proposed feature aims to enhance the user interface (UI) responsiveness by speeding up animation sequences. Currently, certain UI menus incorporate animations that prevent user interaction until the animation sequence is complete. While these animations serve to smooth transitions and mask data loading times from local or remote servers, they inadvertently impact the responsiveness of the application.

[Demo of menu animation](https://streamable.com/viqtxl)

# Suggested Improvement

`Allow user Input During Animations` This involves modifying the UI to accept user input even while animations are playing. This could involve making buttons and other interactive elements responsive during the animation sequence, allowing users to proceed with their tasks without waiting for the animation to complete.

`Animation Interruption` This allows users to interrupt an ongoing animation. A simple click or command could halt the animation, enabling immediate access to the UI.

`Speed Up Animations` By speeding up animations, the overall responsiveness of the application can be enhanced, leading to a more seamless and efficient browsing experience.

# Explain why people would want to use it

By speeding up animations, the overall responsiveness of the application can be enhanced, leading to a more seamless and efficient browsing experience. This feature is expected to significantly improve the user experience by reducing the time spent on actions such as transferring favorites through these windows.

**Comment by Natsumi-sama** [comment]
https://github.com/vrcx-team/VRCX/issues/453
