### ISSUE TITLE
playerlist not showing anyone 

### ISSUE THREAD

**Issue by kyroXfox** [vrcx-team/VRCX#702]
im running the newest version i have auto install on. so i recently relised my player list was blank and i tried installing older versions that i know worked but it still stayed blank. so i tried rejoining worlds to load it in because i know sometimes it wiged out in the past and that fixed it but got nothing. then i tried restarting vrcx and rejoining world still didnt work. so now i cant see the people im with on there also meaning i almost missed out on a avatar i really wanted that a kid wouldnt give me tell i litterly begged which i dont like doing for a avatar thats public but for some reason isnt in the database. which i also noticed vrcx is missing a lot of avatars.

**Comment by Myrkie** [comment]
1. if this is not the case please provide the output of the console by pressing `Ctrl + Shift + I`
2. not all avatars are logged in the database as its a community project and is not guaranteed to have all avatars ever uploaded (VRC is a big game with millions of avatars)

**Comment by kyroXfox** [comment]
> 1. please provide the output of the console by pressing `Ctrl + Shift + I`
> 2. not all avatars are logged in the database as its a community project and is not guaranteed to have all avatars ever uploaded (VRC is a big game with millions of avatars)
![image](https://github.com/vrcx-team/VRCX/assets/100985179/18df92d9-9b24-4bcb-8912-dba8a2c5048c)

**Comment by Myrkie** [comment]
please go to the console tab and show that.

**Comment by kyroXfox** [comment]
> please go to the console tab and show that.
![image](https://github.com/vrcx-team/VRCX/assets/100985179/788f2bb2-a980-43f5-bbac-09253daa0484)

**Comment by Myrkie** [comment]
try enableing app debug by typing `$app.debug = true` into the console and start vrchat, see if you get any logs that say

`'isGameRunning' true`

example: 
![image](https://github.com/vrcx-team/VRCX/assets/20288698/5b82e672-1e47-4299-9b95-d081318b3760)

**Comment by kyroXfox** [comment]
well i usualy open vrc on my quest but this is what i get opening it from steam 
![image](https://github.com/vrcx-team/VRCX/assets/100985179/3db5773d-d1e4-4e8d-9ea5-3d03deb64f2b)

**Comment by Myrkie** [comment]
open VRC on your quest? are you using virtual desktop or SteamVR Link / Tether?

**Comment by kyroXfox** [comment]
no iv been play vrc on quest lately because my laptop got slow so just standalone

**Comment by Myrkie** [comment]
> no iv been play vrc on quest lately because my laptop got slow so just standalone

vrcx requires that VRC be ran on the device VRCX is installed on as it has to read the contents of your VRChat Output log located at `%AppData%\..\LocalLow\VRChat\VRChat` this is not accessible on quest as its on another completely separate device and thus what you are asking is not possible

**Comment by kyroXfox** [comment]
oh so im the problem? damn well thx for the info sorry to waste time

**Comment by Myrkie** [comment]
> oh so im the problem? damn well thx for the info sorry to waste time

yes, vrchat doesnt provide information about users in the lobby unless that lobby is public facing and they are your friends and are not on a status that blocks location IE: Ask me / Do not disturb, VRCX has to get this information by reading the output of your VRChat log that contains information about who has joined and left the lobby
