### ISSUE TITLE
[Feature Request] port conflict with flashpoint archive

### ISSUE THREAD

**Issue by krum110487** [vrcx-team/VRCX#706]
**Explain in detail what your suggested feature would be used for.**
We have recently found a problem where we have modified plugins to proxy traffic  to port 22500, which is seems this application is using for a localhost, we are as well. Ours is not easy to change and I really just wanted to make you aware that if you have someone with flashpoint open, it will conflict with your app.
Since ours is hard to change, it would be nice if you had a config item to change yours. (You may already have this, I'm not fully aware of this apps capability)
This way, if we have someone with this app in the future, we can guide them in how to change the port.

**Describe how it would look if it requires a UI.**
A field to set the port.

**Explain why people would want to use it.**
To prevent port collisions with flashpoint archive.

Thanks!

**Comment by Natsumi-sama** [comment]
Our port is hard-coded into user generated content making it near impossible to change, best we can do is add a disable switch for the webserver as it isn't crucial for most of the programs functionality.

**Comment by krum110487** [comment]
That is fine, I mostly wanted to bring it to your attention that the two programs will have conflicts.
