### ISSUE TITLE
[Feature Request] Ability to disable the world persistence feature.

### ISSUE THREAD

**Issue by Lafikateh** [vrcx-team/VRCX#710]
Currently, the app listens for connections the whole time it is running, regardless of whether VRChat is running or not.

Additionally, the app somehow manages to open the socket as the "System" process, making it impossible to block at the firewall level.
![image](https://github.com/vrcx-team/VRCX/assets/73808989/1c1837d2-8558-4f8a-9c34-e0d73fe86db8)

There is no option to enable/disable this feature, so those that don't want it for whatever reason are out of luck.

**Comment by Myrkie** [comment]
a kill switch is being considered to also resolve possible port conflicts. https://github.com/vrcx-team/VRCX/issues/706
