### ISSUE TITLE
[Bug] VRCX always asks for 2fa code even though there were no changes to prompt for 2fa

### ISSUE THREAD

**Issue by TheRealDanini** [vrcx-team/VRCX#711]
**Describe the bug**
When on the latest version 2023.12.24 stable when logging into an account, it asks for 2fa, when logging out of the account and logging in again with the saved credentials feature it asks for 2fa again. This did not happen in the previous version of VRCX

**To Reproduce**
Install VRCX 2023.12.24 stable
Login to an account with 2fa
Once logged in, log out of that account and use saved credentials to log in again
VRCX will then ask for a 2fa code even though the session should be "trusted" in the future

If you check with the previous build 2023.11.06 stable it should not ask for a 2fa code again after you confirm the login with 2fa

**Expected behavior**
VRCX should not ask again for a 2fa code after a session has been trusted with 2fa when switching accounts

**Screenshots**

**What version you are running**
Version 2023.12.24 stable

**Comment by Natsumi-sama** [comment]
Latest and previous build store user cookies differently, switching between builds will expire your cookies and require you to sign in again. If you're having issues with cookies not saving on latest build try remove your saved account then re add it, I believe this will fix any cookie related issue.

**Comment by TheRealDanini** [comment]
> Latest and previous build store user cookies differently, switching between builds will expire your cookies and require you to sign in again. If you're having issues with cookies not saving on latest build try remove your saved account then re add it, I believe this will fix any cookie related issue.

I will try this, I did remove the accounts and try logging in again but it was still asking for 2fa even though I already did put in 2fa on newly created saved credentials. though this gave me the thought to try removing the saved credentials then update and see if the issue persists then.

**Comment by TheRealDanini** [comment]
Tried clearing out the accounts before updating and then creating new saved credentials to see if that fixes it and it did not, still asks for 2fa after logging back in with saved credentials. Confirming that this is only related to 2023.12.24 stable and it was not an issue before updating on 2023.11.06 stable.

**Comment by Natsumi-sama** [comment]
Okay thanks I was able to replicate the bug by switching account, I'll let you know once it's fixed.

**Comment by TheRealDanini** [comment]
Replying to confirm that this issue appears to be fixed in pre release 2024.03.17 and from testing it appears to no longer be an issue with this build. This issue can probably be closed now unless it comes back in a future build
