### ISSUE TITLE
[Bug] Game Security Violation Detected (#0000000E)

### ISSUE THREAD

**Issue by NFLD99** [vrcx-team/VRCX#713]
**Describe the bug**
VRCX Causes error Game Security Violation Detected (#0000000E) on game close. This happens with all EAC games

**To Reproduce**
1. Open VRCX
2. Open a EAC Protected game
3. Close the game

**Expected behavior**
The error shouldn't happen.

**Screenshots**
![RDT_20231231_1417258012046414920024764.jpg](https://github.com/vrcx-team/VRCX/assets/24623601/182f0963-eb73-4c80-833a-5ebacf80a8a0)

**What version you are running**
Latest

**Comment by Myrkie** [comment]
This is a EAC issue, not at all related to VRCX.
