### ISSUE TITLE
[Bug] Please use github actions to update client in Linux branch to 2024.03.23

### ISSUE THREAD

**Issue by OzzyHelix** [vrcx-team/VRCX#714]
it is well known that there are issues running VRCX under wine the last update was done in actions 2 months ago if someone could update VRCX to 2023.12.24 on the Linux branch that would be great

Sincerely Ozzy

**Comment by Natsumi-sama** [comment]
Give this build a try and let me know how it goes. https://github.com/vrcx-team/VRCX/actions/runs/7381921537

**Comment by OzzyHelix** [comment]
this is the error I get when trying to run it
![image](https://github.com/vrcx-team/VRCX/assets/29835364/71a4cea9-59a0-4a5d-b1e5-06fda2a07f40)

**Comment by BenjaminZehowlt** [comment]
That is due to a missing API in Wine, the first version to have any kind of support is 9.0-rc1

**Comment by OzzyHelix** [comment]
I'm running Wine 7 due to some glitching with the UI I can try upgrading

**Comment by OzzyHelix** [comment]
ok after installing wine 9.0 rc3 it works

**Comment by OzzyHelix** [comment]
wine 9 is a requirement for VRCX I guess but at least it works on Linux closing as complete

**Comment by OzzyHelix** [comment]
@Natsumi-sama could you update this using github actions to the new latest version?

**Comment by OzzyHelix** [comment]
I reopened the issue because of the update

**Comment by Natsumi-sama** [comment]
Apparently latest stable release will work under Linux but requires Wine 9.3 and corefonts

**Comment by Natsumi-sama** [comment]
https://github.com/vrcx-team/VRCX/tree/master/Linux
