### ISSUE TITLE
[Bug] Very slow, delayed updates on the Feed tab

### ISSUE THREAD

**Issue by Spirit532** [vrcx-team/VRCX#718]
**Describe the bug**
A few days ago I started noticing a weird issue - everything except players going online seems to take a really, really long time to update.
It can take several minutes for people's locations and status to update, but if I click on the refresh button myself, it updates immediately.
This doesn't happen on the Game Log tab, only on the Feed tab.

**To Reproduce**
1. Launch VRCX
2. Log into VRCX and VRChat
3. Go to an instance in-game
4. Compare what happens in the friend list to what happens in the Game Log tab when your friends join/leave. States don't update for minutes after things happen.

**Expected behavior**
Updates should happen much faster, if not realtime

**What version you are running**
2023.12.24

**Comment by Natsumi-sama** [comment]
In-game instance tab and VRCX gameLog is using real time info from your game to update, Feed and friends list uses VRChats API, maybe the API is taking a little longer than usual to do its thing this is outside of VRCXs control.
