### ISSUE TITLE
[Bug] Mutiple VRCX Instances

### ISSUE THREAD

**Issue by Hackebein** [vrcx-team/VRCX#720]
**Describe the bug**
2nd instance of VRCX always crashes

**To Reproduce**
1. start 1st VRCX
2. check if webserver port is turned off (otherwise it would fail to start on port conflict)
3. start 2nd VRCX (with `--config` argument)
4. confirm popup to start 2nd instance

**Current behavior**
Hard crash. No further windows, notification or log from this point

**Expected behavior**
2nd VRCX instance to open

**Screenshots**
n/A

**What version you are running**
VRCX Nightly 2024-01-09T10.24-8488a9c

**Logs**
```
2024-01-10 06:45:37.8361 [INFO ] VRCX                 - VRCX Nightly 2024-01-09T10.24-8488a9c
 Starting... 
2024-01-10 06:45:37.8594 [DEBUG] VRCX.ProcessMonitor  - Added process vrchat to process monitor. 
2024-01-10 06:45:37.8594 [DEBUG] VRCX.ProcessMonitor  - Added process vrserver to process monitor. 
2024-01-10 06:45:38.5289 [INFO ] VRCX.WorldDBManager  - World database is disabled. Not starting.
```

**Comment by Natsumi-sama** [comment]
The issue may lie with CefSharp rather than Cef itself, if you can find the exact nightly version it broke on that would be helpful for narrowing it down.

For the time being having multiple installs of VRCX with the `--config` launch parameter will work for running multiple instances of VRCX.
I've removed the dialog asking to run a second instance to prevent confusion.

**Comment by Hackebein** [comment]
Last working stable version: 20231106

### not working stable builds
20230918: doesn't creates sqlite file
20231106: doesn't creates sqlite file
20231224: creates sqlite file

**Comment by Hackebein** [comment]
Last working Nightly version: 2023-08-20T06.44-96f7567
First not working Nightly version: 2023-09-03T22.46-f8ff798

> chore(.NET): update to Cef 116.0.150

**Comment by EinDev** [comment]
This seems to be requiring a folder, which it didn't before. This is a breaking change, can you please add that to the release notes?

**Comment by Hackebein** [comment]
> This seems to be requiring a folder, which it didn't before. This is a breaking change, can you please add that to the release notes?

This is a different change and is not related to this bug

**Comment by TayouVR** [comment]
> This seems to be requiring a folder, which it didn't before. This is a breaking change, can you please add that to the release notes?

this is noted in here: [VRCX Discord #nightly-updates](https://discord.com/channels/854071236363550763/999950540987445268/1207144040475140106)
![image](https://github.com/vrcx-team/VRCX/assets/31988415/4b91fb5b-582c-4150-88c8-3d646acbda1c)
