### ISSUE TITLE
All tabs show "No data"

### ISSUE THREAD

**Issue by VRtualv01d** [vrcx-team/VRCX#722]
**Describe the bug**
When opening VRCX the feed, game log, player list friend log, tabs show 'No data'. 
No errors are displayed when logging in, user is in VRC and in a populated instance.

**Comment by Natsumi-sama** [comment]
Can you check your console for any errors with `Ctrl + Shift + I` is this a new or old VRCX install?

**Comment by VRtualv01d** [comment]
New VRCX install 

console shows:

Uncaught (in promise) TypeError: e.changeAppLanguage is not a function 
at app.js:28876:32 
at Array.forEach (<anonymous>) at app.js:28873:35 
at async app.js:28859:29

**Comment by Natsumi-sama** [comment]
Hmm if that's the only error then maybe VRCX is failing to read your VRChat gameLog file in `%UserProfile%\AppData\LocalLow\VRChat\VRChat` if log files aren't being generated in this folder try delete it.
