### ISSUE TITLE
Unable to run under Wine

### ISSUE THREAD

**Issue by i0ntempest** [vrcx-team/VRCX#730]
**Describe the bug**
VRCX cannot be run under wine in macOS. I've tried two different configurations, one with Wineskin and another one with Whisky (https://getwhisky.app). Both gives the same result.

**To Reproduce**
1. Create a new wrapper/bottle (different words for WINEPREFIX in different apps)
2. Get winetricks: `vcrun2015 vcrun2022 dotnet472`
3. Install VRCX 20231106 (the one before the switch to dotnet 8)
4. Attempt to launch (with and without arg `-no-cef-sandbox`)
5. See error
![image](https://github.com/vrcx-team/VRCX/assets/16017904/272014c0-40f3-4d9d-b165-e3856bd529ef)

**Expected behavior**
It runs

**What version you are running**
Version 20231106

**Comment by i0ntempest** [comment]
> [galister/VRCX/releases/latest](https://github.com/galister/VRCX/releases/latest)

Thanks. There's currently no way to get Wine 9 on macOS afaik (except manualy building it I guess) but I went ahead and tried with 8 anyway - it hangs after launch without doing anything, no windows, no icons popping up. Expected?

**Comment by Natsumi-sama** [comment]
Try the last version before .NET 8
https://github.com/vrcx-team/VRCX/actions/runs/6847602855

**Comment by i0ntempest** [comment]
Getting this:
![image](https://github.com/vrcx-team/VRCX/assets/16017904/518b6dd9-6c63-4782-a985-964993341133)
Do I need to install runtime packages?

**Comment by Myrkie** [comment]
might be a good idea to also add a killswitch for IPC like with pwi kinda pointless on linux.

**Comment by PablosCorner** [comment]
I notice installing it with Wine 9 installed, it does open without any error boxes, but when the window opens it, it's just a white screen with nothing else happening on it. With the dev builds of Wine (9.3 as of this writing), it actually crashes the system and logs out of my current session. Very interesting results for sure.

**Comment by regalialong** [comment]
@PablosCorner You may have not had corefonts in your bottle, I had a fork with a fix needing winetricks which got pushed up to the main repo under https://github.com/vrcx-team/VRCX/tree/master/Linux, see if that helps.
