### ISSUE TITLE
[Feature Request] Search in Local Favourite

### ISSUE THREAD

**Issue by LIII-Works** [vrcx-team/VRCX#735]
### **Explain in detail what your suggested feature would be used for.**

This feature will be used to search world(s) storage in local favourite groups by `World Name` or `Creator Name`

### **Describe how it would look if it requires a UI.**

> Add a search box in the favourite tab, same as the search for the online world and users

or

> Use search tab but add a tickbox for local search

### **Explain why people would want to use it.**

There are sometimes we need to search for a specific word we have favourited before without fully remembering its name, searching with keywords in all VRChat worlds usually results in being overwhelmed by unwanted worlds with similar names.

**Comment by GenesisAria** [comment]
Definitely would be nice.  I find myself losing track of my favourites a lot.  I know it's somewhere but no idea where haha.
