### ISSUE TITLE
invite users group

### ISSUE THREAD

**Issue by poke000000000** [vrcx-team/VRCX#737]
add the ability to inv users that are in your game to group with out them being added 

this would be helpful for people trying to grow there groups.

**Comment by OctoFloofy** [comment]
Wouldn't that just promote spam inviting people?

**Comment by poke000000000** [comment]
no cuz rate limited is a thing. but there could be a cool down or something to stop the spam of invites

**Comment by quazi00** [comment]
yes please add this

**Comment by Natsumi-sama** [comment]
This can be done already from the user dialog, as for bulk inviting users in your current instance this isn't planned.
