### ISSUE TITLE
[Feature Request] Show Headset Battery in VR Overlay device list

### ISSUE THREAD

**Issue by konsti219** [vrcx-team/VRCX#741]
Virtual Desktop started transmitting headset battery information to SteamVR since the recent 1.30.3 Beta. I think it would be useful if the headset battery was shown alongside the battery charge for controllers and trackers.

UI: If the user is wearing a headset with a battery, then an extra item with a headset icon would be shown in the overlay VR devices section.

This would be very useful when playing wirelessly for quickly checking your headset battery.

I am interested in doing the implementation for this if I can get some help with finding the required icons.

**Comment by Myrkie** [comment]
> I am interested in doing the implementation for this if I can get some help with finding the required icons.

most of the icons are yoinked from the steamvr folder `C:\Program Files (x86)\Steam\steamapps\common\SteamVR\resources\icons`

`C:\Program Files (x86)\Steam\steamapps\common\SteamVR\drivers\{device}\resources\icons`

oculus related icons are locates at
`C:\Program Files (x86)\Steam\steamapps\common\SteamVR\drivers\oculus\resources\icons`
