### ISSUE TITLE
[Feature Request] mobile version of the app

### ISSUE THREAD

**Issue by NightseaVR** [vrcx-team/VRCX#747]
Pretty much the same app but for people that are unable to use a computer, for mobile, or lets say u cant go to Ur pc to check something, a phone version will be very useful ik vrchat has now aobilr version but likenthe normal pc version it doesn't give that much detail like vrcx! That's why I believe a mobile version would be neat!

**Comment by Natsumi-sama** [comment]
Someone else is actively working on a mobile app, you can check it out here https://github.com/Nyabsi/VRCAA
