### ISSUE TITLE
[Feature Request] Add notification information for invites

### ISSUE THREAD

**Issue by Luois45** [vrcx-team/VRCX#757]
It would show details like where you got invited to so that you could launch into the world directly or just as additional information.

It could be implemented so that the message field of the notification just shows the world+instance.

People would use it for example when not yet starting into VRChat but requesting an invite and just starting VRChat if they get invited.

**Comment by MingyuNinja** [comment]
Dooray! 메일 발송 실패 안내



  
  
    
    
  
  
    
메일 발송
실패 안내
    
  
  
    
        
          
***@***.***) 
          님께
보낸
메일이
전송되지
못하였습니다.
        
        
          실패 사유를 확인해보세요.
        
    
  
  
    
      
        
          
            * 받는 사람 : 
***@***.***) 
          
          
            * 발송 시간 : 
2024-03-29T00:02:31
          
          
            * 메일 제목 : 
[vrcx-team/VRCX] [Feature Request] Add notification information for invites (Issue #757)
          
          
            
              
                * 실패 사유 : 
              
              
                
대외비/기밀 메일은 외부 계정으로 발송이 제한되어 일부 메일 발송 실패(수신자가 전달 설정한 경우 포함)
                
              
            
                      
          
        
      
    
  
  
    
        
          이 메일은 발신전용으로 회신되지 않습니다.
          더 궁금하신 사항은
          ***@***.***
          으로 문의해 주시기 바랍니다.
        
    
  
  
    
        © Dooray!.

**Comment by Natsumi-sama** [comment]
It is possible by hovering over or clicking on the "invite" text in the "Type" column, yes the UX is bad, it is what it is.

**Comment by MingyuNinja** [comment]
Dooray! 메일 발송 실패 안내



  
  
    
    
  
  
    
메일 발송
실패 안내
    
  
  
    
        
          
***@***.***) 
          님께
보낸
메일이
전송되지
못하였습니다.
        
        
          실패 사유를 확인해보세요.
        
    
  
  
    
      
        
          
            * 받는 사람 : 
***@***.***) 
          
          
            * 발송 시간 : 
2024-03-29T00:08:12
          
          
            * 메일 제목 : 
Re: [vrcx-team/VRCX] [Feature Request] Add notification information for invites (Issue #757)
          
          
            
              
                * 실패 사유 : 
              
              
                
대외비/기밀 메일은 외부 계정으로 발송이 제한되어 일부 메일 발송 실패(수신자가 전달 설정한 경우 포함)
                
              
            
                      
          
        
      
    
  
  
    
        
          이 메일은 발신전용으로 회신되지 않습니다.
          더 궁금하신 사항은
          ***@***.***
          으로 문의해 주시기 바랍니다.
        
    
  
  
    
        © Dooray!.

**Comment by Luois45** [comment]
> It is possible by hovering over or clicking on the "invite" text in the "Type" column, yes the UX is bad, it is what it is.

Thanks but the UX isn't user friendly

**Comment by MingyuNinja** [comment]
Dooray! 메일 발송 실패 안내



  
  
    
    
  
  
    
메일 발송
실패 안내
    
  
  
    
        
          
***@***.***) 
          님께
보낸
메일이
전송되지
못하였습니다.
        
        
          실패 사유를 확인해보세요.
        
    
  
  
    
      
        
          
            * 받는 사람 : 
***@***.***) 
          
          
            * 발송 시간 : 
2024-03-29T00:23:08
          
          
            * 메일 제목 : 
Re: [vrcx-team/VRCX] [Feature Request] Add notification information for invites (Issue #757)
          
          
            
              
                * 실패 사유 : 
              
              
                
대외비/기밀 메일은 외부 계정으로 발송이 제한되어 일부 메일 발송 실패(수신자가 전달 설정한 경우 포함)
                
              
            
                      
          
        
      
    
  
  
    
        
          이 메일은 발신전용으로 회신되지 않습니다.
          더 궁금하신 사항은
          ***@***.***
          으로 문의해 주시기 바랍니다.
        
    
  
  
    
        © Dooray!.
