### ISSUE TITLE
vrcx won't launch [Bug] 

### ISSUE THREAD

**Issue by Jaycario** [vrcx-team/VRCX#765]
ever since i restarted my PC after a windows update, vrcx just refuses to start. it runs in the task manager, but nothing shows up, not even on the icon tray. i tried reinstalling vrcx, but it didn't work.

2024.03.23

**Comment by Natsumi-sama** [comment]
Check anti virus isn't blocking it
Try latest nightly https://github.com/Natsumi-sama/VRCX/releases/latest
Try backup/rename `%AppData%\VRCX\`
Try downgrade to a older version

**Comment by Jaycario** [comment]
i have an exception set for the antivirus, and even disabled it before launching vrcx

i installed the nightly and it didn't work, i also tried the backup and downgrade and neither of those worked either.

**Comment by Natsumi-sama** [comment]
Not much else to try other than building from source or reinstalling Windows unfortunately.

**Comment by Jaycario** [comment]
what does vrcx run on? maybe something got corrupted and i just need to install over it.

**Comment by Myrkie** [comment]
> what does vrcx run on? maybe something got corrupted and i just need to install over it.

VRCX Runs in dotnet using cef as its renderer

**Comment by Jaycario** [comment]
thank you! somehow i got it to work after re-updating windows, thank you for the help though!
