### ISSUE TITLE
[Bug] 

### ISSUE THREAD

**Issue by Hackebein** [vrcx-team/VRCX#767]
**Describe the bug**
clicking self invite for some instances failing with following error message:
```
400 Bad Request
"'ArcticLucky_AI~group（grp_7c75c192-e00e-4ac8-a14b-95bcbfa8429b）~groupAccessType（public）~region（us）' is not a valid instanceId"
"invite/myself/to/wrld_6caf5200-70e1-46c2-b043-e3c4abe69e0f:ArcticLucky_AI~group(grp_7c75c192-e00e-4ac8-a14b-95bcbfa8429b)~groupAccessType(public)~region(us)"
```

**To Reproduce**
1. Go to instance `wrld_6caf5200-70e1-46c2-b043-e3c4abe69e0f:ArcticLucky_AI~group(grp_7c75c192-e00e-4ac8-a14b-95bcbfa8429b)~groupAccessType(public)~region(us)`
2. Click on "Invite yourself"
3. See error

**Expected behavior**
Confirmation message of send out self invite

**Screenshots**

**What version you are running**
VRCX Nightly 2024-03-22T21.55-05ffb0c

**Comment by Nekromateion** [comment]
Not a VRCX bug, this is a VRChat API bug.
Please report at https://feedback.vrchat.com/

**Comment by Hackebein** [comment]
@Nekromateion any details?

**Comment by DavidLeBonk** [comment]
Well they did just say that this issue is on VRChats side and can't be resolved by VRCX. Best you can do is make a report on the site they linked, post the link to the report here and other people having the issue can bump it so it gets pushed as a higher priority to fix.

**Comment by Hackebein** [comment]
@DavidLeBonk I understand what they asked me. I asked for details. For example which API endpoints getting used? How are requests designed? Or has anybody reported this before already? (At least with <5 minutes reaction time a wild guess)

**Comment by Nekromateion** [comment]
@Hackebein 
The same issue is present when you try to [use the VRChat website](https://vrchat.com/home/launch?worldId=wrld_6caf5200-70e1-46c2-b043-e3c4abe69e0f&instanceId=ArcticLucky_AI~group(grp_7c75c192-e00e-4ac8-a14b-95bcbfa8429b)~groupAccessType(public)~region(us)) to invite yourself to the instance.
The API request fails and returns a 400 error, but the website doesn't handle this and simply displays the checkmark regardless.
The endpoint that is used is already in your original message so I figured you'd know.

`/api/1/invite/myself/to/{WorldIdWithInstanceId}`

The endpoint attempts to validate the InstanceID but that filter only checks for alphanumerical and the _ causes it to mark the InstanceID as invalid.
If you plan to report this please mention all of those things as it required some testing (and wasted time) on my end to figure out what specifically was causing it.

**Comment by Hackebein** [comment]
> The endpoint that is used is already in your original message so I figured you'd know.

Somehow thought the instance id we get would be wrong and validation would just be right. Didn't realized that i'm directly looking at the real issue. Thanks for clearification.

I reported it: https://feedback.vrchat.com/website/p/cant-invite-myself-to-a-public-instance
