### ISSUE TITLE
[Feature Request] Option to Hide/Disable unfriend logging

### ISSUE THREAD

**Issue by Dusty-Sprinkles** [vrcx-team/VRCX#776]
**Explain in detail what your suggested feature would be used for.**
I would like a toggle to make vrcx not log/automatically delete unfriend logs generated in the app

**Describe how it would look if it requires a UI.**
Checkbox in settings 

**Explain why people would want to use it.**
Personally I don't really want to know who unfriends me and having the information is more of a mental sink than it is useful, the only friends I'm interested in hearing about are the reliable ones anyhow.

Also I don't consider filtering to be a suitable alternative as the information is still there and will still mark my friend log as unread when it happens

**Comment by Myrkie** [comment]
as far as im aware VRCX Doesnt delete this information and its saved in the SQLite DB located at `%APPDATA%\VRCX`
`VRCX.sqlite3` you can browse this with [sqlite db browser](https://sqlitebrowser.org/), and if the database gets corrupted or isn't properly transferred when reinstalling windows or moving pc this data will be lost

all friend information is stored in a table named after your userid_friend_log_history

**Comment by Dusty-Sprinkles** [comment]
I personally don't think its that niche, and I feel a lot of people would appreciate not having such negative information forced on them in the app. Some of us just like to use it to find out when our friends come online.

Also github isn't giving me an option to not close on the dropdown so im just going to ignore that but pls reopen if it gets closed

**Comment by Natsumi-sama** [comment]
I've made the notification dot respect the notification table filters, hopefully that's enough because any other changes likely wouldn't be worth the dev time and could cause bugs.

**Comment by Dusty-Sprinkles** [comment]
I think its a decent enough work around for now, though it might be worth leaving the issue open in case other users want to express interest in case it gets to the point where enough people openly care for the dev time to be worth fixing whatever is blocking the issue and complete implementation.

**Comment by KelseyHigham** [comment]
personally i've chosen not to use VRCX because i don't wanna ever know about unfriending

**Comment by loukylor** [comment]
guys my account has reached the age where every time i see a friend log dot i just think "who unfriended me this time :sob:" i totally understand i will implement this lmfao
