### ISSUE TITLE
[Feature Request] Define custom perf ranks based on the server side provided avatar stats (and automations based on them (hide avatars))

### ISSUE THREAD

**Issue by TayouVR** [vrcx-team/VRCX#786]
**Explain in detail what your suggested feature would be used for.**
It would allow you to define when an avatar is performing badly and mark it as such.
It would be also great if you could automatically hide any avatars that exceed certain user defined limits (e.g. vram) (this may not be possible immediately in game as the game probably doesn't update that information from external changes until the avatar is reloaded) 

**Describe how it would look if it requires a UI.**
Grid Layout with rows for each measured stat, columns for ranks. (there could be e.g. 4 pre-defined at the start, or it could be dynamic)
each field then has a input field allowing the user to configure the maximum value that the avatar is allowed to have for that rank

**Explain why people would want to use it.**
it would give quick and easy information on how avatars perform.
If the automations are integrated each rank would have a "action" selection defining what should be done with a avatar in that rank, allowing you to automatically hide badly performing avatars.
The advantage of using this over VRChats built in systems would be, that you can adjust what should be hidden and what not based on your hardware and pain tolerance. (low FPS)

**Comment by Natsumi-sama** [comment]
You can only fetch avatar stats when you have the assetUrl for that avatar making this not possible. IIRC externally edited avatar show/hides only update after a game restart defeating the purpose a bit, this should really be implemented by VRChat not VRCX.

**Comment by TayouVR** [comment]
I agree, it should be, but as far as i understand VRCX can get all avatars in the current lobby with API logging levels and could at least rank them in the UI, for the user to see.

~~Though I wouldn't want to implement it either...~~
