### ISSUE TITLE
[Bug] After Upgrade to v2024.05.09, VRCX launches VRCX_Setup.exe and closes

### ISSUE THREAD

**Issue by tschaerni** [vrcx-team/VRCX#787]
**Describe the bug**
Basically the Title. After upgrading to v2024.05.09 everytime I try to launch VRCX.exe, it instead launches VRCX_Setup.exe, does something for a bit, opens up the VRCX window, and closes it after 1-2s again.

**To Reproduce**
I don't know how to produce it on other systems, but on mine I just try to launch VRCX.exe

**Expected behavior**
Launching VRCX as expected

**Screenshots**
No screenshot, but a pretty much empty logfile which it produces.

**What version you are running**
Version v2024.05.09

[VRCX.log](https://github.com/vrcx-team/VRCX/files/15316098/VRCX.log)

PS: I tried reinstalling, but the behaviour is the same.

**Comment by Natsumi-sama** [comment]
I had named the update incorrectly, try again now it should be fixed.

**Comment by tschaerni** [comment]
> I had named the update incorrectly, try again now it should be fixed.

Seems fixed. Thanks for the quick fix, and also thanks for the awesome work you and the rest of the team does ❤️
