### ISSUE TITLE
steamvr wrist overlay not working

### ISSUE THREAD

**Issue by Invaliduser81** [vrcx-team/VRCX#794]
**Describe the bug**
When using the steamvr overlay feature it wont work properly, to put it simply when I toggle it on now nothing happens and in the steamvr menu, in the bottom area with all the other apps and stuff vrcx will flicker off and on like its closing and launching but the icon is invisible.

**To Reproduce**
1. Go to settings
2. Wrist overlay
3. Toggle steamvr overlay
4. Open steamvr menu
5. Look at steamvr taskbar
6. notice flickering app

**Expected behavior**
I would normally expect the feature to work normally and the wrist feed to show, not sure what else to say

**Screenshots**
Sadly I cant provide any screenshots right now but maybe later but heres my settings
![image](https://github.com/vrcx-team/VRCX/assets/95740910/96d4babe-12a8-4a18-b3da-cf067c4b8687)
![image](https://github.com/vrcx-team/VRCX/assets/95740910/23721ff5-5304-4adc-9ea6-360ae12c0e28)

**What version you are running**
Vrcx 2024.05.09

**Comment by Provini** [comment]
"SteamVR Overlay" is the "Master" toggle for each section. Turn it on for the Wrist Overlay.

**Comment by Provini** [comment]
This issue I've heard has been strange and wouldn't be the first time this happened. I'm not sure if we know a proper resolution but 
I will ask some things to start us off:
- Has the wrist feed overlay ever worked for you? If so, when exactly did it stop working?
- What happens if you set  "Start Overlay With" to SteamVR. (Maybe game detection is going wrong?)
- Are your graphics drivers up to date? Update and restart if not.

**Comment by Natsumi-sama** [comment]
Sending us these log files should help us find the cause
`C:\Program Files (x86)\Steam\logs\vrclient_VRCX.txt`
`%AppData%\VRCX\logs\VRCX.log`

**Comment by Invaliduser81** [comment]
> This issue I've heard has been strange and wouldn't be the first time this happened. I'm not sure if we know a proper resolution but I will ask some things to start us off:
> 
> * Has the wrist feed overlay ever worked for you? If so, when exactly did it stop working?
> * What happens if you set  "Start Overlay With" to SteamVR. (Maybe game detection is going wrong?)
> * Are your graphics drivers up to date? Update and restart if not.

Yeah it worked for me in the past plenty of times but I dont think i can pinpoint when it stopped working, I likely didnt notice until recently but best date I can give is around the latest update

No my graphics arent up to date and ill be doing that rn
[vrclient_VRCX.txt](https://github.com/vrcx-team/VRCX/files/15367204/vrclient_VRCX.txt)


setting it to start with steamvr didnt do much of anything either

**Comment by Invaliduser81** [comment]
> This issue I've heard has been strange and wouldn't be the first time this happened. I'm not sure if we know a proper resolution but I will ask some things to start us off:
> 
> * Has the wrist feed overlay ever worked for you? If so, when exactly did it stop working?
> * What happens if you set  "Start Overlay With" to SteamVR. (Maybe game detection is going wrong?)
> * Are your graphics drivers up to date? Update and restart if not.

Apprently an outdated graphics driver was the issue? I dont really understand why that would be the issue unless in the process I did something else and forgot but thanks for the suggestions.
