### ISSUE TITLE
[Bug] Favorite Friends are not grouped on startup if custom groups are selected

### ISSUE THREAD

**Issue by jan-Sanku** [vrcx-team/VRCX#796]
**Describe the bug**
when starting VRCX with custom favorite friend groups selected, no favorite friends will be listed in the favorites category of your friends list

**To Reproduce**
1. select a group of favorite friends that has online users under "Favorite Friends" in General Settings. you should see your friends in the "Favorites" category in the friends list, as expected
2. restart VRCX
3. the online favorite friends of that group will now be listed under "Online", not "Favorites"
4. to fix, change anything in the "Favorite Friends" setting. selecting and/or unselecting any group makes all friends update to their proper category, even if the group you select is empty. basically, any kind of update to this setting will refresh the categories

**Expected behavior**
the "Favorites" category should always correctly show friends that are in a groups you selected, if any

**Screenshots**
current settings
![image](https://github.com/vrcx-team/VRCX/assets/56739341/6c9f1b9d-28cb-4d66-ab27-e1735fed119f)

expected behavior
![image](https://github.com/vrcx-team/VRCX/assets/56739341/a511b42c-a169-4575-bdbd-71fc0de801c4)

behavior after startup (note that the 2 favorites are accounted for in the online user count)
![image](https://github.com/vrcx-team/VRCX/assets/56739341/2e03b0c6-8a4c-40b6-8809-358646d27241)

**What version you are running**
Version 2024.05.09

**Comment by zkxs** [comment]
I'm not certain if it's the same or a different bug, but I have another reproduction that doesn't require restarting VRCX:

1. select any (or all) friend groups in the settings
2. In the Favorites tab, press the "Refresh all favorites" button
3. Observe that the Favorites category in the friends list has disappeared

**Comment by Natsumi-sama** [comment]
Yea I'm pretty sure that's the same bug, execution order loading favorites after friends list, should be fixed in next nightly build let me know how it goes once it's released.

**Comment by Natsumi-sama** [comment]
Nightly has been updated with a fix, let me know how it goes.
