### ISSUE TITLE
[Bug] Extremely slow launching for VRCX

### ISSUE THREAD

**Issue by JackRyker** [vrcx-team/VRCX#807]
**Describe the bug**
When launching VRCX it is extremely slow. It launches after just over 2 minutes (timed it). It barely uses any resources during this time and sits idle in task manager. It used to launch quickly before and suddenly started doing this a while ago.

The app itself works perfectly fine and does everything I expect it to.

**To Reproduce**
1. Launch VRCX

**Expected behavior**
To not take 2 minutes to launch.

**What version you are running**
VRCX 2024.05.09

Side note: I tried clean uninstalling the program and deleting ALL data (files and reg entries) then grabbing a fresh copy to no avail.

**Comment by Natsumi-sama** [comment]
Give the latest nightly build a try it should be fixed now.

**Comment by JackRyker** [comment]
I had recently reset my computer a week or so after I made this post, so I'm unable to test to see if its fixed. But it loads normally again after computer reset.

**Comment by Natsumi-sama** [comment]
Classic Windows reinstall, it fixes all.
