### ISSUE TITLE
[Bug] XSOverlay notifications not being pushed

### ISSUE THREAD

**Issue by throwaway345789** [vrcx-team/VRCX#811]
**Describe the bug**
Notifications aren't being shown on XSOverlay unless manually pushed via devtools
`AppApi.XSNotification("VRCX", "test", 5, "");`

**To Reproduce**
1. Reset VRCX by removing all files in appdata
2. Set Notifications > Notification Filter to Everyone/On

**Expected behavior**
XSOverlay notifications to function correctly

**What version you are running**
VRCX 2024.05.09
XSOverlay Build 667

**Comment by Natsumi-sama** [comment]
Is your in-game status set to busy?
