### ISSUE TITLE
[Bug] Wrong Country Flag Used On Language

### ISSUE THREAD

**Issue by ShanaNyaa** [vrcx-team/VRCX#816]
**Describe the bug**
Language "Bahasa Melayu" (known as msa in VRC) is using Indonesian flag.

**To Reproduce**
1. Add Bahasa Melayu language to your bio or find a friend that use Bahasa Melayu as their language in their bio
2. Observe the flag used

**Expected behavior**
It should show Malaysia flag.

**Screenshots**
![image](https://github.com/vrcx-team/VRCX/assets/26851070/3ea893b2-bc3d-4756-b349-2171c8e2406d)

**What version you are running**
Version 2024.05.09

**Extra detail**
I saw that in the code html/src/app.js under variable "LanguageMappings" both Bahasa Melayu and Bahasa Indonesia is using "id". I do not know how the code works but perhaps using "my" for Bahasa Melayu is the fix for this.

**Comment by Natsumi-sama** [comment]
@hyblocker can you give this a look if you have the time.
