### ISSUE TITLE
[Feature Request] Network proxy setting

### ISSUE THREAD

**Issue by BAKAOLC** [vrcx-team/VRCX#818]
I hope to have an interface to set the proxy used by network requests initiated by VRCX.

Because in some areas, we sometimes encounter network pollution and other problems that require the use of network proxies to access.
However, VRCX currently does not support setting network proxies, and if you use software like SocksCap, the software will not be able to access the network.
Therefore, you can only use a global network proxy solution (at least I haven't found any other solution yet), but it will bring more other usage problems, such as the need to filter traffic such as VRChat to avoid affecting the normal play of the game.

If you decide to make this function, this function requires an interface with the following content:
Two input boxes can be set respectively: target proxy server address, target proxy server port
A button can be used to test the proxy server connection
If possible, HTTP/Socks5 proxy servers can be supported, so you need to add an additional checkbox to choose whether to use HTTP proxy or Socks5 proxy

**Comment by Natsumi-sama** [comment]
I believe [Proxifier](https://www.proxifier.com/) will work well for this use case.

**Comment by yuyang233** [comment]
Yes, I agree with that.
vrchat's api has been seriously contaminated with dns recently and requests to add proxy options
we need HTTP proxy options or Socks5 proxy options

**Comment by BAKAOLC** [comment]
> I believe [Proxifier](https://www.proxifier.com/) will work well for this use case.

I tried Proxifier today, and it can indeed proxy the traffic of VRCX.exe without directly blocking the work, but when it is running, my VRChat will be blocked from connecting and cannot work through software such as network accelerators. As a user in a polluted area, this is unacceptable.
This may be caused by my ignorance of the settings or other reasons. But for now, I can only choose not to use VRCX for the time being.

**Comment by NAOLIU** [comment]
> > I believe [Proxifier](https://www.proxifier.com/) will work well for this use case.
> 
> I tried Proxifier today, and it can indeed proxy the traffic of VRCX.exe without directly blocking the work, but when it is running, my VRChat will be blocked from connecting and cannot work through software such as network accelerators. As a user in a polluted area, this is unacceptable. This may be caused by my ignorance of the settings or other reasons. But for now, I can only choose not to use VRCX for the time being.

我现在用Netch根据进程代理VRCX倒是可用
https://github.com/netchx/netch
跟加速器之类的不冲突，在netch里面导入你的梯子之类的，然后扫描VRCX的进程
![image](https://github.com/vrcx-team/VRCX/assets/55797625/9f06d294-8206-48ce-8c25-6b0c1e774584)
但需要每次启动VRCX之前先打开Netch并启用，非常麻烦，还是希望官方能出一个端口代理之类的

Google Translate for others:
I use Netch to proxy VRCX according to the process. It works.
https://github.com/netchx/netch
It does not conflict with accelerators. Import your ladder in netch and scan the VRCX process.
![image](https://github.com/vrcx-team/VRCX/assets/55797625/9f06d294-8206-48ce-8c25-6b0c1e774584)
But you need to open Netch and enable it before starting VRCX every time. It is very troublesome. I still hope that the official can release a port proxy or something like that.

**Comment by NAOLIU** [comment]
> I believe [Proxifier](https://www.proxifier.com/) will work well for this use case.

May I ask if the VRCX development team has made a statement on this issue?

**Comment by Natsumi-sama** [comment]
Please try latest nightly build.

**Comment by BAKAOLC** [comment]
> Please try latest nightly build.

Thanks for your work, I have just tried compiling the latest code. It seems to be working fine.

If I find new issues, I will report back immediately.
