### ISSUE TITLE
[Bug] Urgent need for network proxy function through port

### ISSUE THREAD

**Issue by NAOLIU** [vrcx-team/VRCX#823]
![测试1](https://github.com/vrcx-team/VRCX/assets/55797625/bf0c25db-deab-45de-a134-e999634b421e)
Unable to connect to api.vrchat.cloud .This almost renders the software unusable.

Due to DNS pollution and blocking of some Cloudflare servers, it is no longer possible to connect to the only two server IPs of this API.

![image](https://github.com/vrcx-team/VRCX/assets/55797625/c9eac4a5-d2b0-48ac-bc09-f342908a4fe9)

We hope to be able to implement the function of network proxy based on ports to cope with complex network situations in multiple regions.

Version [VRCX 2024.06.12]

**Comment by Natsumi-sama** [comment]
Duplicate https://github.com/vrcx-team/VRCX/issues/818#issuecomment-2174002250
