### ISSUE TITLE
[Bug] WebSocket error

### ISSUE THREAD

**Issue by MaribelHearm** [vrcx-team/VRCX#830]
I get WebSocket error error when I use vpn, I added the rule but it still reports error, I remember someone asked this question before but I can't find it, it's to add a rule about websocket

**Comment by Provini** [comment]
WebSocket error is usually an error on VRChat's end I believe though I could be wrong. Does VRChat run fine with a VPN for you? All images and things load fine in-game without issue?

**Comment by MaribelHearm** [comment]
Yes, the vpn is loading fine in the game, but this error is always a pain in the ass

**Comment by Natsumi-sama** [comment]
Is VRCX and your VPN software fully up-to-date?

**Comment by MaribelHearm** [comment]
> VRCX 和您的 VPN 软件是否完全是最新的？
Yes, it's all up to date.
