### ISSUE TITLE
[Bug] Unable to log in

### ISSUE THREAD

**Issue by fsguoguo** [vrcx-team/VRCX#832]
When I enter the two-factor authentication code, I can't log in. The prompt window for entering the verification code pops up again, asking me to input the code, and this keeps repeating in a loop.

**Comment by Natsumi-sama** [comment]
Make sure VRCX is fully up-to-date, remove your saved account (this wont remove your data) then try login again.

**Comment by Natsumi-sama** [comment]
Try open a incognito window in your web browser and try login to the VRChat website there just to be 100% sure it's a VRCX related issue.
Otherwise press `Ctrl + Shift + I` in VRCX and select the console and send a screenshot of any error here.

**Comment by fsguoguo** [comment]
I successfully logged into the VRChat website on a new device, but I still failed in VRCX. Here is the screenshot of the error.
![屏幕截图 2024-06-25 190612](https://github.com/vrcx-team/VRCX/assets/53118184/6849cff5-12fe-4106-9a48-b185af4ec6ca)

**Comment by fsguoguo** [comment]
![屏幕截图 2024-06-25 191154](https://github.com/vrcx-team/VRCX/assets/53118184/b1d82e15-093b-4a7c-87a4-7ec4904ba93c)

**Comment by Natsumi-sama** [comment]
That's *very* odd and might be something on VRChats end, I'm not entirely sure though, could be related to the other issues Chinese people have been having with VPNs if you're from there.
I'll think about it a bit more but I've never seen this one before.

**Comment by Natsumi-sama** [comment]
Wait no I'm blind it's returning an error can you click on that to expand it?

**Comment by fsguoguo** [comment]
Which link shoud I click? Is it app.js:489:27 ?

**Comment by fsguoguo** [comment]
![屏幕截图 2024-06-25 195553](https://github.com/vrcx-team/VRCX/assets/53118184/70e8feb5-225d-4501-a4c5-a9f9029a0c31)

**Comment by Natsumi-sama** [comment]
Click here
![a](https://github.com/vrcx-team/VRCX/assets/11171153/d52d2fd7-c70b-40c7-9a23-b98f0c3f7dde)

**Comment by fsguoguo** [comment]
![屏幕截图 2024-06-25 200048](https://github.com/vrcx-team/VRCX/assets/53118184/4b5c7039-45f0-4710-9f51-1d5f36fd4a3d)

**Comment by fsguoguo** [comment]
![屏幕截图 2024-06-25 203553](https://github.com/vrcx-team/VRCX/assets/53118184/44b283f0-494c-4ba7-9990-5f02dafffc2b)
Doesn't look like they expired, does it?

**Comment by Natsumi-sama** [comment]
Looks correct to me, damn I'm back to being clueless as to what is going on there.
