### ISSUE TITLE
[Bug] Screenshot Metadata Drag and drop not working as intended 

### ISSUE THREAD

**Issue by khalifa9199** [vrcx-team/VRCX#842]
**Describe the bug**
Screenshot Metadata Drag and drop not working as intended, when dragging a photo it will end up in a a blank state showing nothing, however if you open the photo through browse it will work as intended.

**To Reproduce**
1. Go to settings
2. Click on Advanced
3. Click on Screenshot Metadata
4. Drag a VRC photo into the app
5. The app will turn black as no photo was dragged there 

**Expected behavior**
Dragging a photo into the Screenshot Metadata Drag and drop will show the IMG and the related metadata 

**Screenshots**
![VRCX_noBlBx6nkw](https://github.com/user-attachments/assets/1f777405-d378-4e04-b271-63f76e0d3905)

**What version you are running**
The bug showed in the last 3 versions 
1. v2024.06.12
2. v2024.05.09
3. v2024.03.23

(The functionality was working on an older version but I cant remember which)

**Comment by TayouVR** [comment]
I can confirm this, it hasn't worked in a handful of months

**Comment by Nekromateion** [comment]
Confirmed the bug myself too.
From what I can tell the issue seems to be that `filePath` in `$app.methods.dragEnterCef` does not provide the full path but only the file name.
