### ISSUE TITLE
[Bug] Launch Options

### ISSUE THREAD

**Issue by mathi14811** [vrcx-team/VRCX#847]
**Describe the bug**
In launch options, we're supposed to be able to change the location of the vrcx sqlite database. I followed the wiki (https://github.com/vrcx-team/VRCX/wiki/Launch-parameters) : added --config="H:\My Drive\VRCX" to the launch options in VRCX advanced settings. I restarted the app and it doesn't work.
**To Reproduce**
Add a line in the launch options in VRCX.

**Expected behavior**
After switching location, VRCX should be on the main log in page, or the files should have been move. 
However, neither happens.

**What version you are running**
VRCX 2024.06.12

**Comment by Natsumi-sama** [comment]
The launch options in advanced settings are for VRC not for VRCX.
You need to either edit the shortcut you use to launch VRCX to add these launch options, or if you're not aiming to run more than one instance of VRCX at a time use the `%AppData%\VRCX\VRCX.json` file instead to specify your custom database location.
