### ISSUE TITLE
[Bug] [Linux] Installer hangs after "Download VRCX"

### ISSUE THREAD

**Issue by CorneliusCornbread** [vrcx-team/VRCX#853]
**Describe the bug**
Had an issue updating, went to reinstall VRCX and it seems like the installer always hangs after downloading VRCX

**To Reproduce**
1. Run installer
2. Wait until download
3. Error

**Expected behavior**
Installer does not hang

**Logs**
```
Download VRCX
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
100  225M  100  225M    0     0  28.5M      0  0:00:07  0:00:07 --:--:-- 28.0M
replace Accessibility.dll? [y]es, [n]o, [A]ll, [N]one, [r]ename: new name: replace ip? [y]es, [n]o, [A]ll, [N]one, [r]ename: error:  invalid response [{ENTER}]
replace ip? [y]es, [n]o, [A]ll, [N]one, [r]ename: error:  invalid response [echo '#!/]
replace ip? [y]es, [n]o, [A]ll, [N]one, [r]ename: error:  invalid response [usr/bin/e]
replace ip? [y]es, [n]o, [A]ll, [N]one, [r]ename: replace Blake2Sharp.dll? [y]es, [n]o, [A]ll, [N]one, [r]ename: error:  invalid response [export WI]
replace Blake2Sharp.dll? [y]es, [n]o, [A]ll, [N]one, [r]ename: %    
```

**What version you are running**
N/A

**Comment by Natsumi-sama** [comment]
Delete this folder then run the installer again `$HOME/.local/share/vrcx/drive_c/vrcx` someone will need to add deleting that folder to the install script.

**Comment by CorneliusCornbread** [comment]
> Delete this folder then run the installer again `$HOME/.local/share/vrcx/drive_c/vrcx` someone will need to add deleting that folder to the install script.

Well that works, but I'm still getting the issue that caused me to originally reinstall. VRCX immediately hangs on a black screen during launch 
![image](https://github.com/user-attachments/assets/1fc64f26-bc3f-432b-8f86-46c23645a4f6)

**Comment by CorneliusCornbread** [comment]
Oddly enough it works via bottles great. Honestly I might just switch back to using bottles and link my VRCX app data folder manually for my bottles install. For anyone who wants the bottles config it's here:
![image](https://github.com/user-attachments/assets/97092d34-483a-4b26-9ed3-04f760e47c0e)

**Comment by TuxTheAstronaut** [comment]
i have same issue too with a black screen 

@CorneliusCornbread  are you using the flatpak version of bottels? maybe the flatpak runtime fixes something

**Comment by CorneliusCornbread** [comment]
> i have same issue too with a black screen
> 
> @CorneliusCornbread are you using the flatpak version of bottels? maybe the flatpak runtime fixes something

I'm using the flatpak version of Bottles yes as it's the recommended method of install by the maintainers of Bottles. It's likely that's the case though I am using the sys-wine9.0 for my compatibility layer. My system is using Wine 9.5 instead of wine 9.0, maybe newer versions of Wine don't play nice?

**Comment by Natsumi-sama** [comment]
It could also be due to the Cef update in latest VRCX release, previous VRCX version might still work fine.

**Comment by CorneliusCornbread** [comment]
> It could also be due to the Cef update in latest VRCX release, previous VRCX version might still work fine.

Yeah can confirm the previous version was working just fine, it was only after I updated I started having issues.

**Comment by TuxTheAstronaut** [comment]
thats what i suspect. the older version works fine while the newest version is a black screen i have to restart the app over and over until it randomly decides to load the UI

**Comment by CorneliusCornbread** [comment]
Okay weird, but I just had an issue where the Bottle was doing the same thing. Seems like it's a really inconsistent bug but happens more often on newer versions of Wine

**Comment by guerryer** [comment]
The script hang because of the unzip command
Line 70 `unzip -uq vrcx.zip`

If you change the -uq for -oq it will overwrite the files WITHOUT prompting

**Comment by Natsumi-sama** [comment]
That was also my first thought as well but I'd rather delete the entire folder to prevent potential future VRCX related issues from arising.

**Comment by regalialong** [comment]
Okay, just woke up.

I was able to reproduce both issues on my end, the installer one should be easily fixable.
I'll side with Natsumi that I'd rather delete the folder (with `set -u` so that we don't pull a Steam, IYKYK :p), that's consistent with the behavior from the real Windows installer if I understand correctly.

For the blackscreen issue, @CorneliusCornbread @TuxTheAstronaut, could you two add `WINEDLLOVERRIDES="libglesv2=d"` to the start of `~/.local/share/vrcx/drive_c/vrcx/vrcx` 3rd line?
Kill your wineservers (`wineserver -k`) to be sure.

If that prevents the blackscreens, which it does on my end, I believe our issue is [this one](https://bugs.winehq.org/show_bug.cgi?id=44985), that's a proposed workaround for that.

**Comment by CorneliusCornbread** [comment]
> Okay, just woke up.
> 
> I was able to reproduce both issues on my end, the installer one should be easily fixable. I'll side with Natsumi that I'd rather delete the folder (with `set -u` so that we don't pull a Steam, IYKYK :p), that's consistent with the behavior from the real Windows installer if I understand correctly.
> 
> For the blackscreen issue, @CorneliusCornbread @TuxTheAstronaut, could you two add `WINEDLLOVERRIDES="libglesv2=d"` to the start of `~/.local/share/vrcx/drive_c/vrcx/vrcx` 3rd line? Kill your wineservers (`wineserver -k`) to be sure.
> 
> If that prevents the blackscreens, which it does on my end, I believe our issue is [this one](https://bugs.winehq.org/show_bug.cgi?id=44985), that's a proposed workaround for that. I'll upstream it if I get a greenlight from you two.

Adding it to the third line causes it to simply crash without saying much
```
05dc:fixme:ntdll:RtlGetCurrentProcessorNumberEx (000000000019D3D0) :semi-stub
05dc:fixme:ntdll:RtlGetCurrentProcessorNumberEx (000000000019D3D0) :semi-stub
05dc:fixme:ntdll:RtlGetCurrentProcessorNumberEx (000000000019D3D0) :semi-stub
05dc:fixme:ntdll:RtlGetCurrentProcessorNumberEx (000000000019D3D0) :semi-stub
05dc:fixme:ntdll:RtlGetCurrentProcessorNumberEx (000000000019D3D0) :semi-stub
05dc:fixme:ntdll:RtlGetCurrentProcessorNumberEx (000000000019D3D0) :semi-stub
05dc:fixme:ntdll:RtlGetCurrentProcessorNumberEx (000000000019D3D0) :semi-stub
05dc:fixme:ntdll:EtwEventSetInformation (deadbeef, 2, 00000001005C15E8, 40) stub
```

However, putting it in front of the execution of the script like so `WINEDLLOVERRIDES="libglesv2=d" ~/.local/share/vrcx/drive_c/vrcx/vrcx` _does_ work.

**Comment by regalialong** [comment]
What does your third line look like? And did you kill the wineserver beforehand? The dead process can still block startup.

**Comment by regalialong** [comment]
Oh wait, I see.
Sure, add `export WINEDLLOVERRIDES="libglesv2="` above `~/.local/share/vrcx/drive_c/vrcx/vrcx` then

**Comment by CorneliusCornbread** [comment]
> Oh wait, I see. Sure, add `export WINEDLLOVERRIDES="libglesv2="` above `~/.local/share/vrcx/drive_c/vrcx/vrcx` then

I'm assuming you meant to add the "d" after the equals `export WINEDLLOVERRIDES="libglesv2="d`

That worked actually. I also also actually had to kill vrcx outside of wineserver via Mission Center, for some reason wineserver wasn't able to deal with it.

There's one problem, it still hangs sometimes, just not with a black screen and instead with the last frame
![image](https://github.com/user-attachments/assets/b295203b-bda2-4d1f-b5b9-73deb16bc132)

**Comment by regalialong** [comment]
Uh, if you resize the window, does it refresh?

**Comment by CorneliusCornbread** [comment]
> Uh, if you resize the window, does it refresh? What's your hardware and DE?

Gimme a sec to reproduce it it's not exactly consistent. In the meantime here's my hardware:
RX 6900 XT
Ryzen 7 5700X3D

or neofetch with a bunch of info
```
                                             ┌──────────────────────Hardware──────────────────────┐
                                             │ ├: AMD Ryzen 7 5700X3D (16) @ 3.00 GHz
                                             │ ├󰍛: AMD Radeon RX 6900 XT [Discrete]
                                             │ ├󰍛: 13.88 GiB / 31.24 GiB (44%)
                .',;::::;,'.                 └ └: 807.60 GiB / 929.93 GiB (87%) - btrfs
            .';:cccccccccccc:;,.             └────────────────────────────────────────────────────┘
         .;cccccccccccccccccccccc;.
       .:cccccccccccccccccccccccccc:.        ┌──────────────────────Software──────────────────────┐
     .;ccccccccccccc;.:dddl:.;ccccccc;.       OS: Fedora Linux 40 (KDE Plasma) x86_64
    .:ccccccccccccc;OWMKOOXMWd;ccccccc:.     │ ├: Linux 6.9.11-200.fc40.x86_64
   .:ccccccccccccc;KMMc;cc;xMMc;ccccccc:.    │ ├: 5013 (5.17)
   ,cccccccccccccc;MMM.;cc;;WW:;cccccccc,    │ ├󰏖: 3891 (rpm), 38 (flatpak)
   :cccccccccccccc;MMM.;cccccccccccccccc:    └ └: zsh 5.9
   :ccccccc;oxOOOo;MMM000k.;cccccccccccc:
   cccccc;0MMKxdd:;MMMkddc.;cccccccccccc;     DE: KDE Plasma 6.1.3
   ccccc;XMO';cccc;MMM.;cccccccccccccccc'    │ ├: sddm 0.21.0 (Wayland)
   ccccc;MMo;ccccc;MMW.;ccccccccccccccc;     │ ├: KWin (Wayland)
   ccccc;0MNc.ccc.xMMd;ccccccccccccccc;      │ ├󰉼: Colorful-Blur-Dark-Aurorae-6
   cccccc;dNMWXXXWM0:;cccccccccccccc:,       └ └: yakuake 24.05.2
   cccccccc;.:odl:.;cccccccccccccc:,.        └────────────────────────────────────────────────────┘
   ccccccccccccccccccccccccccccc:'.
   :ccccccccccccccccccccccc:;,..             ┌────────────────────Uptime / Age / DT────────────────────┐
    ':cccccccccccccccc::;,.                    OS Age : 410 days
                                               Uptime : 34 mins
                                               DateTime : 2024-07-31 18:47:02
                                             └─────────────────────────────────────────────────────────┘
```

**Comment by regalialong** [comment]
I think that fixes the original issue. I'll wait on @TuxTheAstronaut.

For your issue, if you don't mind, [I'd like to drag you into Discord for triage of that](https://discord.gg/B3MEr6BTSS). No promises we'll find anything but still.

**Comment by CorneliusCornbread** [comment]
> I think that fixes the original issue. I'll wait on @TuxTheAstronaut.
> 
> For your issue, if you don't mind, [I'd like to drag you into Discord for triage of that](https://discord.gg/B3MEr6BTSS). No promises we'll find anything but still.

Welp I cannot reproduce it for the life of me, so if it is a problem it's rare enough to not worry about it

**Comment by regalialong** [comment]
fwiw it feels like hw accel dying, maybe add `-disable-gpu` to `~/.local/share/vrcx/drive_c/vrcx/vrcx` if it happens again and see if that helps.
God knows with CEF.

**Comment by TuxTheAstronaut** [comment]
@regalialong i tried using the `-disable-gpu` in the bash script but its still a black screen

**Comment by regalialong** [comment]
Replace the contents `~/.local/share/vrcx/drive_c/vrcx/vrcx` with this:
```bash
#!/usr/bin/env bash
export WINEPREFIX=$HOME/.local/share/vrcx
export WINEDLLOVERRIDES="libglesv2=d"
wine64 $WINEPREFIX/drive_c/vrcx/VRCX.exe -no-cef-sandbox
```

That _should_ be the workaround for the blackscreen.

**Comment by TuxTheAstronaut** [comment]
@regalialong  just tried it and it seems to be working so far👍, thanks
