### ISSUE TITLE
[Feature Request] Save last FBT calibration, and restore it after a game restart/crash

### ISSUE THREAD

**Issue by Nicalay2** [vrcx-team/VRCX#863]
I'm probably the only one that cares about having a perfectly aligned FBT calibration (that I take time to do).

Having something that restore the last FBT calibration (in case if the game crash, or just restart because idk something broke and you need to restart it) would be life saving.

I am not joking, the amount of time I stopped my VRChat session because it crashed and I didn't want to spend 15min again on calibrating my FBT is countless.

I just hope this is possible with VRCX.

**Comment by Myrkie** [comment]
As far as we are aware FBT calibration is saved within the game and not at all saved externally like to a file or the windows registry so this will not be possible, it would be best for you to request a feature from VRChat directly via [canny](https://vrchat.canny.io/) as this is out of the scope of VRCX.
