### ISSUE TITLE
[Feature Request] i need ask a question

### ISSUE THREAD

**Issue by dracojoaquin1** [vrcx-team/VRCX#872]
is a ways to know whit this tool,how to know when someome mute you? or extensions for this tool?

**Comment by Natsumi-sama** [comment]
No, you can only see this information in-game by looking at their nameplate.

**Comment by dracojoaquin1** [comment]
> No, you can only see this information in-game by looking at their nameplate.

i know but this tool have extensions? because someome is say to me this tool have extensiosn then they can see if someome mute you

**Comment by Myrkie** [comment]
> > No, you can only see this information in-game by looking at their nameplate.
> 
> i know but this tool have extensions? because someome is say to me this tool have extensiosn then they can see if someome mute you

VRCX has no official extensions, extensions may exist by other people through forking this project but we do not at all endorse these as they could be used maliciously such as leading you on with fake information or attempt to steal your account login information. make sure to only use VRCX from official sources!

**Comment by Natsumi-sama** [comment]
Many years ago it was possible with mods, not anymore.

**Comment by dracojoaquin1** [comment]
> > > No, you can only see this information in-game by looking at their nameplate.
> > 
> > 
> > i know but this tool have extensions? because someome is say to me this tool have extensiosn then they can see if someome mute you
> 
> VRCX has no official extensions, extensions may exist by other people through forking this project but we do not at all endorse these as they could be used maliciously such as leading you on with fake information or attempt to steal your account login information. make sure to only use VRCX from official sources!

many thanks for the info

**Comment by dracojoaquin1** [comment]
> > > No, you can only see this information in-game by looking at their nameplate.
> > 
> > 
> > i know but this tool have extensions? because someome is say to me this tool have extensiosn then they can see if someome mute you
> 
> VRCX has no official extensions, extensions may exist by other people through forking this project but we do not at all endorse these as they could be used maliciously such as leading you on with fake information or attempt to steal your account login information. make sure to only use VRCX from official sources!

then you say if someome have extensions can edit logs and make it fake? like falsify records?

**Comment by Myrkie** [comment]
> then you say if someome have extensions can edit logs and make it fake? like falsify records?

you don't need extensions or modify VRCX to do this, our database technology is well known, its more about using unoffical versions could result in your account being compromised by whoever runs the unofficial version, but aside all of that what you are asking for is not possible as the status of being muted by someone is not shared over the API.
