### ISSUE TITLE
Group State Logging (left, deleted, name etc)

### ISSUE THREAD

**Issue by GenesisAria** [vrcx-team/VRCX#919]
Pretty simple, just logging joining and leaving groups, identifying groups that have been deleted, and also maybe groups that change their names.

**Comment by Natsumi-sama** [comment]
VRCX already does this.

**Comment by GenesisAria** [comment]
I see no logging or info anywhere on groups that have been deleted.  I only see the "cannot find group id" popup and that is it.

**Comment by Natsumi-sama** [comment]
'groupChange' is then event type, that popup is from friends joining deleted group instances.

**Comment by GenesisAria** [comment]
I guess i just haven't seen a group get removed then if it's recent.  Most recent change i see of any kind was the 30th.  I was thinking another group i was in was taken down.
