### ISSUE TITLE
[Bug] Discord Rich Presence shows Group Instances as public when they should be hidden & private

### ISSUE THREAD

**Issue by Junii23** [vrcx-team/VRCX#920]
**Describe the bug**
Using VRCX's Discord Rich Presence feature, while you are in a Group Instance, the Discord Rich Presence will show information about the instance as if it was a public instance (player count, world, group, etc.), however I believe these should be considered private instances and this information should be hidden. If someone who isn't invited to the group looks at you on the VRChat website or in-game, it shows you as in a private world, people need to be in the group and/or have a specific role before they can see the instance. Whether the group is public/private or open/request/invite, I believe it always shows as a public instance.

**To Reproduce**
1. Ensure VRCX's Discord Rich Presence is enabled and "Show Details in Private" is off. (Settings -> Discord Presence -> Enable)
2. Create & Join a Group only instance (Not Group+ or GroupPublic)
3. Look at your Discord Rich presence, it will show details about the instance.
4. Look at yourself on another account who isn't in the group, it will just show as 'private world.'

**Expected behavior**
Your Discord Presence should show as a private world, just like Invite or Invite+.

**Screenshots**
Here's a screenshot of my Discord Presence in an invite only and private group with the only the owner role being permitted to join (as restrictive of an instance as I could think of). Discord Presence is still showing the instance details:
![GroupDiscordPresenceTeehee](https://github.com/user-attachments/assets/aa91292b-3c69-4c3f-8edb-72eda8fda9b4)

**What version you are running**
VRCX Nightly 2024-09-14T09.04-58bb578

Apologies if this is intended behavior. I could see it being intended behavior for Group+ or GroupPublic, but I think for Group only specifically it should show as private.

**Comment by Natsumi-sama** [comment]
It was originally intended this way but I agree with this change.
