### ISSUE TITLE
[Feature Request] Autorestart SteamVR if crashed

### ISSUE THREAD

**Issue by BlackWolfWoof** [vrcx-team/VRCX#922]
**Explain in detail what your suggested feature would be used for.**
Currently VRCX is able to detect a game crash. Sometimes a crash also kills your stramvr though and the game doesn't auto restart.

**Describe how it would look if it requires a UI.**
It would be an additional toggle to restart steamvr in the same place the restart game on crash is placed at.

**Explain why people would want to use it.**
That way the headset can be kept on and if reconnected to steam link as example it would already be in the process of restarting the game and pulling me into the lobby.
Currently i have to put my headset down, walk to my pc and restart stramvr.

**Comment by Natsumi-sama** [comment]
Hmmm maybe it could be a toggle but that's intended behavior because when SteamVR closes the game while stopping SteamVR, VRCX detects this has a false positive game crash so it wont start VRChat again if SteamVR isn't running anymore.
