### ISSUE TITLE
can no longer login

### ISSUE THREAD

**Issue by FlareSnare** [vrcx-team/VRCX#923]
**Describe the bug**
I enter my username and password and click login.
It brings up the 2FA window and removes my username and password i just entered, acting like i never typed it in. When putting the 2FA code in, it fails to log me in due to there no longer being a username and password in the login boxes.

![image](https://github.com/user-attachments/assets/cedb9e1b-ac64-4e3b-ba12-c1fa0e38f89d)
![image](https://github.com/user-attachments/assets/eae6c2c9-0030-4299-bb00-c6e45c47d63f)
![image](https://github.com/user-attachments/assets/801fe408-34a9-4149-ae50-ac8956f6de9b)

It just removes my username and password before logging me in.

**Comment by loukylor** [comment]
Are you on the latest version of VRCX?

**Comment by Natsumi-sama** [comment]
Try login with the website, this error almost always means you put in the wrong 2FA code.

**Comment by FlareSnare** [comment]
> Try login with the website, this error almost always means you put in the wrong 2FA code.

The website works fine. The username and password disappears before its able to complete the login process.

**Comment by FlareSnare** [comment]
> Are you on the latest version of VRCX?

I have tried the latest version and the previous version aswell.

**Comment by Natsumi-sama** [comment]
> The website works fine. The username and password disappears before its able to complete the login process.

This is the intended behavior and wont impact the login process.

**Comment by Pyrii** [comment]
I got this recently, I got logged out after leaving my computer alone awhile, Now I have to put my 2FA in every time I restart my PC.

**Comment by Natsumi-sama** [comment]
This normally occurs when changing IP address or using a VPN, the game and website should behave the same in this regard.

**Comment by Pyrii** [comment]
Neither of these occur in this case.

> This normally occurs when changing IP address or using a VPN, the game and website should behave the same in this regard.

**Comment by Natsumi-sama** [comment]
You could try reset VRCX by renaming `%AppData%\VRCX` and see if it lets you login after that.
