### ISSUE TITLE
[Bug] Friend log not loading, 'Friended' not loading on all friends

### ISSUE THREAD

**Issue by morgona** [vrcx-team/VRCX#924]
When I opened the application, I clicked on a friend to see when we added each other but it's not showing up. This happens with all the friends I have, even the ones online. Friend log does not show anything even though I have friends. Filters on friend log do not work, to try and fix that issue. 

1. I opened the VRCx application on desktop (I'm on Windows)
2. click on a friend
3. I looked for "friended" and it shows a - , it does this for all friends on my list, even the ones online.

I'm pretty sure the 'friended' is supposed to show when you added someone or when you and another person officially became friends.

Screenshot (302)(https://github.com/user-attachments/assets/b45c3da3-7654-4ec0-b78c-9c4080642be4)

I'm on the latest version, it says VRCX 2024.09.02

**Comment by Myrkie** [comment]
friended date comes from the SQL Database, if you friended someone without vrcx running then that data will not be present

**Comment by morgona** [comment]
Ohh okay, thank youOn Sep 25, 2024, at 5:17 PM, Myrkur ***@***.***> wrote:﻿
friended date comes from the SQL Database, if you friended someone without vrcx running then that data will not be present
