### ISSUE TITLE
[Bug] Most Invites and InviteRequests are deleted on closing VRCX

### ISSUE THREAD

**Issue by marhuber** [vrcx-team/VRCX#931]
**Describe the bug**
I've noticed this for pretty much the entire year and a half I've been using VRCX. I love this tool, but it frustrates me that if it should freeze up (something else happening lately that might be due to needing a graphics driver update, need to try that first before I consider another bug report here) or my computer crash or something, nearly all Invite and Inviterequests from a session using VRChat and VRCX will just auto delete when the application is closed and reopened. 

Part of why I use this tool is that I want to keep track of which friends have been trying to spend time with me while I'm busy; so I can remember to make time for them when I'm free. It's also nice to know who wanted to see me while I was nodding off or afk and left VRChat and VRCX open. Other types of notifications are being purged too, but I'm most concerned about those two types being logged more reliably. Like how people leaving and joining the instance or logging on and logging off seem to be.

**To Reproduce**
1. Open and use VRCX while in VRChat.
2. Continue until you have several or more notifications in the log.
3. Close VRCX.
4. Reopen VRCX.
5. Open notifcations tab and note that some Invites and InviteRequests have been purged arbitrarily while others are saved in the log, unless the bug is unique to me and I did something wrong during setup or something.

**Expected behavior**
VRCX keeps a consistently saved log of all recent Invites, InviteRequests, and maybe other such notifications the way it keeps a log of a lot of other activity like people joining and leaving your current instance or going on and offline.

**What version you are running**
VRCX 2024.09.02
I always let the app update though, and it's happened across every version I can remember in the past year and half or so.

**Comment by Natsumi-sama** [comment]
The only thing the comes to mind is VRCX doesn't save self invites persistently but only for the session, as for other things not saving that does sound quite odd and has never been reported before, you could use something like [sqlitebrowser](https://sqlitebrowser.org/) to verify table entries are being saved to the database as they come in. Or open DevTools with `Ctrl + Shift + I` and check the console tab for notification or database related errors.

**Comment by SalbugVR** [comment]
I've noticed this as well, but for some reason never really thought to report it.

**Comment by marhuber** [comment]
I have DevTools open and I'll keep that open as I get on later this evening. So far with Group notifications I haven't noticed errors related to either of those, just some 404 not found ones that seem to be related to the VRChat api that popped up a bit ago.. Unfortunately by the time I saw you reply earlier things were petering out as far as my social circles last night and I myself was heading to bed soon. 

Where exactly does VRCX save the log of VRChat notifications? I could also check if there's anything funky with the permissions for that file and see if I can compare it with a usual night's activity and see what actually made it into the file and what didn't.

**Comment by Natsumi-sama** [comment]
Open `%AppData%\VRCX\VRCX.sqlite3` with sqlitebrowser to see the table with the stored notifications, all VRCX data is saved in this file.

**Comment by marhuber** [comment]
Thanks. Looks like the database has all the invites and requests going back to the day I first started using this application, but the application is very selective in what it loads from the database and presents to me. I will try to check later if there is a pattern, like it loads every tenth or so or something. I wouldn't expect it to load everything when the application is started up, just all of the latest couple hundred or so would be more practical for default behavior, I think. 

Also, most group notifications aren't being logged. But I'm much less concerned with those, since they're also on the group pages and we have the group instance tab in game and in VRCX anyways.

**Comment by Natsumi-sama** [comment]
RIGHT, thanks that's the exact info I needed I can see the bug now, will be fixed in next nightly. And yes group notifications not being logged is intended I never got around to implementing that.

**Comment by marhuber** [comment]
The update worked great. I should've posted here months ago. And yeah, Group notifications aren't all that important to me. They would clutter the database with weekly meet announcements and other such unneeded data. Invites and Requests are more personal and therefore more valuable to keep track of. At least that's how I feel about it. 

In fact the notification tab is the area I look at the most. Because I hate how Invites and Requests get deleted after 15 minutes. I wish VRChat would make them hang around a lot longer like group notifications, give me a chance to acknowledge I saw them at least; even if the actions available beyond dismissing them have all long since expired.
