### ISSUE TITLE
[Bug] System.InvalidOperationException: Could not execute method: SweepCache() 

### ISSUE THREAD

**Issue by BlackWolfWoof** [vrcx-team/VRCX#935]
**Describe the bug**
Does not sweep cache upon clicking sweep cache button.

**To Reproduce**
*I have my set set to 200GB 90 days.*
Hit the `Sweep Cache` button or use `Automatically Manage Cache When Closing VRChat`

**Expected behavior**
It sweeps the cache that is old

**Screenshots**
![image](https://github.com/user-attachments/assets/eb171e24-64d1-48e5-b5fc-765951bc2821)

**What version you are running**
Version 2024.09.02

**Comment by Myrkie** [comment]
this has been fixed in a pull request that has yet to be merged https://github.com/vrcx-team/VRCX/pull/928

**Comment by BlackWolfWoof** [comment]
Ah my bad, haven't checked. Thanks for the quick reply 🫡.
