### ISSUE TITLE
Won't open at all on PikaOS 4 (Debian/Linux)

### ISSUE THREAD

**Issue by Jakeh9777** [vrcx-team/VRCX#938]
VRCX won't launch at all

I installed it using [the instructions from here](https://github.com/vrcx-team/VRCX/blob/master/Linux/README.md) and it installs just fine but when I try to open it nothing happens. Nothing pops up at all.

Version: Newest I believe.

Specs:
## Hardware Information:
- **Hardware Model:**                              ASRock B450M-HDV R4.0
- **Memory:**                                      32.0 GiB
- **Processor:**                                   AMD Ryzen™ 9 5900X × 24
- **Graphics:**                                    NVIDIA GeForce RTX™ 2060
- **Disk Capacity:**                               3.0 TB

## Software Information:
- **Firmware Version:**                            P10.10
- **OS Name:**                                     PikaOS 4
- **OS Build:**                                    (null)
- **OS Type:**                                     64-bit
- **GNOME Version:**                               47
- **Windowing System:**                            Wayland
- **Kernel Version:**                              Linux 6.11.3-pikaos

**Comment by Jakeh9777** [comment]
Am I missing something? I even tried in Lutris and this is what's happening.
![image](https://github.com/user-attachments/assets/8b867caa-e95b-404b-9174-286bc7a2ef87)

**Comment by Natsumi-sama** [comment]
Install script has been updated, if it still doesn't work reopen issue.

**Comment by Jakeh9777** [comment]
I ran the script and it installed. Looks like its running but nothing shows up at all like I mentioned above when I installed it through Lutris. 
![image](https://github.com/user-attachments/assets/9000e3c3-65ba-46b8-b5ba-aca3b82e7984)
