### ISSUE TITLE
[Bug] Searching Friends Function not work

### ISSUE THREAD

**Issue by iashbringer** [vrcx-team/VRCX#939]
Enter in the search box, but the reasult  list is empty.

![fm1](https://github.com/user-attachments/assets/dffa5195-00d4-4d78-ab3d-3ff69161ad74)

version:20241011, There is no problem in the previous version

**Comment by loukylor** [comment]
This is likely an issue with localization settings. Do you mind setting your language to english and trying again?

**Comment by iashbringer** [comment]
> This is likely an issue with localization handling. Do you mind setting your language to english and trying again?

I tried it and it worked. When I switched back to zh-CN.it still worked. When I restarted again, it didn't work.

**Comment by loukylor** [comment]
Alright, I'll look into pushing a fix soon then
