### ISSUE TITLE
[Feature Request] Ability to hide past names

### ISSUE THREAD

**Issue by MagicalNET** [vrcx-team/VRCX#955]
**Explain in detail what your suggested feature would be used for.**
Opting out from past stored names would be beneficial for privacy & safety.

**Describe how it would look if it requires a UI.**
Toggle opt out for past display names

**Explain why people would want to use it.**
privacy mainly

**Comment by Myrkie** [comment]
not really a possibility, VRCX just stores what the API returns, it would also require a way to track who doesn't want to be logged, that would require a server of some sort and a way to verify peoples requests to make sure they are the owner of the account that don't want to be logged, and that's completely out of scope for VRCX.
