### ISSUE TITLE
[Bug] player list couldn't loaded any data

### ISSUE THREAD

**Issue by jiaqiangmo2023** [vrcx-team/VRCX#956]
**Describe the bug**
 player list couldn't loaded any data.

**To Reproduce**
when i try to update the lastest version , it  still doesn't work
**Expected behavior**
player list couldn't loaded any data, could you guys have any way to fix it or reset?
**Screenshots**
![image](https://github.com/user-attachments/assets/c490eb7c-0c49-4c46-955f-0a4941799578)

**What version you are running**
VRCX Nightly 2024-10-24T10.57-cca4e5d

**Comment by Natsumi-sama** [comment]
Does gameLog tab work? Did player list work for you in the past?

**Comment by jiaqiangmo2023** [comment]
> Does gameLog tab work? Did player list work for you in the past?

how do I know gameLog tab work or not? my player list  always been like this blanktab all the time ? where should I open it or restart it ?

**Comment by Natsumi-sama** [comment]
It's the tab above playerList, are you using a Quest in standalone mode?

**Comment by jiaqiangmo2023** [comment]
> standalone mode

 no, I am using pc, byw, what is standalone mode?

**Comment by jiaqiangmo2023** [comment]
when the author told me to go into %localappdata%low/vrchat/ and then delete whole vrchat folder , restart the vrchat and vrcx. it works now ,thx a lot
