### ISSUE TITLE
[Bug] Enabling overlay causes all of vrcx to crash

### ISSUE THREAD

**Issue by TRSMML** [vrcx-team/VRCX#957]
enabling the steamVR overlay causes vrcx to crash, and continues to crash every time it attempts to starts the overlay

(probably) relevent specs
AMD Ryzen 5 6600HS Creator Edition
16GB ram
Nvidia RTX 3050 mobile 4GB

**Comment by Natsumi-sama** [comment]
Could you upload your last crash dump? `%localappdata%\CrashDumps\`

**Comment by TRSMML** [comment]
[VRCX.exe.20612.zip](https://github.com/user-attachments/files/17526884/VRCX.exe.20612.zip)

**Comment by konsti219** [comment]
Also experiencing this. Maybe this is related to GPU accelerated rendering and having an integrated GPU?

**Comment by BenjaminZehowlt** [comment]
This is an issue with Nvidia Optimus, and similar technologies for AMD. In windows settings set VRCX to use the high perf gpu.

**Comment by Natsumi-sama** [comment]
Please give the latest nightly build a try and let us know how it goes.
