### ISSUE TITLE
[Bug] database upgrade failed, check console for details

### ISSUE THREAD

**Issue by bia-1** [vrcx-team/VRCX#962]
I get this popup every time i open vrcx, i just downloaded it. It gets me nothing, all the pages are empty.
![Screenshot_17](https://github.com/user-attachments/assets/77856ff8-1dc6-48c3-bf35-c42c39541122)

**Comment by Natsumi-sama** [comment]
I'll investigate it, for now if you install an older version first then upgrade it might work.

**Comment by bia-1** [comment]
should i delete this verison and how far back should i install?

**Comment by Natsumi-sama** [comment]
or try run the command manually `database.setWal();` or delete `%AppData%\VRCX`

**Comment by bia-1** [comment]
would i just copy and paste the command in console?

**Comment by Myrkie** [comment]
Copy paste the command in console, you may have to type `'allow.pasting'` before to allow pasting.
