### ISSUE TITLE
[Bug] [Niche] URI links only open when VRCX is closed

### ISSUE THREAD

**Issue by quazi00** [vrcx-team/VRCX#966]
**Describe the bug**
URI links only open when VRCX is closed

**To Reproduce**

1. grab a URI link i.e 
```
USER -  vrcx://user/usr_ID
GROUP - vrcx://group/grp_ID
AVATAR - vrcx://avatar/avtr_ID
WORLD - vrcx://world/wrld_ID
AVTARDATABASE - vrcx://addavatardb/LINK
```
(all the ones I've tested)

2. put the URI into the browser and press enter and press allow on the pop-up for "Do you want to open "VRCX" "

IF it's closed it will work as expected and open VRCX

IF it's open already nothing will happen. it will not even focus the VRCX app 

**What version you are running**
VRCX2024.10.25

**Comment by Natsumi-sama** [comment]
I have a feeling this is already fixed in latest nightly build, give that a try.

**Comment by quazi00** [comment]
yup just tried this is working again thanks
