### ISSUE TITLE
[Bug] Player List / Game log not working proprely.

### ISSUE THREAD

**Issue by m1ch-the-unlikely** [vrcx-team/VRCX#967]
Just noticing since two days now, VRCX keeps logging players with their userID in their name, and when i try to check their profile, it keeps opening the search bar instead of showing their profile. It also doesn't show up in the join count either.

https://gyazo.com/613b0dd1ec0025603e72cb55c6fa2d2e

I have tried updating to latest version, and it didn't fix anything. Hope to get some reason behind this.

**Comment by OctoFloofy** [comment]
Please update VRCX

**Comment by OctoFloofy** [comment]
Could try updating to the Nightly version

**Comment by Myrkie** [comment]
latest nightly will retroactively fix userids being in names, but please update, the new version handles the new format properly.

**Comment by m1ch-the-unlikely** [comment]
> latest nightly will retroactively fix userids being in names, but please update, the new version handles the new format properly.

That has fixed it, thank you.
