### ISSUE TITLE
[Bug] SteamVR Overlay Crash 

### ISSUE THREAD

**Issue by ShaderMember** [vrcx-team/VRCX#968]
I had an issue when i was in vr the steamvr overlay would cause vrcx to crash i was able to solve the issue by making it run off of my gpu but i still had an issue where if it runs on integrated graphics the overlay would continuously crash but vrcx would still be running 
it doesn't show up in the logs either

**Comment by Natsumi-sama** [comment]
Could you try the latest nightly build? https://github.com/vrcx-team/VRCX/issues/957

**Comment by ShaderMember** [comment]
im on the nightly build. im still having the same issue with the overlay not showing when i run vrcx off of integrated graphics. it shows like its trying to but it closes the very second it opens and continuously goes on and off.

**Comment by Natsumi-sama** [comment]
Ah the change in the nightly build forces the use of your "high performance" GPU maybe stable will work for you instead.

**Comment by ShaderMember** [comment]
alright well it works when i have it set to let windows decide on nightly build

**Comment by Natsumi-sama** [comment]
Okay thanks good to know, we'll have to take a different approach when deciding what GPU to use.

**Comment by ShaderMember** [comment]
alright well good luck and i hope i was helpful.
