### ISSUE TITLE
[Bug] VRCX Wrist Overlay VRAM Leak.

### ISSUE THREAD

**Issue by GYSS1204** [vrcx-team/VRCX#970]
**Describe:**
After enabling the wrist overlay in VRCX, while playing VRChat, the VRAM usage of VRCX continuously increases. Forcefully closing the VRCX software releases the occupied VRAM.

VRCX wrist overlay settings: SteamVR overlay enabled, wrist dynamic overlay enabled, hide private worlds disabled, launch with VRChat enabled, overlay button held, use gray background enabled, use mini icons enabled, show VR device enabled, show CPU usage enabled, show game duration enabled, show computer boot duration disabled.

**Other information:**
The VRAM leak issue recently occurred and is likely caused by the update to version 2024.10.25.

**Software and system information:**
VRCX version: 2024.10.25  
Operating system: Windows 10 Pro 22H2  
CPU: AMD Ryzen 7 7800X3D 8-Core Processor  
RAM: 32GB  
Graphics card: AMD Radeon RX 7900XT  
Graphics driver version: 24.10.1

**Comment by kunanaxp** [comment]
You need to disable GPU hardware acceleration
