### ISSUE TITLE
[Bug] Blurry text on every version past Stable v2024.10.11 (nightly included)

### ISSUE THREAD

**Issue by MintDoq** [vrcx-team/VRCX#971]
**Describe the bug**
Sometimes random parts of the UI will go blurry until you hover over it or open some other part of VRCX

**To Reproduce**
No real way to reproduce, it just seems to happen random when using VRCX or switching tabs

**Expected behavior**
Just not to have blurry text or spots

**Screenshots**
![{3B2C11EB-25C3-4BDE-B07A-6A8E30A2FA76}](https://github.com/user-attachments/assets/95094f14-bbf7-4c6f-893d-fbea66161408)

**What version you are running**
VRCX Nightly 2024-11-02T03.14-0abf43b

**Comment by Natsumi-sama** [comment]
My first guess is it being an issue with GPU Acceleration, try run with `--disable-gpu`

**Comment by MintDoq** [comment]
I would do this in the advanced settings and under launch options correct? This is something i never ran into so im not sure

**Comment by Myrkie** [comment]
> I would do this in the advanced settings and under launch options correct? This is something i never ran into so im not sure

no you would do this from a shortcut

**Comment by MintDoq** [comment]
what do you mean by shortcut?

**Comment by Myrkie** [comment]
> what do you mean by shortcut?

as in a launch shortcut to the application, such as one on your desktop, right click VRCX.exe, [create shortcut and in the target add the argument. ](https://www.digitalcitizen.life/shortcut-arguments-parameters-windows/)

**Comment by MintDoq** [comment]
Seems to have worked, thank you! That issue was keeping me from wanting to using an version past 2024.10.11 but its fixed now. Appreciate it
