### ISSUE TITLE
Wierd visual glitch?

### ISSUE THREAD

**Issue by lilstavo** [vrcx-team/VRCX#974]
Yeah I've never gotten this in previous builds and I'm trying to figure out any solutions for this issue.

![Screenshot 2024-11-06 170844](https://github.com/user-attachments/assets/2529b98e-d802-48a3-ac31-16a26b3f2132)

**Comment by BLANKE1** [comment]
This most likely is due to GPU acceleration, try running VRCX with the `--disable-gpu` launch option. To further help fix this issue what GPU do you have? Which drivers are you on?

**Comment by lilstavo** [comment]
Looks like the launch option worked! thank you very much bro
