### ISSUE TITLE
[Bug] Friend log is spammed with name changes from friends switching between VRC account and non-vrc account

### ISSUE THREAD

**Issue by EnderShadow** [vrcx-team/VRCX#975]
**Describe the bug**
I have a few friends where multiple times a day their name switches to and from the name associated with their VRC account and their steam/meta account. At least I think that's what's happening. All I can observe is that I repeatedly see the name change back and forth between something like "Username" and "Username 89d9".

**To Reproduce**
I unfortunately don't know how to purposefully reproduce it, but it's happened every day for at least a week.

**Expected behavior**
Friend list does not spam name changes from rapid name changes between VRC and non-vrc account.

**Screenshots**
![Capture](https://github.com/user-attachments/assets/d6c5bb17-cb7f-4f41-9641-2d0f49c52aec)

**What version you are running**
Version 2024.10.25

**Comment by Myrkie** [comment]
this is an API bug, VRChat has been notified, not much we can do.
