### ISSUE TITLE
[Feature Request] Locally stored vrc+ emotes/stickers for quick swapping

### ISSUE THREAD

**Issue by Synzzz** [vrcx-team/VRCX#980]
**Explain in detail what your suggested feature would be used for.**
A feature to store vrc+ emotes/stickers locally in the vrcx local db, similar to local saved worlds and a button to enable them to reupload with a click of a button instead of having to find the source pic, set the mode, or set the sprite sheet settings for gifs. 

**Describe how it would look if it requires a UI.**
A checkbox next to the currently "loaded" vrc+ emotes/stickers that you can untick to delete them but keep in the local vrcx db, then be able to reupload them with the same settings with a checkbox

**Explain why people would want to use it.**
9 emotes/stickers just dont seem to be enough most the time but swapping between them is a pain

**Comment by Natsumi-sama** [comment]
The website supports uploading images with settings in the file name e.g. `CoolEmoji_14frames_10fps.png` VRCX could expand on this for other settings and add settings to filename when saving images.

**Comment by Synzzz** [comment]
that'd be a good thing too, but I think its more about keeping the pics in a cached gallery view for easier reupload from the UI. The delete button could have an also delete from local emote library toggle on it that would work as a non-soft delete

**Comment by Natsumi-sama** [comment]
Would be too far out of scope for VRCX.
