### ISSUE TITLE
[Feature Request] Make VRCX work with Mullvad Split Tunneling

### ISSUE THREAD

**Issue by HugPhiluu** [vrcx-team/VRCX#981]
**Explain in detail what your suggested feature would be used for.**
VRCX works fine with split tunneling on other VPNs, but for some reason, it doesn’t with Mullvad. Even when I add it to the list of excluded apps, it still doesn’t behave as expected.

**Describe how it would look if it requires a UI.**
Figure out why it’s not working and make it compatible. I’m guessing it’s something in the back-end, so probably no UI changes needed just make it work seamlessly.

**Explain why people would want to use it.**
A lot of people (like me) use Mullvad for privacy and security, and split tunneling is super useful to exclude certain apps. It’d be great to use VRCX without having to completely turn off the VPN.

**Comment by Natsumi-sama** [comment]
It's a know issue with Mullvad, you can work around it by setting up a socks5 proxy.
https://mullvad.net/en/help/socks5-proxy

**Comment by HugPhiluu** [comment]
Set it up Windows-Wide or is it possible to do it through the proxy settings of vrcx itself?

**Comment by Natsumi-sama** [comment]
Oh you want to exclude, this is only for when using an app whitelist.
VRCX has socks proxy settings in `Settings -> General -> Proxy Settings`
But if you're wanting VRCX to ignore your system proxy settings that will need to be its own toggle added in an update.

**Comment by HugPhiluu** [comment]
Apologies, I am confused at this point 😅
When I use a VPN to log into VRCX I get the following error:
![image](https://github.com/user-attachments/assets/df9e566c-4dd3-4da4-88ff-c4526524d51f)

It has only been an issue with Mullvad as I have used other VPNs in recent years and accessed this application.
ProtonVPN doesn't have an issue setting up tunnelling with vrcx, whilst mullvad does. Arguably this is probably an issue on mullvads part, but this issue is exclusive in combination with vrcx so I hoped that you guys may have an idea or at least could help with fixing it (though I am totally using socks proxy in my browser now, thanks xD)

**Comment by Natsumi-sama** [comment]
If you change Mullvad to only proxy selected apps instead of all apps with exceptions it would be one such work around.
Otherwise us adding an option to VRCX to ignore system proxy settings should allow you to use VRCX without a VPN even though your VPN is enabled system wide.

**Comment by HugPhiluu** [comment]
I see, I understand now.
Sadly the Windows version of Mullvad doesn't support the workaround you mentioned, so I'll be stuck turning my VPN off occasionally. Thank you for the quick replies!

**Comment by Natsumi-sama** [comment]
https://www.bitdefender.com/consumer/support/answer/1979/
When setting one of these apps to use "no proxy" does this bypass Mullvad? if that works then this option could be added to VRCX.

**Comment by HugPhiluu** [comment]
I tried it with firefox, it does not bypass Mullvad

**Comment by HugPhiluu** [comment]
I could sponsor a fiver so that you can get mullvad and test a few things yourself if you'd like

**Comment by Natsumi-sama** [comment]
Ah damn no such luck then, nah it's okay I think if that doesn't work then there is nothing more we can do. You'd be better off creating a support ticket with Mullvad.
