### ISSUE TITLE
[Bug] friends list not loading 

### ISSUE THREAD

**Issue by AFKDARK** [vrcx-team/VRCX#993]
resently i got a starlink and ever since then my friends list wont load 
**What version you are running**
Version VRCX Nightly 2024-11-26T05.04-2e136a0

**Comment by AFKDARK** [comment]
FIX: just delete save login and relogin

**Comment by AFKDARK** [comment]
UPDATE: so i got the friendss list backup but now my auth token wont work when it is requested by vrcx

**Comment by Natsumi-sama** [comment]
Which error do you get? have you tried using the VRC website?

**Comment by Natsumi-sama** [comment]
There is an issue with some weird characters in passwords, try change your password to something more simple.

**Comment by KnightDemons** [comment]
> resently i got a starlink and ever since then my friends list wont load **What version you are running** Version VRCX Nightly 2024-11-26T05.04-2e136a0

Same problem and Starlink user as well.

**Comment by AFKDARK** [comment]
> > resently i got a starlink and ever since then my friends list wont load **What version you are running** Version VRCX Nightly 2024-11-26T05.04-2e136a0
> 
> Same problem and Starlink user as well.

heyquick question if you go on vcc (vrchat creator companion) dsoe that work too

**Comment by AFKDARK** [comment]
ok so i found out that if i use a vpn everythink works fine so i guess its something to dowith the fact thatspace isent a location or something
